### ISSUE TITLE
REST interface component - receiving JSON data into models

### ISSUE THREAD

**Issue by stenerikbjorling** [biolab/orange3#6094] opened 2022-08-13 10:37 UTC
**What's your use case?**

Database systems such as Postgres can act as REST services servers and deliver their search sets in the form of JSON. Allowing direct access to such functionality allows for data transfer without transformations that increases the risks and challenges.

**What's your proposed solution?**

Utilise the current SQL object and allow the data received to be in the form of JSON that internally also can be transformed into CSV.

**Are there any alternative solutions?**

**Comment by janezd** [comment] 2022-10-07 11:22
You're right Orange's capabilities to access databases are very limited. There's a lot of other functionality that we'd like to have, but we don't. The problem is that none of current core developers can invest time for that, nor do we currently have any projects related to databases. We're closing this issue not because we disagree, but because we can't see it solved in foreseeable future. But if you can do it, you are more than welcome to contribute.

**Closed by janezd** 2022-10-07 11:22 UTC

**Comment by stenerikbjorling** [comment] 2022-10-11 09:27
Hi,

I have recommended use of Orange3 in a couple of Horizon Europe projects in regard to analysis etc. Maybe I can promote custom development of JSON data interoperability since this will be the preferred method of interacting with several data sources. I will see what I can do - I myself is quite busy at this time and in a potential future.

Take care, all the best…

Stene

_____
Sten-Erik Björling
Enviro Data
Kyrkogatan 5A 2 tr
SE-972 32  Luleå
Sweden

E-Mail: ***@***.***
Mobile: +46-70-655 11 72
Wire: @stenerikbjorling
Skype: stenerikbjorling
iChat: ***@***.***
Signal: +46 70 655 11 72
FaceTime: ***@***.***
Telegram: @stenerikbjorling
Hotmail / Messenger: ***@***.***
GMail: ***@***.***
______

This email and any files transmitted with it are confidential, may be legally privileged and are intended solely for the use of the individual or entity to whom they are addressed. If you are not the intended recipient, please note that any use, distribution, or reproduction of the contents of this email is strictly prohibited and may be unlawful. If you are not the intended recipient, please notify the sender by return email and destroy all copies of the original message including any attachments thereto. Thank you.

Please note that we take reasonable precautions to prevent the transmission of viruses; however, we cannot guarantee that this email or its attachments are free from viruses. We only send and receive emails on the basis that we are not be liable for any loss or damage resulting from the opening of this message and/or attachments.

> 7 okt. 2022 kl. 13:22 skrev Janez Demšar ***@***.***>:
> 
> You're right Orange's capabilities to access databases are very limited. There's a lot of other functionality that we'd like to have, but we don't. The problem is that none of current core developers can invest time for that, nor do we currently have any projects related to databases. We're closing this issue not because we disagree, but because we can't see it solved in foreseeable future. But if you can do it, you are more than welcome to contribute.
