### ISSUE TITLE
error on installing

### ISSUE THREAD

**Issue by neulf** [biolab/orange3#4807] opened 2020-05-23 09:57 UTC
**Describe the bug**

error on installing.

**To Reproduce**

Steps to reproduce the behavior go **here**:
1. install
2. ParseError: Could not parse explicit URL: file:///C:/Users/jason/AppData/Local/Temp/nsi9B81.tmp/Orange-installer-data/conda-pkgs/blas-1.0-mkl.conda

"conda" command exited with 1. Cannot continue.

**Orange version:**
Orange - About - 3.25

**Operating system:**
Windows

**Additional context**
none.

**Comment by ales-erjavec** [comment] 2020-05-25 07:15
Duplicate of gh-4772

**Closed by ales-erjavec** 2020-05-25 07:15 UTC
Labels: bug report
