### ISSUE TITLE
Evaluate owpredictions: Click report error

### ISSUE THREAD

**Issue by 17865653325** [biolab/orange3#5097] opened 2020-11-27 07:15 UTC
![image](https://user-images.githubusercontent.com/68682057/100421331-24421a80-30c3-11eb-8481-88262c43c189.png)

**Comment by ajdapretnar** [comment] 2020-11-27 07:54
Thanks for reporting it. Duplicate of #5074.

**Closed by ajdapretnar** 2020-11-27 07:54 UTC
Labels: bug report
