### ISSUE TITLE
Rounding error in PCA

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#5157] opened 2021-01-04 15:41 UTC
- [x] **What's wrong?**

There is a rounding error in the PCA widget.
It comes up very rarely but it does appear sometimes.

- [x] **How can we reproduce the problem?** 

A bit of patience will produce it with general workflows I think. 

- [x] **What's your environment?**

- Operating system: Windows 10
- Orange version: Quasar 1.0.0
- How you installed Orange: Windows installer

![image001](https://user-images.githubusercontent.com/6304794/103551976-78eb6900-4eab-11eb-9656-215efa2ad93c.png)

**Comment by borondics** [comment] 2021-01-15 08:32
I found another rounding error in the `Confusion Matrix` (see DNA column).
![image](https://user-images.githubusercontent.com/6304794/104700457-79d69300-5714-11eb-84f7-beb4b65d1faa.png)

For this workflow I used the Liver Spectroscopy dataset from `Datasets`

**Comment by VesnaT** [comment] 2021-01-18 08:08
As explained in #5191, this is intentional behaviour, so I'm closing the issue.

**Closed by VesnaT** 2021-01-18 08:08 UTC
Labels: bug report

**Comment by markotoplak** [comment] 2021-01-18 08:23
@borondics, we suspect that is intentional, because the text selector specifies the minimum variance covered. I'd guess that the problem seems to appear because the one in the graph is rounded (for example from 0.9895 to 0.990).

If you think there is an additional problem, point us to a data set where we can reproduce it.
