### ISSUE TITLE
Add automatic 'optimal alpha' for LASSO

### ISSUE THREAD

**Issue by belg4mit** [biolab/orange3#6674] opened 2023-12-12 19:14 UTC
Implementing an optional automatic "optimal alpha" selection for regularized regressions would make Orange more powerful. This article appears to outline a method for doing so using cross-validation: [https://tahera-firdose.medium.com/lasso-regression-a-comprehensive-guide-to-feature-selection-and-regularization-2c6a20b61e23#d452](https://tahera-firdose.medium.com/lasso-regression-a-comprehensive-guide-to-feature-selection-and-regularization-2c6a20b61e23#d452)

**Comment by janezd** [comment] 2023-12-12 22:59
This is a duplicate of a more general https://github.com/biolab/orange3/issues/1327. We would like to have this in Orange, but it is difficult to design a general framework for parameter optimization.

Even for something as simple as regularization of logistic regression, the user would at least need to choose the target score, e.g. AUC. ... And what about sampling? It is one thing to write a guide on Medium that shows how to write a few lines of code for some particular toy data set, but Orange needs to cover a range of cases. K-fold CV is OK, when the data is not too large; if training is slow and data is huge, one should better use a single validation set. Should Orange try to guess? Or should we let the user choose it?

And --- note again that this is just for the simplest case, logistic regression. In SVM you would probably do some kind of grid search across a number of specified parameters and their ranges. How do we specify, in general, a list of tweakable parameters and their ranges?

Thank you for your suggestion. It is already in the list of ideas (#4090) that we hope to implement some day.

**Closed by janezd** 2023-12-12 22:59 UTC
