### ISSUE TITLE
show help not working

### ISSUE THREAD

**Issue by erikafuna** [biolab/orange3#6700] opened 2024-01-09 14:22 UTC
**What's wrong?**

The "Show Help" function of widgets isn't working properly, except the preview: the option "More" in the preview box of "Show Help" doesn't open when clicking on it. 
When opening a widget, the "Show Help" icon doesn't open either.

Uploading Screen Recording 2024-01-09 at 15.09.14.mov…

**How can we reproduce the problem?** 
 
 
Place any widget on the canvas, click on it, click on the orange "Show Help" icon at the bottom left of the window. Click on the option "More" in the "Show Help" preview window. Nothing happens.
Place any widget on canvas, double click on it, in the new window, click on the "Show Help" icon bottom left. Nothing happens.

**What's your environment?**

- Operating system: Mac
- Orange version: 3.36.1
- How you installed Orange: from DMG

**Comment by processo** [comment] 2024-01-09 16:22
I can confirm this on Windows 10. Right click > Help also does nothing. Log gives the same error:
```
2024-01-09 17:06:08,247:ERROR:qasync._QEventLoop: Task exception was never retrieved
future: <Task finished name='Task-11' coro=<CanvasMainWindow.whatsThisClickedEvent.<locals>.run() done, defined at C:\Program Files\Orange\lib\site-packages\orangecanvas\application\canvasmain.py:2349> exception=RuntimeError('no running event loop')>
Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\application\canvasmain.py", line 2352, in run
    url = await query_coro
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\help\manager.py", line 127, in search_async
    return await provider.search_async(desc, timeout=timeout)
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\help\provider.py", line 133, in search_async
    await asyncio.wait_for(reply_f, timeout)
  File "C:\Program Files\Orange\lib\asyncio\tasks.py", line 435, in wait_for
    loop = events.get_running_loop()
RuntimeError: no running event loop
```

**Comment by processo** [comment] 2024-01-09 16:32
Likely duplicate of #6609.

**Comment by frankyates06** [comment] 2024-01-10 17:40
Is this problem solved? I am running orange3 on pc and I can’t have the help box showing anything useful when I click on help.

**Comment by PrimozGodec** [comment] 2024-01-18 15:11
It is a duplicate of https://github.com/biolab/orange3/issues/6609, so I am closing it. 

In #6609 I wrote:
 
> I just tested the issue and can confirm that the error should be fixed in https://github.com/biolab/orange-canvas-core/pull/281. This can be fixed by installing a new installer with version 3.36.2. It was already published on the website (a week ago) but was removed this morning since we noticed one other issue. We are building a new installer and reuploading it to the website soon.

Keep tracking #6609. We will post there when the new installer is ready.

**Closed by PrimozGodec** 2024-01-18 15:11 UTC
Labels: bug report
