### ISSUE TITLE
OWRank: Outdated setting

### ISSUE THREAD

**Issue by VesnaT** [biolab/orange3#1712] opened 2016-11-04 09:35 UTC
##### Orange version

3.3.8

##### Expected behavior
Widget should not crash even though settings has not been reset.

##### Actual behavior
The third element has been added to headerState setting. The widget crashes when used with old settings.

##### Steps to reproduce the behavior
Set Rank widget on the canvas without reseting widget settings.

**Comment by kernc** [comment] 2016-11-07 13:59
Duplicate of https://github.com/biolab/orange3/issues/1707.

**Closed by kernc** 2016-11-07 13:59 UTC
