### ISSUE TITLE
Report crashes when Webkit/Webengine are missing

### ISSUE THREAD

**Issue by toop** [biolab/orange3#3661] opened 2019-03-07 01:10 UTC
##### Orange version

version：3.20.1

##### Actual behavior

![orange3error](https://user-images.githubusercontent.com/1625023/53924897-d39db900-40b8-11e9-99f6-eed840a5176f.png)

**Comment by ajdapretnar** [comment] 2019-03-07 08:32
Please describe the issue is more detail. I cannot reproduce.

**Comment by janezd** [comment] 2019-03-07 20:41
How did you install Orange? Apparently your PyQt includes neither WebKit nor WebView. Orange warns about this when opening (at least if open from terminal) and then replaces it with a mock. This however fails when Orange tries opening the report.

If I'm correct, you have not installed Orange using a binary installer -- please confirm. In this case, you will have to find a PyQt version that inclues WebKit or WebView. Does anybody here know more about this, on Windows?

This is a known problem. Orange should probably avoid showing a Python exception and instead show a kind message that report won't work due to missing libraries.

**Comment by toop** [comment] 2019-03-08 00:36
win10 64；python 3.6.7；pip 19.0.3
use pip to install，then install pyqt5

**Comment by janezd** [comment] 2019-03-08 09:38
The problem is rather that the "packaging" of PyQt that you used previously didn't have Webview/Webengine, while the version that you installed now has it. We can't influence that, but Orange should report this in a friendlier and more informative dialog.

So thanks for closing the issue, but I'm reopening so that we don't forget to fix it.

**Comment by janezd** [comment] 2019-03-29 15:04
The code that needs to be modified will be refactored when preparing a standalone canvas, so we will fix it later, unless @ales-erjavec doesn't already do so in #3527.

**Comment by ales-erjavec** [comment] 2019-07-08 07:40
Fixed in gh-3772

**Closed by ales-erjavec** 2019-07-08 07:40 UTC
