### ISSUE TITLE
Logistic regression not using all features

### ISSUE THREAD

**Issue by dvanderelst** [biolab/orange3#1800] opened 2016-12-03 03:08 UTC
![screenshot from 2016-12-02 22-10-38](https://cloud.githubusercontent.com/assets/18736256/20856416/2e6fc5e2-b8dc-11e6-949d-9bff09d1eea1.png)

##### Orange version

3.3.6

##### Expected behavior

When selecting n features and one discrete target variable (using the Select Columns Widget) the Logistic regression should return n coefficients.

##### Actual behavior

Instead of n coefficients, only n-1 are returned. No coefficient is returned for the feature listed last in the Select Columns widget.

##### Steps to reproduce the behavior

Add a select cloumns widget and route this to a logistic regression widget (see screenshot)

**Comment by lanzagar** [comment] 2016-12-05 13:22
I can't reproduce this using the latest version of Orange using documentation data sets.
Could you make sure you get expected results using e.g. the iris data set. And then check the values of Feature 4 in your data. Maybe it contains only unknown values and is removed for the modelling stage (or something similar).

**Comment by ajdapretnar** [comment] 2017-01-25 10:52
I also cannot reproduce. @dvanderelst did you manage to check with default data sets?

**Comment by ajdapretnar** [comment] 2017-02-20 10:44
@dvanderelst Could you please check if the problem persists on iris.tab as well?

**Comment by lanzagar** [comment] 2017-02-22 14:08
Not enough information to reproduce.
Closing, to be reopened if more info is available.

**Closed by lanzagar** 2017-02-22 14:08 UTC
