### ISSUE TITLE
The 'degree' parameter of SVC must be an int in the range [0, inf). Got 2.5 instead

### ISSUE THREAD

**Issue by 1324493354ZHOU** [biolab/orange3#6853] opened 2024-07-17 10:34 UTC
**What's wrong?**

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by 1324493354ZHOU** [comment] 2024-07-17 10:40
What's wrong?
InvalidParameterError: The 'degree' parameter of SVC must be an int in the range [0, inf). Got 2.5 instead.
How can we reproduce the problem?
Occurs when using SVM classification
What's your environment?
conda
Operating system:win10
Orange version:[Orange 3.37.0 for Windows]
How you installed Orange:Download and install from the official website

**Comment by PerryGogas** [comment] 2024-07-31 17:28
So what is the solution to this? I have the same problem...

**Comment by markotoplak** [comment] 2024-07-31 21:03
I confirm the bug. My scikit-learn (for reference) is 1.3.2.

The problem is not only that the parameter can be 2.5 as in the original error report - scikit-learn complains as soon as it is a float, even if it is 2.0.

**Comment by PerryGogas** [comment] 2024-07-31 21:49
> I confirm the bug. My scikit-learn (for reference) is 1.3.2.
> 
> The problem is not only that the parameter can be 2.5 as in the original error report - scikit-learn complains as soon as it is a float, even if it is 2.0.

Where is this degree parameter set?
I get: "The 'degree' parameter of SVC must be an int in the range [0, inf). Got 3.0 instead"

**Comment by markotoplak** [comment] 2024-08-01 07:26
It is an internal parameter ("d") only relevant to the "Polynomial" kernel, but it seems to be always passed and that check about argument type complains even if it is not used.

It is a bug that has to be fixed in code.

**Comment by PerryGogas** [comment] 2024-08-01 07:28
> It is an internal parameter ("d") only relevant to the "Polynomial" kernel, but it seems to be always passed and that check about argument type complains even if it is not used.
> 
> It is a bug that has to be fixed in code.

I see. It did not make sense in the linear SVM as it is the degree of the polynomial in the polynomial kernel... But still I get it in the linear SVM node...

**Comment by markotoplak** [comment] 2024-08-02 08:50
While fixing this bug I found a workaround for other types of SVMs. If you are using non-polynomial SVM (or polynomial with a default degree of 3), reset widget settings (Options -> Reset Widget Settings and then start a new workflow). The SVM widget will work correctly until you change the degree.

**Comment by PerryGogas** [comment] 2024-08-08 12:58
> While fixing this bug I found a workaround for other types of SVMs. If you are using non-polynomial SVM (or polynomial with a default degree of 3), reset widget settings (Options -> Reset Widget Settings and then start a new workflow). The SVM widget will work correctly until you change the degree.

Where exactly is this 3.0 degree set?

**Closed** 2024-08-23 07:50 UTC
Labels: bug

**Comment by PerryGogas** [comment] 2024-08-24 09:14
> While fixing this bug I found a workaround for other types of SVMs. If you are using non-polynomial SVM (or polynomial with a default degree of 3), reset widget settings (Options -> Reset Widget Settings and then start a new workflow). The SVM widget will work correctly until you change the degree.

Does not work for me. Still I cannot train any SVM models despite the fact that the problem is with the SVM-Polynomial.

**Comment by markotoplak** [comment] 2024-11-20 09:29
The version with the fix was finally packaged and released.

**Comment by PerryGogas** [comment] 2024-11-21 22:54
Oh! great! thanks!


PG


Professor *Periklis Gogas <https://econ.duth.gr/author/pgkogkas/>*
Economic Analysis and International Economics
Department of Economics
Democritus University of Thrace


Euro Area Business Cycle Network (ECB) - Fellow
<https://eabcn.org/person/periklis-gogas>
International Centre for Economic Analysis - Senior Research Fellow
<https://www.rcea.world/home>
The Rimini Centre for Economic Analysis - Fellow <http://rcea.org/>
The Society for Economic Measurement - Member <https://sem-society.org/>
Institute for Nonlinear Dynamical Inference (INDI) - Charter Fellow
<http://icemr.ru/institute-for-nonlinear-dynamical-inference/>




*Associate Editor *Open Economies Review
<https://www.springer.com/journal/11079>

The Journal of Economic Asymmetries
<https://www.sciencedirect.com/journal/the-journal-of-economic-asymmetries>

International Journal of Financial Studies
<https://www.mdpi.com/journal/ijfs>

Journal of Banking and Financial Technology
<https://www.springer.com/journal/42786>

(Nature) Humanities and Social Sciences Communications
<https://www.nature.com/palcomms/>
