### ISSUE TITLE
GEO Data Sets widget 

### ISSUE THREAD

**Issue by YuriB85** [biolab/orange3#4031] opened 2019-09-18 07:58 UTC
I am trying to access some GEO datasets through the GEO DataSets widget but I cannot find any of the data sets I am interested in. Is this widget supposed to be able to access all the  NCBI data sets or only a selected group? Many thanks.

**Comment by ajdapretnar** [comment] 2019-09-18 10:13
Closing as a duplicate of https://github.com/biolab/orange3-single-cell/issues/366.

**Closed by ajdapretnar** 2019-09-18 10:13 UTC
Labels: bug
