### ISSUE TITLE
Explain Model Widget from Explain Addon display the error np.int

### ISSUE THREAD

**Issue by bohdankornienko** [biolab/orange3#6490] opened 2023-06-23 14:59 UTC
**What's wrong?**
```
￼ An error occurred.
module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**How can we reproduce the problem?** 
[islr.zip](https://github.com/biolab/orange3/files/11849625/islr.zip)

1. Create Linear Regression model
2. Create "Explain Model" widget
3. Connect Data and model to Exlain widget
4. Get the error

**What's your environment?**

- Operating system: Windows 10
- Orange version: 3.35
- How you installed Orange: via installer (with miniconda installed automatically)

**Comment by markotoplak** [comment] 2023-07-03 11:01
Duplicate of biolab/orange3-explain#60

**Closed by markotoplak** 2023-07-03 11:01 UTC
Labels: bug report
