### ISSUE TITLE
Preprocess does not show entire interface when Sent automatically is on

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#3209] opened 2018-08-27 09:09 UTC
Use File -> Preprocess, and in File selected, say, Iris. Remove all preprocessors inPreprocess widget (if there are any). In Output, check Send Automatically. Then add Select Random Features.

![screen shot 2018-08-27 at 11 09 54](https://user-images.githubusercontent.com/726604/44651461-c1481180-a9e9-11e8-8a98-abb79b2fc49b.png)

Check if any other preprocessor behaves the same, that is, has the same bug. Following is a screenshot where the GUI is rendered correctly:

![screen shot 2018-08-27 at 11 06 37](https://user-images.githubusercontent.com/726604/44651498-dfae0d00-a9e9-11e8-9b88-e3d829f7ed28.png)

**Comment by ales-erjavec** [comment] 2018-08-28 07:13
Which version of PyQt5 are you using? Try downgrading it to 5.9.2 (`pip install PyQt5==5.9.2`)

**Comment by janezd** [comment] 2019-01-24 21:50
@BlazZupan, is this still relevant?

**Comment by ajdapretnar** [comment] 2019-02-01 12:44
Closing, since unable to reproduce. @BlazZupan Reopen if issue still persists.

**Closed by ajdapretnar** 2019-02-01 12:44 UTC
