### ISSUE TITLE
Widgets relocates when opening

### ISSUE THREAD

**Issue by MogensBLaursen** [biolab/orange3#3598] opened 2019-02-14 11:00 UTC
##### Expected behavior
Widget stays in place when opening it.

##### Actual behavior
Widget flips to the position of the cursor as the widget opens. This may be outside the actual canvas, which in turn adapts the the enlarged area. One then has to scroll the canvas to drag the widget back in place. On next opening, the problem reoccurs.

##### Steps to reproduce the behavior
(On Windows) Enable the mouse feature "Smart move", which positions the cursor  on the active GUI-control. In the Orange context, the control should be a control inside the widget form and not affecting controls in any way.  
This is also the remedy / workaround: Disable this mouse feature.
But it took some time to crack the problem.

**Comment by ajdapretnar** [comment] 2019-03-27 10:00
Duplicate of #3294.

**Closed by ajdapretnar** 2019-03-27 10:00 UTC

**Comment by markotoplak** [comment] 2019-03-27 10:20
@MogensBLaursen, thank you for tracing out the "Smart move" that causes this on Windows. We had no idea why it was happening there.

**Comment by ajdapretnar** [comment] 2019-03-27 10:24
Yes, @MogensBLaursen I was too quick to close this without thanking you. Nice job finding the issue! 👍
