### ISSUE TITLE
Concatenate does not work with Feature Constructor

### ISSUE THREAD

**Issue by lbtuda** [biolab/orange3#1943] opened 2017-01-24 00:03 UTC
##### Orange version
3.3.9

##### Expected behavior
Concatenate two tables, both with an via the feature constructor added feature (named the same)

##### Actual behavior
Combines the two tables but takes only consturcted feature values of the primary data. 
Additional datasconstructed feature field gets the value of the primary data constructed feature field

##### Steps to reproduce the behavior
Load a file with multiple dimensions (numerical features) run them parallel through multiple K-meas (with different k), after every k-means add a constructed feature (k, with the value of the k of k-means) to the Centroids.

Then combine the results into one data table.

##### Additional info (worksheets, data, screenshots, ...)

![image](https://cloud.githubusercontent.com/assets/15673873/22228315/a56cc9d4-e1d0-11e6-8e82-5354bea09694.png)

**Comment by ajdapretnar** [comment] 2017-01-25 10:43
I have a different problem. I get two columns instead of one, X1 (where all values are 1) and X1 (where all values are 2). Moreover, I split the data in half and then selected an intersection, which should be None, but I got a full data table with doubled attributes.

<img width="1311" alt="screen shot 2017-01-25 at 11 42 36" src="https://cloud.githubusercontent.com/assets/12524972/22287483/661f7ff0-e2f3-11e6-9c91-8435fb18a9a8.png">

**Comment by ales-erjavec** [comment] 2017-01-27 12:01
The behavior in the original issue is 'expected' (although confusing). To get the union of all columns in the input datasets, the "Primary Data" should not be connected to the widget (i.e. connect both Feature Constructors to the 'Additional Data' input).

The second issue is addressed in #1967

**Comment by ajdapretnar** [comment] 2017-01-27 12:26
Even when connecting both inputs as 'Additional Data', intersection doesn' recognize the two columns being the same and output only original data. As for union, I get both X1's in the table. I presume the issue is in the domain, as X1 from one input in not the same as X1 from the other.

<img width="1102" alt="screen shot 2017-01-27 at 13 18 35" src="https://cloud.githubusercontent.com/assets/12524972/22370894/27d7284a-e494-11e6-809b-b7a7f60e53e2.png">

**Comment by ales-erjavec** [comment] 2017-01-27 12:39
Yes. If the two X1 are constructed with a different Feature Constructor they will both be in the union an neither in the intersection.

**Comment by ajdapretnar** [comment] 2017-01-27 12:40
Is this the desired behaviour?

**Comment by ales-erjavec** [comment] 2017-01-27 12:50
Yes.

**Comment by ajdapretnar** [comment] 2017-02-20 08:53
Then I'm closing this.

**Closed by ajdapretnar** 2017-02-20 08:53 UTC
Labels: bug
