### ISSUE TITLE
Workflow size too small on Windows 10

### ISSUE THREAD

**Issue by oyvinrog** [biolab/orange3#3194] opened 2018-08-09 11:08 UTC
##### Orange version

3.15.0 running on Windows 10. I have never experienced this issue on previous versions of Orange

##### Expected behavior

Workflow window size should be as large as possible

##### Actual behavior

Workflow window size is really small

##### Additional info (worksheets, data, screenshots, ...)

![image](https://user-images.githubusercontent.com/16526012/43895352-50182490-9bd5-11e8-9eb9-6bc4d8cc8032.png)

**Comment by ajdapretnar** [comment] 2018-08-09 11:35
Duplicate of #3193.

**Closed by ajdapretnar** 2018-08-09 11:35 UTC
