### ISSUE TITLE
Scatter Plot: Show class density does not work

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#1986] opened 2017-02-03 07:00 UTC
##### Orange version
3.3.9 / 3.3.10

##### Expected behavior
Show class density in Scatter Plot should display density information for the class.

##### Actual behavior
Gray background is displayed instead.

##### Steps to reproduce the behavior
File (Iris) -> Scatter Plot, check on Show class density from Plot Properties

**Comment by kernc** [comment] 2017-02-03 07:31
Duplicate of https://github.com/biolab/orange3/issues/1948

**Closed by kernc** 2017-02-03 07:31 UTC
Labels: bug
