### ISSUE TITLE
Distributions: Plot doesn't update

### ISSUE THREAD

**Issue by pavlin-policar** [biolab/orange3#2460] opened 2017-07-09 13:38 UTC
##### Orange version
3.5.0.dev0+942877a

##### Expected behavior
Plot updates when checking "Show relative frequencies". Plot updates when changing "Show probabilities".

##### Actual behavior
The plot only updates on redraw (by changing any other option in the control area).

##### Steps to reproduce the behavior
1. Connect File to Distributions
2. Check "Show relative frequencies" (_plot doesn't change, but should_)
3. Change selection of "Show probabilities" (_plot doesn't change, but should_)

**Comment by ajdapretnar** [comment] 2017-07-10 06:51
Possible duplicate of #2420?

**Comment by pavlin-policar** [comment] 2017-07-10 06:55
Yes, pretty much, the only difference being that this also happens when checking "Show relative frequencies".

**Comment by ajdapretnar** [comment] 2017-09-08 08:08
Fixed in #2428.

**Closed by ajdapretnar** 2017-09-08 08:08 UTC
