### ISSUE TITLE
about web based version

### ISSUE THREAD

**Issue by toop** [biolab/orange3#4164] opened 2019-11-05 09:53 UTC
Orange3 need web based version，like samsung brightics，Brightics Studio is a web-based data analysis workflow tool for data scientists.
![brightics_sample](https://user-images.githubusercontent.com/1625023/68197411-369f7100-fff5-11e9-9c13-5e101387db42.png)

**Comment by ajdapretnar** [comment] 2019-11-05 10:05
Duplicate of https://github.com/biolab/orange3/issues/1419. See https://github.com/biolab/orange3/issues/1419#issuecomment-478494556 for details.

**Closed by ajdapretnar** 2019-11-05 10:05 UTC
Labels: suggestion
