### ISSUE TITLE
Segmentation Fault: right click on widget name

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5379] opened 2021-04-02 11:14 UTC
- [ ] **What's wrong?**

Segmentation Fault when clicking on the widget name.

- [ ] **How can we reproduce the problem?** 

Very precisely.
Open Orange.
Put File on the canvas.
Don't click anything else.
Right-click on widget name.

- [ ] **What's your environment?**

- Operating system: OSX Big Sur
- Orange version: 3.29.dev
- How you installed Orange: git (master)

**Comment by JakaKokosar** [comment] 2021-04-02 11:29
Using PyPI released versions of orange-widget-base and orange-canvas-core I was not able to reproduce this. It happened only after I installed it directly from the master branch.

**Comment by ales-erjavec** [comment] 2021-04-02 12:19
Probably introduced by: https://github.com/biolab/orange-canvas-core/pull/172

Is this on right click only or left also?

**Comment by JakaKokosar** [comment] 2021-04-02 12:38
It seems like only on right click

**Comment by ales-erjavec** [comment] 2021-04-02 13:14
Does https://github.com/biolab/orange-canvas-core/pull/185 fix it? I cannot duplicate it.

**Comment by ajdapretnar** [comment] 2021-04-02 13:16
I am on latest PyQt5. The widget has to be selected to replicate (widget name in blue).

**Comment by ales-erjavec** [comment] 2021-04-02 19:26
This is caused by [QTBUG-88309](https://bugreports.qt.io/browse/QTBUG-88309) present in Qt >=5.15.1 fixed in 6.0.0

**Closed** 2021-04-09 08:51 UTC
Labels: bug report
