### ISSUE TITLE
IndexErrror: list index out of range error, while I load any classifier

### ISSUE THREAD

**Issue by siraj2020** [biolab/orange3#4833] opened 2020-05-30 13:36 UTC
I am using windows 10 and have installed Orange v3.25, also I have installed Timeseries addons, But the problem is, when ever I try to load any classifier it give me IndexError: list  Index out of range 
![E1](https://user-images.githubusercontent.com/66170263/83329929-67464100-a28c-11ea-8677-e76fdf0f759c.jpg)

**Comment by ajdapretnar** [comment] 2020-06-01 07:21
Duplicate of #4805.

**Closed by ajdapretnar** 2020-06-01 07:21 UTC
Labels: bug report
