### ISSUE TITLE
DataLoad-valueError: could not convert string to float.

### ISSUE THREAD

**Issue by anilkodepaka** [biolab/orange3#1798] opened 2016-12-02 13:56 UTC
##### Orange version
3.3.8

##### Expected behavior

data file should load with the selected conversions (string to date and vice versa)

##### Actual behavior

Exception:
ValueError: could not convert string to float: '27.05.2015'
Module:
numpy.core.numeric:482
Widget Name:
File
Widget Module:
Orange.widgets.data.owfile:410
.
.
Stack Trace:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\Orange\widgets\data\owfile.py", line 410, in apply_domain_edit
    table = Table.from_numpy(domain, X, y, m, self.data.W)
  File "C:\Python34\lib\site-packages\Orange\data\table.py", line 440, in from_numpy
    X, Y, W = _check_arrays(X, Y, W, dtype='float64')
  File "C:\Python34\lib\site-packages\Orange\data\table.py", line 1461, in _check_arrays
    array = np.asarray(array, dtype=dtype)
  File "C:\Python34\lib\site-packages\numpy\core\numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: '27.05.2015'

##### Steps to reproduce the behavior

Data is present as a string in excel file, at the time of loading file, tried to update date column from string/meta to Datetime/feature.

**Comment by ajdapretnar** [comment] 2016-12-05 09:30
Datetime accepts data in ISO format only (e.g. 1990-01-31). However, the widget should not crash when encountering an unfamiliar format.

**Comment by ajdapretnar** [comment] 2017-01-11 07:44
@anilkodepaka Can you check whether the problem persists with the latest version?

**Comment by ajdapretnar** [comment] 2017-01-11 08:02
Yeah, it does. Happened to me as well...

**Comment by ajdapretnar** [comment] 2017-01-25 11:09
https://sentry.io/biolab/orange3/issues/196743724/

**Comment by anilkodepaka** [comment] 2017-01-25 12:16
hei..what is this link about?

**Comment by ajdapretnar** [comment] 2017-01-25 12:17
The corresponding issue on Sentry. Just to keep track of the resolved / unresolved issues.

**Comment by ajdapretnar** [comment] 2017-01-25 12:29
Duplicate of #1520.

**Closed** 2017-04-21 10:33 UTC
Labels: bug
