### ISSUE TITLE
Compare labeled data in Line Chart (time series)

### ISSUE THREAD

**Issue by gslopez** [biolab/orange3#3332] opened 2018-10-25 20:32 UTC
Hi, i have the following problem.

My database looks like this:

| Name  | Date  |  Value  |
|---|---|---|
|  Region A | 01/01/2011  | 1  |
|  Region A | 02/01/2011  | 5  |
|  Region A | 03/01/2011  | 10  |
|  Region B | 01/01/2011  | 15  |
|  Region B | 02/01/2011  | 50  |
|  Region B | 03/01/2011  | 2  |

I want to compare Region A and Region B charts, but Orange shows all data grouped in one single chart.
Is it possible ?

Thank you !

**Comment by kernc** [comment] 2018-10-26 02:38
Duplicate of https://github.com/biolab/orange3-timeseries/issues/60.

**Closed by kernc** 2018-10-26 02:38 UTC
