### ISSUE TITLE
Cannot open on Mac os Big Sur (Mac os 11.0)

### ISSUE THREAD

**Issue by Richard195666** [biolab/orange3#4878] opened 2020-07-02 18:30 UTC
**Bug reports that do not sufficiently describe a bug are not helpful and will most likely be ignored.**

- [ ] **A clear and concise description.** "*I'm getting an error when I open a tree viewer*" is far from enough (what kind of error? what kind of data you give it?). "*I'm getting an error*" is even worse.

- [ ] **How to reproduce the problem.** Upload a zip with a workflow and data, or describe the steps (open this widget, click there, then add this ...)

- [x] **Which version of Orange are you using? How did you install it?**
0.9 I download from website and installed it.
- [x] **What is your operating system?**
Mac OS big Sur(11.0)

**Comment by Richard195666** [comment] 2020-07-03 16:22
Quasar cannot open on Mac os Big Sur, it won't come out anything with high cpu use.

**Comment by Richard195666** [comment] 2020-07-04 20:37
I tried to upgrade my Xcode to beta version as well to fix itl but Quasar still didn't work.

**Comment by markotoplak** [comment] 2020-07-04 21:27
@Richard195666, I see you are working with Quasar. We try to keep installers for Orange and Quasar equivalents, but could you please also try running vanilla Orange (download dmg from https://orange.biolab.si/download/#macos)?

I do not have any Big Sur installs available to test currently. Do you get any error messages?

**Comment by Richard195666** [comment] 2020-07-04 21:53
> @Richard195666, I see you are working with Quasar. We try to keep installers for Orange and Quasar equivalents, but could you please also try running vanilla Orange (download dmg from https://orange.biolab.si/download/#macos)?
> 
> I do not have any Big Sur installs available to test currently. Do you get any error messages?

Hi, I just tried Orange as you said, the same issue happened again. This is error report, hope it is useful.
![image](https://user-images.githubusercontent.com/22250547/86521491-30de8180-be49-11ea-9d8a-fdadc86f8d19.png)

**Comment by Richard195666** [comment] 2020-07-04 23:33
Error Report.txt

**Comment by Richard195666** [comment] 2020-07-04 23:35
[Error Report.txt](https://github.com/biolab/orange3/files/4874176/Error.Report.txt)
This is full error report, hope it is useful.

**Comment by Richard195666** [comment] 2020-07-04 23:36
> @Richard195666, I see you are working with Quasar. We try to keep installers for Orange and Quasar equivalents, but could you please also try running vanilla Orange (download dmg from https://orange.biolab.si/download/#macos)?
> 
> I do not have any Big Sur installs available to test currently. Do you get any error messages?

https://github.com/biolab/orange3/files/4874176/Error.Report.txt
This is full error report, hope it is useful.

**Comment by markotoplak** [comment] 2020-07-05 07:24
@Richard195666, thank you. There seems to be a problem with some UI library that Orange uses.

To update that library to the newest version, could you try running `/Applications/Orange3.app/Contents/MacOS/pip install pyqt5==5.15 pyqtwebengine==5.15`? Or, for Quasar, `/Applications/Quasar.app/Contents/MacOS/pip install pyqt5==5.15 pyqtwebengine==5.15`.

If this does not solve your problem, then we will have to wait for new releases.

**Comment by Richard195666** [comment] 2020-07-07 13:35
> @Richard195666, thank you. There seems to be a problem with some UI library that Orange uses.
> 
> To update that library to the newest version, could you try running `/Applications/Orange3.app/Contents/MacOS/pip install pyqt5==5.15 pyqtwebengine==5.15`? Or, for Quasar, `/Applications/Quasar.app/Contents/MacOS/pip install pyqt5==5.15 pyqtwebengine==5.15`.
> 
> If this does not solve your problem, then we will have to wait for new releases.

Hi
Thanks for your reply. I already tried as you said, but sadly still not working.

**Comment by ales-erjavec** [comment] 2020-07-07 14:14
Can you try starting orange by running 
```bash
/Applications/Orange3.app/Contents/MacOS/Orange --no-splash
```

**Comment by Richard195666** [comment] 2020-07-07 14:25
> Can you try starting orange by running
> 
> ```shell
> /Applications/Orange3.app/Contents/MacOS/Orange --no-splash
> ```

Hi, thanks for your reply. I tried it but there is nothing coming out but high CPU using by Orange.

**Comment by Richard195666** [comment] 2020-07-11 00:02
[Error report on Mac os Big sur beta 2.txt](https://github.com/biolab/orange3/files/4905947/Error.report.on.Mac.os.Big.sur.beta.2.txt)
Since this bug still not solved yet and mac os big sur beta2 is released, I updated to beta 2 to try can it works. Unfortunately still cannot open. This is the full error report from beta 2. Thanks.

**Comment by ales-erjavec** [comment] 2020-07-16 14:18
Can you please also try:

* A) Run
    ```
    plutil -insert NSRequiresAquaSystemAppearance -bool YES /Applications/Orange3.app/Contents/Frameworks/Python.framework/Resources/Python.app/Contents/Info.plist
    ```
    and then try opening orange again

* B) Run:
    ```bash
    /Applications/Orange3.app/Contents/MacOS/pip install pyqt5-sip==4.19.19 pyqt5==5.12.1 pyqtwebengine==5.12.1
    ```
    and then try opening orange again

**Comment by Richard195666** [comment] 2020-07-16 18:45
> Can you please also try:
> 
> * A) Run
>   ```
>   plutil -insert NSRequiresAquaSystemAppearance -bool YES /Applications/Orange3.app/Contents/Frameworks/Python.framework/Resources/Python.app/Contents/Info.plist
>   ```
>   
>   
>   and then try opening orange again
> * B) Run:
>   ```shell
>   /Applications/Orange3.app/Contents/MacOS/pip install pyqt5-sip==4.19.19 pyqt5==5.12.1 pyqtwebengine==5.12.1
>   ```
>   
>   
>   and then try opening orange again

Hi
Thanks very much! You are amazing! It's still not working after I tried A. However, it works now after I tried B as well! 
Thanks again!
Best wishes

**Comment by Richard195666** [comment] 2020-07-16 18:47
> Can you please also try:
> 
> * A) Run
>   ```
>   plutil -insert NSRequiresAquaSystemAppearance -bool YES /Applications/Orange3.app/Contents/Frameworks/Python.framework/Resources/Python.app/Contents/Info.plist
>   ```
>   
>   
>   and then try opening orange again
> * B) Run:
>   ```shell
>   /Applications/Orange3.app/Contents/MacOS/pip install pyqt5-sip==4.19.19 pyqt5==5.12.1 pyqtwebengine==5.12.1
>   ```
>   
>   
>   and then try opening orange again

Quasar can be fixed by using the same method as well. 
Thanks!

**Comment by janezd** [comment] 2020-07-31 08:38
@ales-erjavec, @markotoplak, do we need to do something, or is it a PyQt problem and we wait (and close the issue)?

**Comment by ales-erjavec** [comment] 2020-08-05 08:01
@Richard195666 Can you try this https://dev.azure.com/ales-erjavec/_apis/resources/Containers/9021780/macOS%20dmg%20installer?itemPath=macOS%20dmg%20installer%2Forange3%2Fdist%2FOrange3-3.27.0.dev0%2B6193d32-Python3.7.6.dmg

Note that it is unsigned so you will have to right click on the application icon and click open (or whichever way is the current gatekepper bypas on big sur).

@janezd  I think we should keep it open.

**Comment by maciejsiega** [comment] 2020-10-15 08:10
Hello guys - latest beta and I am still unabled to run PyQt5 apps :/ I even updated yesterday Python to 3.9 version however, no change - the language itself works as I have tried to print "TEST" value every some time in code and it seems to be executable but windows don't want to show up. Same code compiled on Windows work fine

**Comment by educbraga** [comment] 2020-11-14 15:45
Hi! I think sharing this could help solve the problem.
I was with the same issue here on the Big Sur public release (11.0.1).
After doing A, the same error occurred, and after doing B I fixed the issue.

> Can you please also try:
> 
> * A) Run
>   ```
>   plutil -insert NSRequiresAquaSystemAppearance -bool YES /Applications/Orange3.app/Contents/Frameworks/Python.framework/Resources/Python.app/Contents/Info.plist
>   ```
>   
>   
>   and then try opening orange again
> * B) Run:
>   ```shell
>   /Applications/Orange3.app/Contents/MacOS/pip install pyqt5-sip==4.19.19 pyqt5==5.12.1 pyqtwebengine==5.12.1
>   ```
>   
>   
>   and then try opening orange again

**Comment by rowlandpettit** [comment] 2020-11-16 00:59
> > Can you please also try:
> > 
> > * A) Run
> >   ```
> >   plutil -insert NSRequiresAquaSystemAppearance -bool YES /Applications/Orange3.app/Contents/Frameworks/Python.framework/Resources/Python.app/Contents/Info.plist
> >   ```
> >   
> >   
> >   and then try opening orange again
> > * B) Run:
> >   ```shell
> >   /Applications/Orange3.app/Contents/MacOS/pip install pyqt5-sip==4.19.19 pyqt5==5.12.1 pyqtwebengine==5.12.1
> >   ```
> >   
> >   
> >   and then try opening orange again
> 
> Quasar can be fixed by using the same method as well.
> Thanks!

/Applications/Orange3.app/Contents/MacOS/pip install pyqt5-sip==4.19.19 pyqt5==5.12.1 pyqtwebengine==5.12.1

Worked for me too!

**Comment by markotoplak** [comment] 2020-11-16 09:37
I have tried building a new release with the new release of PyQt 5.12.3, which was released this Saturday: https://dev.azure.com/ales-erjavec/orange3-installers/_build/results?buildId=72&view=artifacts&type=publishedArtifacts . However, @JakaKokosar reports that still does not work. But when he replaced PyQt in app with 5.12.2, it started working again. Then, he tried reinstalling 5.12.3. It failed again: it got stuck at `INFO:__main__:Running widget discovery process.`.

So it seems that PyQt5 5.12.2 works in the app and 5.12.3 is not. But @JakaKokosar also reports that 5.12.3 works fine in his dev environment. @ales-erjavec, any ideas why that would happen?

I also noticed some traffic on PyQt mailing list about Big Sur (in)compatibility, but I am not sure how related these are: https://www.riverbankcomputing.com/pipermail/pyqt/2020-November/043391.html

**Comment by ales-erjavec** [comment] 2020-11-16 11:16
Can you please test this build: https://dev.azure.com/ales-erjavec/orange3-installers/_build/results?buildId=74&view=artifacts&type=publishedArtifacts

**Comment by markotoplak** [comment] 2020-11-16 12:34
@ales-erjavec, that worked for @JakaKokosar. It there anything else to do or can I just take that dmg, sign it (and notarize it) and put it on download page?

**Comment by ales-erjavec** [comment] 2020-11-16 12:50
No. Pin pyqt5 and pyqtwebengine to 5.12.1 in the build instead.

**Comment by markotoplak** [comment] 2020-11-16 17:36
A new MacOS package that seems to work on Big Sur is now available at https://orange.biolab.si/download

**Comment by gerardojuan** [comment] 2020-11-16 20:48
> A new MacOS package that seems to work on Big Sur is now available at https://orange.biolab.si/download

Yes, confirmed, it works for me. (I had the same issue as above before.)

**Closed** 2020-11-24 10:26 UTC
Labels: bug report
