### ISSUE TITLE
Logistic Regression for Image Classification is not producing a score

### ISSUE THREAD

**Issue by mshmsh1234** [biolab/orange3#4840] opened 2020-06-03 18:13 UTC
**Describe the bug**

I have a set of images with two separate classifications. I am trying to run a logistic regression model on this data set (following the exact steps in this Orange video https://www.youtube.com/watch?v=lvgx62a8XQk&list=PLmNPvQr9Tf-ZSDLwOzxpvY-HrE0yv-8Fy&index=15).

**Here**, provide a clear and concise description of what the bug is.

When I attach the Logistic Regression modules to the left side of the Test Score module, the same way that the user does in the video, the line connecting the two modules becomes dotted rather than solid. I am not sure what a dotted line in this context means and could not find this information anywhere - please let me know. Additionally, after I connect the two and click the Test Score module, I do not see any results. The table is completely blank. The Logistic Regression model seems to not be running, but I am unable to pinpoint the issue. Again, I followed the exact steps in that video.

**To Reproduce**

Follow that video.

**Orange version:**
Orange - About - 3.25.0

**Expected behavior**
I expect to receive AUC, Precision, Recall, etc the same way the woman in the tutorial did.

**Screenshots**
I'm not sure how to attach screenshots but I can attach one of the dotted line if that is helpful

**Operating system:**
Windows 10

**Comment by PrimozGodec** [comment] 2020-06-03 19:45
Hi, thank you for submitting the issue. The behavior you are describing is strange and I cannot reproduce it. The dotted line usually means that nothing is transferred through the connection. It mostly happens with widgets that send data (when they cannot send anything). 

So if I understand correctly the line between Logistic regression and Test and Score is dotted? If so please double click on this line and make sure that Learner output of Logistic regression is connected to Learner input on the test and score widget. 
If an error is still present, please sends the saved workflow from Orange here. It would be an easier way for us to see what is wrong. In Orange save workflow with Ctrl+S and just drag and drop a file here (in the comment field).

**Comment by mshmsh1234** [comment] 2020-06-03 20:43
Yes, the error is still present. The two Learners are connected.

Are you sure that I can connect the .ows file? When I try to attach file I can't access the .ows

**Comment by mshmsh1234** [comment] 2020-06-03 20:45
<img width="605" alt="embed" src="https://user-images.githubusercontent.com/57454311/83687310-983eb280-a5b9-11ea-813f-dbf67941d1d9.PNG">

This is a photo of the dotted lines

**Comment by PrimozGodec** [comment] 2020-06-04 12:52
It looks strange. I cannot reproduce the error. Sorry, I just realize that you cannot attach the .ows file but it is possible to zip it and then attach. Can you attach it please as a zip?

**Comment by mshmsh1234** [comment] 2020-06-04 12:54
[jun2.zip](https://github.com/biolab/orange3/files/4730114/jun2.zip)

Thank you, I have attached the zip file! I tried uninstalling and reinstalling Orange to see if that would remove the bug, but it did not help.

**Comment by PrimozGodec** [comment] 2020-06-08 15:31
I tried your workflow but still cannot reproduce the issue. I am assuming that it can be connected to this issue https://github.com/biolab/orange3/issues/4844.

Can you try the following:
1. Go to the folder where Orange is installed on your computer. By default it is C://Users/<your user name>/AppData/Local/Orange.
2. Open `Orange command prompt`
3. Upgrade the version of Orange with typing `conda install orange3=3.25.1` in the command prompt
4. Open the workflow again and try if it works now.

**Comment by mshmsh1234** [comment] 2020-06-08 17:35
Is it possible to update Orange with a download from the website? I did not install it with conda

**Comment by PrimozGodec** [comment] 2020-06-08 17:49
We released version 3.25.1 but didn't make a new installer since we assumed it will not be an issue (problematic package si packed together with Orange installer), so it is currently not possible to upgrade with from the website.

When using installer it actually installs Orange with conda (behind is conda environment). So if you open Orange command prompt as written in instructions above you will be able to upgrade with conda.

Anyway, we will provide a new installer soon.

**Comment by mshmsh1234** [comment] 2020-06-08 17:52
I have not been able to upgrade Orange with the prompt above because I installed via download - just commenting this as FYI for anyone in the same boat. It says that orange cannot be found.

I will do a Conda install first so orange can be found and then upgrade.

**Comment by mshmsh1234** [comment] 2020-06-08 17:56
(base) C:\Users\myname>conda install orange3=3.25.1
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

^While Orange does say that it updated to 3.25.1 now, in the app (after restarting) it still says 3.25.0.

**Comment by markotoplak** [comment] 2020-06-08 21:04
@mshmsh1234, you need to do it in Orange's conda environment. The easiest way to get there is to open "Orange Command Prompt".

**Comment by PrimozGodec** [comment] 2020-06-11 10:31
@mshmsh1234 have you tried to upgrade Orange through Orange Command Prompt?

**Comment by PrimozGodec** [comment] 2020-06-16 10:16
@mshmsh1234 the new version of Orange is out. Can you try to download the new installer from orange.biolab.si and let us know if the error persists.

**Comment by PrimozGodec** [comment] 2020-06-18 13:43
I will close this issue for now. Feel free to reopen it if the error still persists.

**Closed by PrimozGodec** 2020-06-18 13:43 UTC
Labels: bug report
