### ISSUE TITLE
When i open orange 3 through anaconda it shows me black screen.....Plz tell solution

### ISSUE THREAD

**Issue by Aditya222002** [biolab/orange3#4710] opened 2020-04-30 06:53 UTC
##### Orange version

3.25.0

##### Expected behavior
It should show me the orange canvas

##### Actual behavior
It showed me black screen and nothing else

##### Steps to reproduce the behavior
Simply click on orange 3 icon

##### Additional info (worksheets, data, screenshots, ...)

[<!--](url
![image](https://user-images.githubusercontent.com/64554000/80680345-34b5f680-8adc-11ea-9a26-61e3a3ca01c5.png)o-
)

**Comment by ales-erjavec** [comment] 2020-05-08 09:28
Duplicate of gh-4714

**Closed by ales-erjavec** 2020-05-08 09:28 UTC
