### ISSUE TITLE
Missing widget in Classification Tree tutorial

### ISSUE THREAD

**Issue by ysmartin** [biolab/orange3#1852] opened 2017-01-03 14:54 UTC
##### Orange version

3.3.9

##### Expected behavior
The Classification Tree example workflow is loaded without problem.

##### Actual behavior
When you attempt to open the Classification Tree workflow, the Tree Viewer widget is not loaded, and an warning pops up with the following error
> Warning. Errors occurred while loading the workflow. There were problems loading some of the widgets/links in the workflow. Show Details...

> `UnknownWidgetDefinition('Orange.widgets.classify.owclassificationtreegraph.OWClassificationTreeGraph',)`

##### Steps to reproduce the behavior
From Welcome Screen, select Example Workflows, select Classification Tree (4th workflow) and open it. The thumbnail also shows that one widget is missing.

**Comment by kernc** [comment] 2017-01-03 16:30
Thanks. Duplicate of https://github.com/biolab/orange3/issues/1820, fixed in https://github.com/biolab/orange3/pull/1804.

**Closed by kernc** 2017-01-03 16:30 UTC
