### ISSUE TITLE
Changing colours in Scatter Plot from table does not work

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4032] opened 2019-09-18 10:00 UTC
When setting colours in Scatter Plot using data from Table the colour in scatter plot does not change.

**To Reproduce**

![Screenshot from 2019-09-18 12-01-52](https://user-images.githubusercontent.com/47607471/65138963-219e5c80-da0c-11e9-87f6-51a32228e9ff.png)

For example: gbfA_avg is plotted (selected as attribute in Table) and colour is set to red in Colour widget, but this is not reproduced in Scatter Plot.

**Orange version:**
3.24
**Operating system:**
Ubuntu

**Comment by janezd** [comment] 2019-09-18 10:15
Not a duplicate, yet a close relative of #3944. `Domain.__hash__` relies on [`Variable.__hash__`](https://github.com/biolab/orange3/blob/master/Orange/data/variable.py#L367), which is just ordinary hash (based on instance id) and does not reflect changes of a variable instance.

There's no point in fixing this now because in #3925 (assuming it will be merged), [`Variable.__hash__`](https://github.com/biolab/orange3/pull/3925/files#diff-8fc32ad6a8ac706482fe82637339979aR346) sums the hash of name, type and `compute_value`. We should add `colors`, and -- @Hrovatin thanks for reporting this and reminding us! -- `DiscreteVariable.__hash__` must also include `values` for `DiscreteVariable` otherwise #3944 will reappear.

**Comment by janezd** [comment] 2019-09-22 13:01
I can no longer reproduce this after we removed `Variable.make` and after fixes in #4041.

@Hrovatin, apologies for wasting your time with dysfunctional Color widget on Friday. Can you try with #4041 (when you're back to work)?

@VesnaT, I don't know what fixed it -- and I don't like this. The Color widget now constructs a new `Variable` on every change, but this `Variable` should be considered equal to the previous because `color` is not (and must not be) included in `__hash__` and `__eq__`. If plot update is nevertheless triggered, it may be prudent to check whether there are any situations in which it is triggered although it shouldn't be. Please check it when/if you have time.

**Comment by VesnaT** [comment] 2019-09-23 08:37
Nothing fixed it - it was never an issue. Even though the data does not change (i. e. `self._invalidated = False`), the points properties are still updated (check `handleNewSignals()` in `OWDataProjectionWidget`).

The problem this issue addresses is changing a color for a variable with more than 10 values. The variable's values are then shown as 10 most common values plus `Other` (with a different color palette). Replacing the palette covers up the color change.

**Comment by VesnaT** [comment] 2019-09-23 09:18
Speaking of `Variable`'s `__hash__` and `__eq__`: Shouldn't they consider `self.attributes` somehow? I know dictionary is not hashable, but how can two variables with different attributes be equal.

**Comment by janezd** [comment] 2019-09-23 09:55
So this issue can be closed?

As for `__hash__` and `attributes`: it boils down to definition of equality. Two discrete variables can now be equal even though they have different `values`. What matters is name, type and `compute_value`. I was confused on Friday when I said we have to check other things, too. This should be a good definition in general, though in some places we'll need to check for "deeper" equality.

**Closed** 2019-10-03 11:27 UTC
Labels: bug
