### ISSUE TITLE
Pivot table does not show the expected count and value

### ISSUE THREAD

**Issue by gengyabc** [biolab/orange3#5180] opened 2021-01-14 07:27 UTC
- [x] **What's wrong?**
The behavior of the pivot table is different from the doc. I am using the last code from the repo, 3.28.

this is what I see in my Orange:
![image](https://user-images.githubusercontent.com/12781437/104557704-a343e000-567c-11eb-8fad-539978accbc3.png)

and this is what shown in the doc:
![](https://orangedatamining.com/widget-catalog/data/images/Pivot-discrete.png)

You see, the "count" and "majority" are both wrong. 

Or am I missing something here?

**Comment by lanzagar** [comment] 2021-01-22 14:16
I am reopening this, because it was fixed only for categorical variables, but the issue is still relevant for time variables.
To reproduce, open Cyber security breaches with the Datasets widget, and in Pivot select rows/columns/values: Type.../US State/Date_Posted...  and e.g. Median aggregation - instead of median dates the widget shows floats (seconds since epoch).

**Closed** 2021-01-29 08:41 UTC
Labels: bug report
