### ISSUE TITLE
Release Orange 3.24.1 incompatible to 3.25.0 leaves workflow in a mess.

### ISSUE THREAD

**Issue by WolframRinke** [biolab/orange3#4771] opened 2020-05-13 18:45 UTC
**Describe the bug**
I have a complex workflow setup with Orange release 3.24 after I upgraded to 3.25.0 the workflow did not work anymore. What has gone wrong?

**Here**, provide a clear and concise description of what the bug is.

will work on that.

**To Reproduce**

**Orange version:**
Orange - About - 3.24.1 incompatible with 3.25.0.

**Expected behavior**

**Screenshots**

**Operating system:**
OSX latest version 10.15.4 Catalina

**Additional context**
I had to switch back to Version 3.24.1

**Comment by janezd** [comment] 2020-05-13 20:41
You should describe this in more detail. We are of course testing backward compability, so if we could answer such a general question, we would already fix it...

**Comment by WolframRinke** [comment] 2020-05-14 16:30
This are the error messages I receive when loading my sheet from version 3.24.1. Below is the output from the log-window. It looks like there are several index-out-of-bounds bugs.

/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangewidget/widget.py:979: UserWarning: Storing variables as strings in settings is deprecated.
Support for this will be dropped in Orange 3.26.
Change _selected_item to store an instance of `Variable`.
  self.settingsHandler.open_context(self, *a)
/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/widgets/data/oweditdomain.py:1859: UserWarning: Storing variables as strings in settings is deprecated.
Support for this will be dropped in Orange 3.26.
Change _selected_item to store an instance of `Variable`.
  self.openContext(self.data)
/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangewidget/widget.py:979: UserWarning: Storing variables as strings in settings is deprecated.
Support for this will be dropped in Orange 3.26.
Change domain_role_hints to store an instance of `Variable`.
  self.settingsHandler.open_context(self, *a)
/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/widgets/data/owselectcolumns.py:310: UserWarning: Storing variables as strings in settings is deprecated.
Support for this will be dropped in Orange 3.26.
Change domain_role_hints to store an instance of `Variable`.
  self.openContext(data)
/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/statistics/util.py:355: RuntimeWarning: All-NaN slice encountered
  np.nanmin(X, axis=0),
/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/statistics/util.py:356: RuntimeWarning: All-NaN slice encountered
  np.nanmax(X, axis=0),
/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/statistics/util.py:357: RuntimeWarning: Mean of empty slice
  np.nanmean(X, axis=0) if not weighted else weighted_mean(),
/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/widgets/settings.py:130: UserWarning: Storing variables as strings in settings is deprecated.
Support for this will be dropped in Orange 3.26.
Change selection to store an instance of `Variable`.
  super().open_context(widget, domain, *self.encode_domain(domain))
/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangewidget/widget.py:979: UserWarning: Storing variables as strings in settings is deprecated.
Support for this will be dropped in Orange 3.26.
Change domain_role_hints to store an instance of `Variable`.
  self.settingsHandler.open_context(self, *a)
/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/widgets/data/owselectcolumns.py:310: UserWarning: Storing variables as strings in settings is deprecated.
Support for this will be dropped in Orange 3.26.
Change domain_role_hints to store an instance of `Variable`.
  self.openContext(data)
---------------------------- IndexError Exception -----------------------------
Traceback (most recent call last):
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/widgets/data/owfeaturestatistics.py", line 822, in on_select
    self.commit()
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangewidget/gui.py", line 1586, in unconditional_commit
    do_commit()
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangewidget/gui.py", line 1594, in do_commit
    commit()
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/widgets/data/owfeaturestatistics.py", line 840, in commit
    labels, data = self.model.get_statistics_matrix(variables, return_labels=True)
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/widgets/data/owfeaturestatistics.py", line 294, in get_statistics_matrix
    self._center[indices], self._dispersion[indices],
IndexError: index 23 is out of bounds for axis 0 with size 0
-------------------------------------------------------------------------------
---------------------------- IndexError Exception -----------------------------
Traceback (most recent call last):
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/scheme/signalmanager.py", line 936, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/scheme/signalmanager.py", line 974, in __process_next_helper
    self.process_node(selected_node)
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/scheme/signalmanager.py", line 605, in process_node
    self.send_to_node(node, signals_in)
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
    handler(*args)
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/widgets/data/owfeaturestatistics.py", line 783, in set_data
    self.commit()
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangewidget/gui.py", line 1586, in unconditional_commit
    do_commit()
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangewidget/gui.py", line 1594, in do_commit
    commit()
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/widgets/data/owfeaturestatistics.py", line 840, in commit
    labels, data = self.model.get_statistics_matrix(variables, return_labels=True)
  File "/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/widgets/data/owfeaturestatistics.py", line 294, in get_statistics_matrix
    self._center[indices], self._dispersion[indices],
IndexError: index 23 is out of bounds for axis 0 with size 0
-------------------------------------------------------------------------------
/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/statistics/util.py:389: RuntimeWarning: All-NaN slice encountered
  return func(x, axis=axis)
/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/statistics/util.py:435: RuntimeWarning: Degrees of freedom <= 0 for slice.
  return dense_func(x, axis=axis)
/Applications/Orange3.25.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/statistics/util.py:458: RuntimeWarning: Mean of empty slice
  means = np.nanmean(x, axis=axis)

**Comment by janezd** [comment] 2020-05-14 17:06
These errors (there are two, in the same place) look a lot like a duplicate of #4683 and should be fixed by #4741.

Orange 3.25 did not significantly change Feature statistics. I wouldn't know why this error (if this is indeed the only error) occur in 3.25 and not 3.24.

In what way is the workflow a mess? Missing widgets, channels or did they have wrong settings and data? With the log you sent, I would expect that the feature statistics widget didn't output any data, so there was nothing in the widgets that followed. Was this the case?

It would help if you could upload your workflow and any data files, if it is not confidential.

**Closed** 2020-05-21 07:34 UTC
Labels: bug report
