### ISSUE TITLE
Error "neural Network (error)"

### ISSUE THREAD

**Issue by uwolzenburg** [biolab/orange3#4108] opened 2019-10-17 09:26 UTC
##### Orange version
3.23.1

##### Expected behavior
I had an working Orange3 Workflow to cluster different types of images which was loaded in according to the – btw very usefull – youtube tutorials. They where used to describe basic AI and ML patterns to our project-partners.

##### Actual behavior
Since yesterday, I cant execute the whole workflow and getting an error using the prediction module. The only information I get from the system is "Neural Network (error)" and "domain transformation produced no defined values" – I tried to figure out whats wrong, but the concept I use is similar to all of the examples I found.

Please help, I don't know what to do know, we need those examples for our science-project.

##### Steps to reproduce the behavior
see attached screenshot

##### Additional info (worksheets, data, screenshots, ...)
![Bildschirmfoto 2019-10-17 um 11 24 49](https://user-images.githubusercontent.com/42774052/66996272-bca05a00-f0d0-11e9-911a-4b588c28ac2f.png)

thanks in advance

uli

**Comment by ajdapretnar** [comment] 2019-10-17 09:32
Is there any change you might share the workflow with us? Or, even better, reproduce this on some general data set and send the workflow?

**Comment by ajdapretnar** [comment] 2019-10-17 09:33
Also, what happens if you build an identical workflow from scratch?

**Comment by uwolzenburg** [comment] 2019-10-17 13:49
First of all, surely, there is no secret data in the set, so I will upload it here, maybe it's only a dump mistake I made.

But: I'm able to reproduce this error in a new workflow by rebuilding it – even on a complete different 2nd computer. 

thanks in advance
uli


[problem.zip](https://github.com/biolab/orange3/files/3739628/problem.zip)

**Comment by ajdapretnar** [comment] 2019-10-17 14:37
The workflow you have attached has no Neural Network widget. Is this on purpose?

Also, you probably didn't mean to close the issue?

**Comment by PrimozGodec** [comment] 2019-10-17 15:40
I also cannot reproduce the error. Can you also share what settings did you used in the neural network widget?

@ajdapretnar workflow does not load train data since the directory had a different name at uwolzenburg's computer and the widget cannot find them under this name. Anyway, I agree that it is an error in the case when no matching directory is found no data should be selected.

**Comment by uwolzenburg** [comment] 2019-10-18 07:05
Hi there, first of all, thanks for your answers, you're right, I accidentally dropped out the neural network, but nevertheless I got the sam Error by using the logistic regression module. 
For better understanding I added a screenshot of all of the error information I could get, or is there a log function anywhere? 

Thanks in advance

uli

![Bildschirmfoto 2019-10-18 um 09 03 38](https://user-images.githubusercontent.com/42774052/67072891-2dee1480-f186-11e9-83e7-37f2ddf8d2a3.png)

**Comment by ajdapretnar** [comment] 2019-10-18 10:40
I am sorry, I have no idea how to help you. I cannot reproduce this in any way.

In essence, seems like your train and test data don't match correctly. That is what the error means. The columns in the two data sets are not the same.

One thing I have noticed here: the above screenshot shows train, not test data used in Predictions... Is this on purpose?

**Comment by PrimozGodec** [comment] 2019-10-18 12:14
We succeded to reproduce your error. The bug you are describing is already fixed #3925, but it is not part of the latest release (so you do not have that update). 
The fix will be released soon but if you want to get rid of the error you can currently use an older version of Orange https://download.biolab.si/download/files/Orange3-3.22.0.dmg

**Closed** 2019-10-18 12:16 UTC
