### ISSUE TITLE
Table.concatenate(): Concatenating sparse and dense tables

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4836] opened 2020-06-01 09:45 UTC
**Describe the bug**

`Table.concatenate()` now pretends to be able to concatenate sparse tables with dense, but after concatenating, the output seems to fail elsewhere.

**To Reproduce**

Corpus - Bag of Words - Concatenate. (sparse)
Corpus - Concatenate. (dense)
Add Data Table after Concatenate.

**Orange version:**
3.26.0.dev

**Expected behavior**
All dense tables are transformed to sparse matrix and concatenated.

**Comment by janezd** [comment] 2020-06-01 16:22
> All dense tables are transformed to sparse matrix and concatenated.

Or the opposite? If a small sparse table is attached to a large dense one, I would hope to get a dense table.

Or should `concatenate` have a parameter whose value can be `Dense`, `Sparse`, and `Auto`, which would be used in the mixed case, and where Auto would construct whichever is smaller?

**Comment by janezd** [comment] 2020-06-12 07:18
Sparse.

**Comment by ajdapretnar** [comment] 2020-06-12 08:32
> If a small sparse table is attached to a large dense one, I would hope to get a dense table.

I suppose so. That would make sense.

**Comment by janezd** [comment] 2020-06-12 09:32
@ajdapretnar, @markotoplak opposed "auto". His argument for "sparse" was that if you create dense instead sparse, the memory requirement will grow immensely, while if you create sparse instead of dense, the memory grows by a factor of `(sizeof(int) + sizeof(double)) / sizeof(double) = (4 + 8) / 8 = 1.5`.

**Comment by janezd** [comment] 2020-06-22 10:58
I think you're wrong. It seems to me that Bag of Words output a CSC and the Corpus widget outputs a CSR matrix, not a dense one!

If any table is sparse, `Table.concatenate` calls `sp.vstack`, which decides the matrix format. `sp.vstack` does the best it can and creates a COO. The Table widget (and many others) then fails when indexing it, that is, in `text.corpus.Corpus.__getitem__`.

The problem cannot be fixed in `Table.concatenate`, because it is no smarter than `vstack`. The problem is that `from_numpy` allows coo matrices, but doesn't implement `__getitem__` that would be able to handle them.

We could prohibit `coo_matrix` in `from_numpy`. But this wouldn't solve anything - your workflow would still fail.

Possible solutions:

A. `from_numpy` converts `coo_matrix` to `csr_matrix`. Row operations are only efficient on csr anyway. We keep csc, though, because some add-ons might need them. Coos ... are not useful for Table.

B. We fix row Indexing for `coo_matrix`. It would be very slow, though. Besides, `__getitem__` may not be the only operation that fails.

Comments, please!

**Comment by markotoplak** [comment] 2020-06-22 11:30
A. Let's only support csr and csc for the Table.

**Comment by janezd** [comment] 2020-06-22 14:50
And `Table.from_numpy` (silently) converts all other formats, right?

**Closed** 2020-06-26 10:07 UTC
Labels: bug
