### ISSUE TITLE
Parameters tunnig

### ISSUE THREAD

**Issue by tryingtodo** [biolab/orange3#5355] opened 2021-03-22 13:01 UTC
Hi, 

thank you for making Orange. It is just great!

There is a feature I miss (and I think it was at Orange2. In the docs I see "Wrapper for tunning parameters").

**Usual situation**
You have already got a nice workflow, with your data and a model -lets say Random Forest- that gets a worthy 75%
You can change the number of trees from 10 to 50 and see if it improves. After that, you can go to 100 trees, to 200...

But there are other parameters to get tunned, like the ones of growth control, etc.

Could be a way to do that semautomatic? 

Perhaps the user chooses the parameters and a range of values, something like that. I'm used to do that in other programs, like Weka.

**Alternative solution**
I think this is quite common when you work with classification/regression problems. 
Perhaps while getting ready an elegant solution (widget, addon...) a "precooked" workflow-example can be enough.

Well, that's the idea.

Thanks for your work!

**Comment by janezd** [comment] 2021-03-26 09:05
This is definitely something we'd like to have and we were also thinking (a lot) about it, but we don't know how to implement it generally enough. It will come, some day.

We have this on our minds, so I'm closing this as duplicate of #1327 (refered to in #4090).

**Closed by janezd** 2021-03-26 09:05 UTC

**Comment by tryingtodo** [comment] 2021-03-26 09:18
Sorry for the duplicate and thank you for your work!

Think about a workflow as a “quick and dirty” solution for the meantime.

Hvala še enkrat! (I hope it means thanks again…)


[Resultado de imagen de LOGO HAZI]

Javier Perez Perez
Natura Ingurune Arloa / Área de Medio Natural

***@***.******@***.***> | www.hazi.eus<http://www.hazi.eus/>
T 945 003 240 –– M 627 92 56 96
Hazi | Granja Modelo de Arkaute s/n | 01192 Arkaute – Araba







*********************  LEGE OHARRA   *******************   AVISOLEGAL   *******************   DISCLAIMER   *****************************
Mezu hau pertsonala eta isilpekoa da eta baimenik gabeko erabilera debekatua dago legalki. Jasotzailea ez bazara ezabatu mezua, bidali eta kontserbatu gabe.
Este mensaje es personal y confidencial y su uso no autorizado está prohibido legalmente. Si usted no es el destinatario, proceda a borrarlo, sin reenviarlo ni conservarlo.
This message is personal and confidential, unauthorised use is legally prohibited. If you are not the intended recipient, delete it without resending or backing it.



De: Janez Demšar ***@***.***
Enviado el: viernes, 26 de marzo de 2021 10:05
Para: biolab/orange3
CC: Francisco Javier Perez Perez; Author
Asunto: Re: [biolab/orange3] Parameters tunnig (#5355)


This is definitely something we'd like to have and we were also thinking (a lot) about it, but we don't know how to implement it generally enough. It will come, some day.

We have this on our minds, so I'm closing this as duplicate of #1327<https://github.com/biolab/orange3/issues/1327> (refered to in #4090<https://github.com/biolab/orange3/issues/4090>).

**Comment by janezd** [comment] 2021-03-26 11:39
> Sorry for the duplicate and thank you for your work!

No problem at all, you couldn't have known.

> Hvala še enkrat! (I hope it means thanks again…)

It does. :)
