### ISSUE TITLE
Error to access "Add-ons" in Orange 

### ISSUE THREAD

**Issue by 1243abbas** [biolab/orange3#4981] opened 2020-09-11 16:23 UTC
my window is 10. when i want to access to "Add-ons" in Orange, it shows me an Error:

**Error encountered: 
Traceback (most recent call last): 
File "C:\Program Files\Orange\lib\site packages\orangecanvas\application\canvasmain.py", Line 2044, in open_addons.format(name),
IndexError: tuple Index out of range**

 please tell me how can i solve this problem? i want to access "Add-ons" to use "Text Mining"

Orange Version: Orange3-3.26.0-Miniconda37-x86_64
Download from: https://orange.biolab.si/

My operating system: Microsoft Windows 10 Enterprise, X64 based PC

**Comment by ales-erjavec** [comment] 2020-09-14 07:36
Duplicate of gh-4944

**Closed by ales-erjavec** 2020-09-14 07:36 UTC
Labels: bug report
