### ISSUE TITLE
Missing methods in Orange.data.Table class

### ISSUE THREAD

**Issue by jonmillard** [biolab/orange3#1275] opened 2016-05-22 12:45 UTC
##### Orange version
3.3.4

##### Expected bahavior
Converting an object of type Orange.data.Table using to_numpy method is successful

##### Actual behavior
Converting an object of type Orange.data.Table using to_numpy method results in error message indicating that this method is not implemented.

##### Steps to reproduce the behavior
>>> in_object.to_numpy()
--------------------------------------------------------------------------------
AttributeErrorTraceback (most recent call last):
  File "/usr/lib/python3.4/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
AttributeError: 'Table' object has no attribute 'to_numpy'

##### Additional info (worksheets, data, screenshots, ...)
There seem to be other methods not implemented in version 3.  I have not checked if this is the case for version 2.7.

**Comment by astaric** [comment] 2016-05-23 08:22
Orange3 stores data in numpy format, so the conversion is no longer needed. You can use table.X, table.Y and table.metas to access attribute, class values and meta data accordingly.

**Comment by ajdapretnar** [comment] 2016-07-28 10:31
@astaric Can we close this issue? How will this work with pandas?

**Comment by astaric** [comment] 2016-07-28 12:26
When we switch to pandas, it will work the same as it works now (you have X, Y and metas to get numpy tables with respective data). As this behaviour is by design, I am closing the issue as wontfix.

**Closed by astaric** 2016-07-28 12:26 UTC
Labels: enhancement
