### ISSUE TITLE
Issue Installing Orange3-Spark Add-on

### ISSUE THREAD

**Issue by packet-rat** [biolab/orange3#1730] opened 2016-11-06 23:04 UTC
##### Orange version

3.3.8

![2016-11-06_17-44-32](https://cloud.githubusercontent.com/assets/3220193/20042487/ccb686a8-a448-11e6-8fda-e4baf841df7b.png)

##### Expected behavior

Install Orange3-Spark Add-on

##### Actual behavior

Fails -   open('README.md').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

##### Steps to reproduce the behavior

(1) Click Add-Ons
(2) Select Orange3-Spark

![2016-11-06_17-38-51](https://cloud.githubusercontent.com/assets/3220193/20042450/31e03d22-a448-11e6-9644-f640ebc27aea.png)

(3) PIP Fails

![2016-11-06_17-40-48](https://cloud.githubusercontent.com/assets/3220193/20042452/38c7a22e-a448-11e6-9d93-61237d53eaec.png)

##### Additional info (worksheets, data, screenshots, ...)

```
Anaconda installation
bash Anaconda3-4.2.0-MacOSX-x86_64.sh 
conda config --add channels conda-forge
conda install orange3
pip install Orange3-Text
Run python -m Orange.canvas
```

```
Collecting Orange3-spark
  Downloading Orange3-spark-0.2.6.zip (46kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y2/5cngxgnx1s58v1cg2rsrq4pr0000gn/T/pip-build-t4ctdd8i/Orange3-spark/setup.py", line 41, in <module>
        LONG_DESCRIPTION = open('README.md').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/y2/5cngxgnx1s58v1cg2rsrq4pr0000gn/T/pip-build-t4ctdd8i/Orange3-spark/

```

**Comment by kernc** [comment] 2016-11-07 12:08
Thanks for the report. It's an add-on issue, duplicate of https://github.com/jamartinh/Orange3-Spark/issues/8.

**Closed by kernc** 2016-11-07 12:08 UTC
