### ISSUE TITLE
Installer fails to install Orange 3.25.0

### ISSUE THREAD

**Issue by raindropsfromsky** [biolab/orange3#4819] opened 2020-05-26 18:29 UTC
**Describe the bug**
Unable to install Orange 3.25.0

The installer aborts with the following log (as seen in the "Details" section):

> Extract: yaml-0.1.7-hc54c509_2.conda
> Extract: zipp-2.2.0-py_0.conda
> Extract: zlib-1.2.11-h62dcd97_3.conda
> Output folder: c:\users\Nagesh\AppData\Local\Temp\nsd98FA.tmp\Orange-Installe...
> Installing packages (this might take a while)
> Executing: cmd.exe /c install.bat "C:\Users\Nagesh\AppData\Local\Orange" "C:\Use..
> Creating a conda env in  "C:\Users\Nagesh\AppData\Local\Orange"
> 
>
> ParseError: Could not parse explicit URL: file:///C:/Users/Nagesh/AppData/Local/Te...
>
> "conda" command exited with 1. Cannot continue.

```
Note: The Installer has a non-expandable window.
I cannot scroll to see the text that lies outside its boundary.
Neither can I copy the whole text (log) with a single command like CTRL+C.
I had to read the log and type it here verbatim.
Please, for god's sake, provide these facilities in the installer!
```
**To Reproduce**
1. Either double-click on the installer, or right-click on it and select "Run as administrator" option.
2. Follow the instruction
3. Specify any path (I tried the default and other paths, with and without space in them).
4. The installer says that Conda is already installed. 
    (I had installed Orange 3.24.1 before this. So Conda is already there on my PC.)

**Orange version:**
Orange 3.25.0

**Expected behavior**
The installer should work without any issue.
Please note that it should be able to install Orange in a path, even if it has spaces in it.
(e.g. C:\Program Files\Util)

Also, I expected the error to be in Window's language, where a path is separated with backslash **\\**.
Then, why does the error message contain all **forward slashes**??
> **file:///C:/Users/Nagesh/AppData/Local/Te...**

(Is the installer trying to parse the path Linux-style, and is that why it fails to install Orange??)

**Operating system:**
Windows 10 Home, 64 bits.

**Comment by janezd** [comment] 2020-05-26 19:23
> Please, for god's sake, provide these facilities in the installer!

You look like an angry man. Is this right? Why are you angry? At whom? Somebody has given you something for free and the gift doesn't meet your standards?

> Also, I expected the error to be in Window's language, where a path is separated with backslash

Forward slashes are printed by conda, one of the two most common Python's package managers. You should report that supposed bug at [their repo](https://github.com/conda/conda). (But then maybe not.)

> I cannot scroll to see the text that lies outside its boundary.
> Neither can I copy the whole text (log) with a single command like CTRL+C.

The installer uses [NSIS](https://nsis.sourceforge.io/Main_Page), like many other Windows programs for almost twenty years already, and to my knowledge it behaves the same as everywhere - also with respect to selecting & copying & everything. If it's behaviour is not as you expect, it is again most probably not Orange's fault, and you should complain to NSIS developers.

However, in #4772, somebody managed to scroll and type -- or perhaps copy and select -- the entire log. 

Duplicate of #4772 and https://github.com/ales-erjavec/orange3-installers/issues/8.

**Closed by janezd** 2020-05-26 19:23 UTC
Labels: bug report

**Comment by raindropsfromsky** [comment] 2020-05-26 19:30
You are right: It was rude of me to use an expression like that.
Sincere apologies!
