### ISSUE TITLE
Remove GeoMap widget

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#2802] opened 2017-11-28 10:08 UTC
GeoMap widget is available here and in geo add-on. IIRC the one in the add-on is more up to date.

I propose we remove GeoMap from core and update `replaces` in GeoMap in the add-on.

**Comment by ajdapretnar** [comment] 2017-11-28 10:08
+1

**Comment by ajdapretnar** [comment] 2017-11-28 10:09
Also, partially a duplicate of #2762.

**Closed** 2017-12-11 14:44 UTC
