### ISSUE TITLE
feature constructor on partial data and concatenation

### ISSUE THREAD

**Issue by wibrt** [biolab/orange3#3612] opened 2019-02-18 12:56 UTC
##### Orange version
Orange version 3.20

##### Problem
selectively changing/adding a feature and joining (concat) them again

##### Expected behavior
values should be merged/concat correctly

##### Actual behavior
definition of new feature travels along the chain, invoking unwanted behaviour, and ignoring the subselection on which it was applied

##### Steps to reproduce the behavior
An example which makes no sense, with the sole purpose of illustrating the mal behaviour.
file: iris
select rows to make two groups: for example setosa vs the rest
setosa group: add new feature, eg length*10 called X1
the rest group: add new feature, eg length/100 called X1
concat: the two streams into one, hoping to have a new overall feature X1, with for setosa a bigger length and the rest a smaller length
result: union sees this as 2 X1's with each definition being applied to the full dataset, intersect throws out X1 although they have the same name and type.

##### Additional info (worksheets, data, screenshots, ...)
use case: imagine mixed data in cm and meter, and try to convert them all to meter, a simple use case, but it seems the widget select row, feature constructor, concat don't solve this problem; nor other widgets? solution: write a script..

**Comment by ajdapretnar** [comment] 2019-02-18 13:06
This is the intended behaviour. Please see https://github.com/biolab/orange3/issues/1943
and https://github.com/biolab/orange3/issues/2489.

Closing as a duplicate of the above issues.

**Closed by ajdapretnar** 2019-02-18 13:06 UTC

**Comment by wibrt** [comment] 2019-02-20 09:41
After reading the references i understand the choice from a backend/developer side.
From a frontend/user side this behaviour is counter intuitive.

Suggestion:
add info to http://docs.biolab.si/3/visual-programming/widgets/data/concatenate.html
and to http://docs.biolab.si/3/visual-programming/widgets/data/featureconstructor.html
