### ISSUE TITLE
When I install Orange-3.34.0. The setup was not completed successfully. The "conda" command exited with 1. Cannot continue. 

### ISSUE THREAD

**Issue by HorKingWeng** [biolab/orange3#6329] opened 2023-02-07 09:13 UTC
**What's wrong?**

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by markotoplak** [comment] 2023-02-07 10:53
Duplicate of #6330

**Closed by markotoplak** 2023-02-07 10:53 UTC
Labels: bug report
