### ISSUE TITLE
Interactive k-Means saves a blank PDF file while trying to store the figure

### ISSUE THREAD

**Issue by lfadljevic** [biolab/orange3#3735] opened 2019-04-11 14:13 UTC
##### Orange version
3.20.1

##### Educational package version
0.1.8

##### OS
Windows 10 Pro (64-bit)

##### Steps to reproduce the behavior
1. Try to paint some data
2. Open the Interactive k-Means and let it do its job
3. Try to save the figure in PDF format
4. Stored file is actually a blank PDF (without a figure)

**Comment by janezd** [comment] 2019-04-12 08:59
@PrimozGodec, can you replicate this and, if needed, open this issue in the correct repository (educational) and close it here?

**Comment by ajdapretnar** [comment] 2019-05-29 08:44
I cannot replicate this, neither on OSX nor on Win10.

**Comment by lfadljevic** [comment] 2019-05-29 08:56
May be just an isolated case, but I wanted to draw your attention to it.

**Comment by ajdapretnar** [comment] 2019-05-29 09:07
@lfadljevic Thanks! It is just hard when you can't reproduce the issue and thus not be able to fix it. I suggest we close this issue and if/when it re-occurs, we reopen it.

**Closed** 2019-05-29 09:08 UTC
