### ISSUE TITLE
Cross-referencing several workspaces?

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4785] opened 2020-05-18 09:15 UTC
**Describe the bug**
First workflow tries to apply settings from the second workflow.

**To Reproduce**
1. Have one workspace open.
2. Open a new workspace with stored settings. (Currently, I can reproduce this only on one of Karin's workflows. 🤷 )
3. Go to the first workspace and add Select Rows. It crashes with ValueError: 'X' is not in domain, where X was present only in the second workspace.

**Orange version:**
3.26.0.dev

**Expected behavior**
No crash.

**Additional context**
Unfortunately, I have not yet been able to reproduce this bug with standard Orange workflows. It seems like Orange cross-references workspaces. It tries to apply settings from workspace2 into workspace1. I will play around some more to see if it is possible to reproduce in any way. Otherwise, I will close this issue.

**Comment by janezd** [comment] 2020-05-18 10:08
Of course. Context settings are local, per widget instance, and also shared, as global, that is, per widget class. At some point(s?), local settings are merged into global.

This is essentially the difference between schema-only and non-schema-only settings. What you describe is an expected behaviour of non-schema-only settings ...

... except that Select Rows shouldn't crash. I don't understand how this can happen, but while investigating I got stuck with another bug in Select Row's settings. (I'm almost done with it, I just need to invent some tests.)

**Comment by ajdapretnar** [comment] 2020-05-18 10:15
Yes, it is a tricky one, this one. I tried out several ideas to make it fail, but couldn't (with Orange's datasets).

**Comment by janezd** [comment] 2020-05-21 07:38
The crash is bug and a duplicate of #4781.

As for context migrating between workflows, this is by design, but the number of cases where this is unexpected can be reduced after implementing #4753 and marking any settings that should not migrate as schema-only.

**Closed by janezd** 2020-05-21 07:38 UTC
Labels: bug report
