### ISSUE TITLE
Linear projection plot scoring keeps running after window is closed

### ISSUE THREAD

**Issue by processo** [biolab/orange3#6504] opened 2023-07-10 10:31 UTC
Not sure if this is intended or not, but when I start a search in _Linear projection_ (Suggest features) if I don't pause it it will keep running even when the _Linear projection_'s window is closed.

How to reproduce:
1. open _Linear projection_, _Suggest features_, start
2. close _Score plots_ window
3. close _Linear projection_ window
4. it is still running in the background (with no progress indicator around the widget icon)
5. you can open _Linear projection_ again, open _Suggest features_ and see it running

OS: Windows 10 x64
Orange: 3.35.0

**Comment by janezd** [comment] 2023-08-17 18:46
This works as intended. Closing the window was not meant to stop the optimization, and the progress bar in widgets refers to what is happening in the widget, not in another window.

Both can be changed. One could argue that the user who closes window intends to cancel the optimization, and one could argue even more that widgets that suggest feature should have a progress bar. We'll discuss this.

**Comment by janezd** [comment] 2023-08-18 15:35
We discussed this. If the computation is started by pressing a button (not by opening a window) it should also be stopped/paused by pressing a button (not closing a window). On the other hand, others also said that they expected that closing the window would stop the computation.

1. We decided to check the existing widgets that offer this functionality and see whether we could change to start the calculation immediately.
2. A progress bar would be useful, but it's not the widget's "main" progress bar. Instead, the bar should be around/under/in the button Suggest Features. Ideally, the button background could serve as a bar, though this is hard to do in Qt. (A hack by @ales-erjavec in a pull request for showing uncommitted signals could be useful here.)

Thanks for your comment. We'll do something about this.

**Comment by janezd** [comment] 2023-08-24 19:04
Re 1: Unless I overlooked any, widgets with a VizRank-like buttons are Linear projection, Radviz, Mosaic, Sieve, Scatter plot. The last two are not a problem, while the first three allow the user to control the number of variables. The corresponding spin/combo is disabled while the widget is running. If vizrank starts immediatelly then my concern is that the user may not be aware that it can enable the control by stopping (pausing) the computation.

**Closed** 2023-12-14 12:54 UTC
Labels: wish, meal
