### ISSUE TITLE
Venn Diagram only contains zeros

### ISSUE THREAD

**Issue by kernc** [biolab/orange3#1099] opened 2016-03-10 19:05 UTC
##### Steps to reproduce

Load iris.tab and connect File → Select Rows → Venn Diagram. And connect File → Venn Diagram.
Set condition in Select Rows: `sepal_length > 5`.
##### Expected bahavior

Venn Diagram contains correct number of instances in each slice.
##### Actual behavior

Venn Diagram shows 0 instances in all slices.
##### Additional info (worksheets, data, screenshots, ...)

[venn-zeros.ows.txt](https://github.com/biolab/orange3/files/167812/venn-zeros.ows.txt)

![screenshot - 03102016 - 08 02 55 pm](https://cloud.githubusercontent.com/assets/684364/13680960/32b290b6-e6fb-11e5-83ad-8c5d4d7143c5.png)

**Comment by shark-S** [comment] 2016-03-10 21:37
Hi @kernc  i have checked same configuration but it is giving correct ouput. there intersection is 117 rest one is 0 and another is 30 is this ryt??

**Comment by mudit5bachhawat** [comment] 2016-03-11 06:07
Hi @kernc , I checked the same. Getting same result as @shark-S. Can you give some other details?

![screenshot from 2016-03-11 11 33 20](https://cloud.githubusercontent.com/assets/6140491/13694644/752f4d08-e77d-11e5-8139-78b3153557ba.png)

**Comment by ajdapretnar** [comment] 2016-03-11 07:50
It's not exactly the right configuration. It has to be as below. So two Select Rows widgets give two empty sets and an empty intersection (even though the intersection should exist based on the data).

![capture](https://cloud.githubusercontent.com/assets/12524972/13696360/2dcfad70-e766-11e5-8e1a-666422173917.PNG)

**Comment by kernc** [comment] 2016-03-11 09:31
@shark-S, @mudit5bachhawat Download [the attached venn-zeros.ows](https://github.com/biolab/orange3/issues/1099#issue-139980983) file (remove the .txt extension) and try with that.

**Comment by mudit5bachhawat** [comment] 2016-03-11 09:31
Yes, I got that. Working on this.

**Comment by ales-erjavec** [comment] 2016-04-08 11:32
The root cause of this is that the two input data sets which are presented to the 'Venn Diagram' widget **do not** have the same domain due to the use of 'Remove unused classes' option in 'Select Rows' (and a suitably chosen filter to exclude all instances with some class value). The exact same thing happens when the widget is presented with, say, *iris.tab* and *lenses.tab* data sets.

**Comment by ajdapretnar** [comment] 2016-07-28 10:47
@kernc Do you agree this is not an issue anymore, it's just a matter of workflow configuration? Can we close this?

**Comment by kernc** [comment] 2016-07-28 17:34
Indeed, if I disable those checkboxes (Remove unused features/classes), then the diagram is not all zeros. But I don't think I am able to read it. Where do those 0, 4, and 20 come from, and why aren't there 0, 885, and 2201?
![screenshot - 07282016 - 07 28 45 pm](https://cloud.githubusercontent.com/assets/684364/17222765/2d34277c-54fa-11e6-9278-e1e453948763.png)

**Comment by ajdapretnar** [comment] 2016-07-29 06:38
I checked this and it is truly bizarre. :open_mouth: We need to give a look into Venn, asap.

**Comment by sstanovnik** [comment] 2016-07-29 06:42
Venn definitely needs a (complete) rewrite, judging by the time I spent adapting it to pandas. I suspect that will be absurdly easy with #1347.

**Comment by astaric** [comment] 2016-12-12 08:37
The original problem (Venn containing zeroes) has been resolved (uncheck the Remove checkboxes in select rows widget).

Smaller numbers are caused by Venn Diagram visualizing **sets** of data, and titanic dataset containing many duplicates (as it only has a small number of discrete features). If that behaviour should be changed, a separate issue should be opened describing the suggested change so we can comment on it.

**Closed by astaric** 2016-12-12 08:37 UTC
Labels: gsoc
