### ISSUE TITLE
Geo_3.2 does not work anymore on Orange 3.34.0 and 3.34.1

### ISSUE THREAD

**Issue by GLad-Arioch** [biolab/orange3#6266] opened 2022-12-21 09:40 UTC

**Comment by markotoplak** [comment] 2022-12-21 10:35
It works for me.

For us to debug the issue, please specify what you mean by not working, your platform, how did you install Orange and how did you install the add-on.

Or did it install at all? Do you see it in your add-on dialog? If there were installation errors, please copy-paste them here.

**Comment by GLad-Arioch** [comment] 2022-12-24 06:36
Hi Marko,

Thank You for your quick reply.

I tried to use Geo 3.2 again today. It still does not work on my 2 different computers.

- Windows 11 OS with 8 cores or 24 cores + 16 or 64 g of ram : R, Stata and other softwares run without problem.

- Orange 3.34.1 installed via the installer
- Geo add-on installed from Orange > Options > Add-ons...
Uninstalled and re-installed 3 times  (Orange + Anaconda + Geo)
Used the default settings as recommended.
Installation seems fine.

-" does not work" means :
-Sending data to  Geocoding_widget  causes a " is not responding" -situation > Orange hangs on indefinitely.

- By-passing Geocoding and sending data with Longitude and Latitude coordinates  in decimal degrees to the  ChoroplethMap_widget  causes a " is not responding" -situation > Orange hangs on indefinitely.

Note that I can place the widgets on the canvas and I can open the widgets. But whenever I send data (csv of tsv format, it does not matter) Orange stops working.

I attach data and a picture of Orange in the Limbo

Best regards, 

Guillaume


[WorldTrade1994_attributes.csv](https://github.com/biolab/orange3/files/10298105/WorldTrade1994_attributes.csv)
![OrangeGeo_in_the_Limbo](https://user-images.githubusercontent.com/78728418/209424660-45f34e5f-36d4-4f9b-8bb3-525415c063e6.jpg)

**Comment by kaimikael** [comment] 2022-12-29 09:03
I can confirm this behaviour, reported in https://github.com/biolab/orange3-geo/issues/156
In my class it seems not all students are affected, but I have not been able to isolate what is different for those for whom it works.

**Comment by ales-erjavec** [comment] 2023-01-04 13:14
Fixed in https://github.com/biolab/orange3-geo/issues/156

**Closed by ales-erjavec** 2023-01-04 13:14 UTC
