### ISSUE TITLE
RMSE values totally wrong, even display negative RMSE values

### ISSUE THREAD

**Issue by ystsan** [biolab/orange3#4220] opened 2019-11-25 15:12 UTC
RMSE values totally wrong, even display negative RMSE values

**To Reproduce**
Use any regression model - See Screen shots

**Orange version:**
Orange - About - 3.23

**Expected behavior**
RMSE figures are wrong

**Screenshots**
![RMSE computation wrong_negative values](https://user-images.githubusercontent.com/57836437/69552241-16057e00-0fd9-11ea-8149-a30c1261c7bc.GIF)
![RMSE computation wrong](https://user-images.githubusercontent.com/57836437/69552242-16057e00-0fd9-11ea-9ac4-1c4d3cd77894.GIF)

**Operating system:**
Windows
**Additional context**

**Comment by janezd** [comment] 2019-11-25 17:06
Duplicate of #4029, fixed in #4030. If I'm correct, 3.23.1 (but not 3.23) already works correctly.

You're not seeing RMSE -- columns are misaligned.

**Closed by janezd** 2019-11-25 17:06 UTC
Labels: bug report
