### ISSUE TITLE
Orange crashes when browsing for file

### ISSUE THREAD

**Issue by ferlocar** [biolab/orange3#4486] opened 2020-03-02 19:33 UTC
**Describe the bug**

When I try to search for a file using the File widget by clicking on the folder option, Orange crashes (i.e., suddenly closes).

**To Reproduce**

1. Open Orange
2. Add a File widget.
3. Click on the folder icon.
4. Orange crashes.

**Orange version:**
Orange - 3.24

**Expected behavior**
Be able to search and load a file (e.g., a csv file) without Orange suddenly closing. 

**Screenshots**
I tried running Orange from the command line, this is the output message that I get in the command line after Orange crashes:
```
ERROR:orangecanvas.help.provider:An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('https://docs.orange.biolab.si/3/visual-programming/')'
Segmentation fault: 11
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Operating system:**
macOS Catalina 10.15.3

**Additional context**
This is pretty much the same issue described in here: https://github.com/biolab/orange3/issues/4146

**Comment by markotoplak** [comment] 2020-03-03 12:08
Are you using the official .dmg packages or did you install Orange in some other way? If so, how did you do it?

**Comment by ferlocar** [comment] 2020-03-03 18:25
I'm using the official .dmg packages.

**Comment by ferlocar** [comment] 2020-03-03 22:41
By the way, the problem started after I upgraded from version 3.23 to version 3.24.

**Comment by markotoplak** [comment] 2020-03-06 11:04
@ferlocar, could you try executing `/Applications/Orange3.app/Contents/MacOS/pip install pyqt5~=5.9.0` in the terminal and then restarting Orange? Here I am assuming that you copied Orange to Applications.

Also, what is the language on your system? Does your username contain and non-latin characters? What does `pwd` in a freshly open terminal show you?

**Comment by ferlocar** [comment] 2020-03-10 21:53
We tried what you mentioned. This is the output:
![image](https://user-images.githubusercontent.com/692704/76362500-8b326000-62f7-11ea-8f01-cf3e791883ac.png)

The language of the system is English, and the username does not contain any non-latin characters. The `pwd` command shows the following: `/Users/tuanhaoly`

Just to clarify, this is an issue that a student of mine is having in his laptop. I'm teaching a data mining course using Orange, and that's why I posted this issue in his behalf. I will provide him the link to this issue so that you and him can troubleshoot the error together. We really appreciate your help on this.

**Comment by markotoplak** [comment] 2020-03-10 21:58
@ferlocar, thank you. I asked you to execute `/Applications/Orange3.app/Contents/MacOS/pip install pyqt5~=5.9.0` (with the full path, starting from  `/Applications`). That command would replace a library from within the Orange app that was installed from dmg. Then you could try running Orange again.

**Comment by janezd** [comment] 2020-03-20 14:42
We can't reproduce this, so we're closing the issue for now. If other users encounter something similar, we'll reopen.

**Closed by janezd** 2020-03-20 14:42 UTC
Labels: bug
