### ISSUE TITLE
"Line Chart" widget remembering column selection

### ISSUE THREAD

**Issue by DoctorDib** [biolab/orange3#4697] opened 2020-04-24 09:43 UTC
**Is your feature request related to a problem? Please describe.**
Personally I am not quite sure if this is a known issue or a bug, however when importing data using the "CSV File Import" widget and then branch of into a "Line Chart" widget, setting up the columns by selecting in the left hand side does not save. When saving the workspace and restarting the Orange application, the "Line Chart" widgets would lose their selected columns, meaning I am required to go through each "Line Chart" and reselect the columns. 

I have tried the same test with "Scatter Plot" widgets, and after restarting the Orange application, it seems to remember the chosen columns. 

**Describe the solution you'd like**
Potentially add a way for the Orange workspace to remember which columns had been selected for the "Line Chart" widget. I have not tested to see if there are any other similar issues with other widgets except from the "Scatter Plot", but it is just frustrating when having a big project and losing all of the work when coming back to it the next day.

**Additional context**
The screenshot below just shows one of my simple layouts that I am using that gets affected once I reset the Orange application. I am required to open the "Line Chart" and reselect the columns.

![image](https://user-images.githubusercontent.com/14931616/80197928-45b3c300-8617-11ea-8588-6b39ce009171.png)

I do hope this was helpful.

**Comment by janezd** [comment] 2020-04-25 10:43
You're right, this is broken.

This widget comes from the time-series add-on. I opened an issue [there](https://github.com/biolab/orange3-timeseries/issues/108), so I'm closing it here.

This will be a problem, though. The widget uses highcharts (in javascript), which we are phasing out. The issue is thus somewhat irrelevant -- it will be fixed when the widget is rewritten from scratch, but this will take some time.

**Closed by janezd** 2020-04-25 10:43 UTC
