### ISSUE TITLE
Mac user cannot upload TAGS URL to Orange

### ISSUE THREAD

**Issue by dariasin** [biolab/orange3#6161] opened 2022-10-04 22:53 UTC
**What's wrong?**
<img width="1221" alt="Screen Shot 2022-09-21 at 1 04 54 PM" src="https://user-images.githubusercontent.com/43657290/193877414-9756b836-7033-4c9f-9385-d20e66d9e6a2.png">

 The red exclamation point shows on top of the "File" widget because the info through the Google sheet won't load. When I load the google sheet link, nothing generates in Orange. The link is not broken. However, there might be a problem with the URL path as well. Maybe it shouldn't say edit? Or maybe it has to do something with Orange running on mac, and something needs to be changed in the privacy settings on Mac? 

**How can we reproduce the problem?** 

Here's the URL link I am uploading. 

https://docs.google.com/spreadsheets/d/1HLkURuJyrMt38cG88bFI6HZBbqVtojyBBiOjI9F4bSc/edit?usp=sharing 

 The .ows zip file is attached. 

[Plat.ows.zip](https://github.com/biolab/orange3/files/9709307/Plat.ows.zip)

Looking forward to hearing back from you soon!

**Comment by ales-erjavec** [comment] 2022-10-07 08:21
I cannot duplicate this on latest released version of Orange. Which version are you using? 

This looks like a duplicate of https://github.com/biolab/orange3/issues/5723 which should be fixed since version 3.32.0.

**Comment by wvdvegte** [comment] 2022-10-12 13:55
I could actually duplicate what I reported in Orange 3.33.0:
https://docs.google.com/spreadsheets/d/1HLkURuJyrMt38cG88bFI6HZBbqVtojyBBiOjI9F4bSc/edit?usp=sharing produces an error
https://docs.google.com/spreadsheets/d/1HLkURuJyrMt38cG88bFI6HZBbqVtojyBBiOjI9F4bSc/ loads the data
https://docs.google.com/spreadsheets/d/1HLkURuJyrMt38cG88bFI6HZBbqVtojyBBiOjI9F4bSc loads that data, too

**Comment by ales-erjavec** [comment] 2022-10-26 11:44
I some times get intermittent read time out errors but that is it.
 
Can you please post the error message (click on the **Read error:** in the bottom right of the File widget and copy the full text).

**Comment by wvdvegte** [comment] 2022-10-26 16:17
> Can you please post the error message

Read error:
The read operation timed out

**Comment by ales-erjavec** [comment] 2022-10-27 11:57
This happens every time? I get them sometimes but on both https://docs.google.com/spreadsheets/d/1HLkURuJyrMt38cG88bFI6HZBbqVtojyBBiOjI9F4bSc/edit?usp=sharing as well as https://docs.google.com/spreadsheets/d/1HLkURuJyrMt38cG88bFI6HZBbqVtojyBBiOjI9F4bSc. A **Reload** solves them.

**Comment by wvdvegte** [comment] 2022-10-27 12:02
You're right - I tried again and it doesn't happen all the time. Perhaps it's just a responsiveness issue in Google Docs.

**Closed** 2022-11-09 18:43 UTC
Labels: bug

**Comment by wvdvegte** [comment] 2022-11-11 10:33
I'm getting a different read error now: when inserting the URL https://drive.google.com/file/d/1Nyi0VnyOGDg5WeRzDJt3K6F8Xu_9ZwWq/view?usp=share_link("anyone with the link can view"), I'm getting "Read error: No readers for file "/var/folders/59/db8x75gs6nq0y62dk2pvn1vmn5nd3m/T/tmphlp3d6i8""
I have no idea what this path is referring to, iot doesn't bear any resemblance with the link to Google Drive

**Comment by ales-erjavec** [comment] 2022-11-11 13:04
> I'm getting a different read error now: when inserting the URL https://drive.google.com/file/d/1Nyi0VnyOGDg5WeRzDJt3K6F8Xu_9ZwWq/view?usp=share_link ("anyone with the link can view"), I'm getting "Read error: No readers for file "/var/folders/59/db8x75gs6nq0y62dk2pvn1vmn5nd3m/T/tmphlp3d6i8""
> I have no idea what this path is referring to, iot doesn't bear any resemblance with the link to Google Drive.
> Edit/update: every time I hit Reload, the part after the last / is different.

That is a google drive link that is not currently supported (only google sheets and dropbox share links are supported). Use https://sites.google.com/site/gdocs2direct/ to convert the link to a direct download link and use that .

**Comment by wvdvegte** [comment] 2022-11-14 08:29
> That is a google drive link that is not currently supported (only google sheets and dropbox share links are supported). Use https://sites.google.com/site/gdocs2direct/ to convert the link to a direct download link and use that .

Thanks, that helped! Perhaps a good idea to add this information to the help page on the File widget.
