### ISSUE TITLE
Orange not notarized for Catalina (was: ... not opening on Mojave)

### ISSUE THREAD

**Issue by andrewpeace** [biolab/orange3#3613] opened 2019-02-18 15:33 UTC
##### Orange version
Orange 3.20.1

##### Expected behavior
Downloaded Orange3-3.20.1.dmg and installed into Applications directory. Opened as detailed using Finder, right click on Orange3 and Open. Orange 3 icon bounces up and down whilst "verifying Orange3..." and prompting "Orange3 is an app downloaded from the internet - Do you wish to Open it" which I confirm. The Orange 3 icon stops bouncing but no Orange3 user interface appears.

##### Actual behavior
No User Interface appears on the screen.

##### Steps to reproduce the behavior
I have tried deleting and reinstalling the app, and restarting the Mac but to no avail

##### Additional info (worksheets, data, screenshots, ...)
I have also tried the following as suggested on Mac App Store / Orange

Install the _App_

Press Command+Space and type Terminal and press enter/return key.
Run in Terminal app:
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null ; brew install caskroom/cask/brew-cask 2> /dev/null
and press enter/return key. 
If the screen prompts you to enter a password, please enter your Mac's user password to continue. When you type the password, it won't be displayed on screen, but the system would accept it. So just type your password and press ENTER/RETURN key. Then wait for the command to finish.
Run:
brew cask install orange

Just the same result as before with the icon bouncing and then stopping with nothing opening.

**Comment by ales-erjavec** [comment] 2019-02-18 15:51
Can you please run `/Applications/Orange3.app/Contents/MacOS/Orange -l4` from the terminal an post the full output?

**Comment by andrewpeace** [comment] 2019-02-18 15:56
Thanks Ales

Last login: Mon Feb 18 15:09:04 on ttys000
PeaceFamilyiMac:~ andrewpeace$ /Applications/Orange3.app/Contents/MacOS/Orange -l4
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/__main__.py", line 568, in <module>
    sys.exit(main())
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/__main__.py", line 277, in main
    make_sql_logger(sql_level)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/__main__.py", line 119, in make_sql_logger
    handler = RotatingFileHandler(os.path.join(config.log_dir(), 'sql.log'),
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/config.py", line 195, in log_dir
    os.makedirs(logdir)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/../../../../lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/andrewpeace/Library/Logs/Orange Canvas'
PeaceFamilyiMac:~ andrewpeace$

**Comment by andrewpeace** [comment] 2019-02-19 14:06
Thanks Ales,

I have changed the permission rights for '/Users/andrewpeace/Library/Logs/ and now everything is working correctly!

**Comment by ykar123** [comment] 2019-03-23 20:13
Hello
I have the same problem, how you change the permission rights?
Thank you

**Comment by andrewpeace** [comment] 2019-03-24 11:39
Hi John,

I changed the permission rights as follows;

1/ using Finder I clicked on McIntosh HD which was listed in the Locations section.
2/ Then I selected Library, Log etc until I got to the file I didn’t have permission for.
3/ Highlight this file and right click your mouse - select get info.
4/ You can then click the padlock at the bottom of the information, give your administration password which unlocks the padlock, change the permission to read and write, and finally re-click the padlock.
5/ This allowed Orange to be installed when I re-ran the installation.

Hope this helps as it’s a really great piece of software.

Best wishes,

Andy

**Comment by markotoplak** [comment] 2019-03-24 11:52
@andrewpeace and @ykar123, thank you for your report. I am reopening this as it seems systematic.

**Comment by ykar123** [comment] 2019-03-24 17:11
Thank you Andy,
 I tried to follow your steps, but I cannot find orange canvas file.  step2

Thank you
John

**Comment by ykar123** [comment] 2019-03-24 17:15
MacBooks-MacBook-Pro:~ macbook$ /Applications/Orange3.app/Contents/MacOS/Orange -l4
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/__main__.py", line 629, in <module>
    sys.exit(main())
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/__main__.py", line 338, in main
    make_sql_logger(sql_level)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/__main__.py", line 177, in make_sql_logger
    handler = RotatingFileHandler(os.path.join(config.log_dir(), 'sql.log'),
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/config.py", line 191, in log_dir
    os.makedirs(logdir)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/../../../../lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/macbook/Library/Logs/Orange Canvas'

This is the output from terminal

**Comment by ykar123** [comment] 2019-03-24 17:49
Hello Andy
got to the file I didn’t have permission for.??? Which file

Thanks
John

**Comment by andrewpeace** [comment] 2019-03-24 18:58
Hi John,

I’m pretty sure I just set the directory Logs ( ~/Library/Logs) to read and write permission ( it was originally showing just read permission). 

Hope that works.

Andy

**Comment by janezd** [comment] 2019-06-02 15:33
@markotoplak, this is stalled. Fix it or forget it?

**Comment by markotoplak** [comment] 2019-06-03 06:58
@janezd, I can not replicate this on my system. I do not have Mojave.

**Comment by janezd** [comment] 2019-06-03 08:12
I know. I just wonder whether we should pursue it (find Mojave etc) or assume the issue is obsolete and rare enough and close it. (I prefer to purge stalled issues that will never be fixed.)

**Comment by mrn-aglic** [comment] 2019-10-10 11:53
Orange3 won't open on OS X Catalina, used to work normally on Mojave.

**Comment by markotoplak** [comment] 2019-10-10 12:24
@mrn-aglic, did you perhaps also try with 3.23.1? Which error do you get? Thanks!

**Comment by mrn-aglic** [comment] 2019-10-10 12:55
Yeah, I just downloaded the latest version.

When I first tried to open Orange3 (after downloading) I got a dialog box telling me that the OS can't scan for malicious content.

<img width="1148" alt="Screenshot 2019-10-10 at 14 54 38" src="https://user-images.githubusercontent.com/2858231/66570494-fcfe5600-eb6d-11e9-932c-d79d206eb75a.png">


Here is the error:


`Process:               Python [7533]
Path:                  /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Python [7533]
User ID:               501

Date/Time:             2019-10-10 13:59:06.091 +0200
OS Version:            Mac OS X 10.15 (19A583)
Report Version:        12
Anonymous UUID:        C25AD9C7-9408-265A-F38F-D0240EFFC1C9


Time Awake Since Boot: 2100 seconds

System Integrity Protection: enabled

Crashed Thread:        15  Qt bearer thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000014720920
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [7533]

VM Regions Near 0x14720920:
--> 
    __TEXT                 0000000100000000-0000000100001000 [    4K] r-x/rwx SM=COW  /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00000001013f2182 semaphore_wait_trap + 10
1   QtCore                        	0x00000001112b0e68 QBasicMutex::lockInternal(int) + 1016
2   QtCore                        	0x00000001112b0a51 QMutex::lock() + 113
3   QtNetwork                     	0x00000001361c069a QNetworkConfigurationManagerPrivate::capabilities() const + 26
4   QtNetwork                     	0x00000001361655fd 0x136141000 + 148989
5   QtNetwork                     	0x000000013615fe28 QNetworkAccessManager::QNetworkAccessManager(QObject*) + 40
6   QtNetwork.so                  	0x000000014077b021 init_type_QNetworkAccessManager(_sipSimpleWrapper*, _object*, _object*, _object**, _object**, _object**) + 113`

**Comment by ales-erjavec** [comment] 2019-10-10 13:34
@mrn-aglic  Can you please try running
```
/Applications/Orange3.app/Contents/MacOS/pip install pyqt5==5.12.3 pyqtwebengine==5.12.1
```
from the terminal and start Orange again.

**Comment by mrn-aglic** [comment] 2019-10-10 15:19
@ales-erjavec your suggestion worked!
@janezd right click did not work for me before using @ales-erjavec suggestion.

**Comment by JakaKokosar** [comment] 2019-10-21 20:35
The orange installer is now codesigned, notarised and available for download at https://orange.biolab.si/download/.

@mrn-aglic and anyone else on OS X Catalina, please do a fresh install and test if you still get prompted by that security check. Thanks!

**Comment by janezd** [comment] 2019-10-22 09:09
Works for me!

**Comment by PrimozGodec** [comment] 2019-10-22 09:10
I will upgrade to Catalina and then test. 

Is notarization required for every release? The instruction should be add to  https://github.com/biolab/orange3/wiki/Preparing-a-release

**Comment by JakaKokosar** [comment] 2019-10-22 11:00
@PrimozGodec Yes, this has to be done on every release. Will update wiki soon :)

**Comment by mrn-aglic** [comment] 2019-10-22 15:12
Doesn't seem to work for me. After installing Orange3 it just opens and closes.

**Comment by janezd** [comment] 2019-10-22 16:35
This doesn't have to be related to Catalina. It happenned to me on Mojave, too. I tried multiple times, but it didn't work. I then ran Orange from terminal from inside the bundle once (I forgot what exactly I ran) to see the output. But it worked, and after this it also works when run the normal way.

**Comment by janezd** [comment] 2019-11-14 18:47
Continues in #4186.

**Closed by janezd** 2019-11-14 18:47 UTC
Labels: needs discussion

**Comment by WolframRinke** [comment] 2019-11-23 20:44
Hi all, I have a similar issue now. Orange3 was working on Catalina for some time, but since the last update on Catalina it is crashing all the time. No idea why. I tried to reinstall Xcode, python, etc .... 
No success at all.
I have attached a crash dump maybe it helps.
Regardds, Wolfram
[Orange3 crashes on Catalina.pdf](https://github.com/biolab/orange3/files/3882899/Orange3.crashes.on.Catalina.pdf)
