### ISSUE TITLE
Not able to connect to see addons in Orange 3.25

### ISSUE THREAD

**Issue by AndSwe** [biolab/orange3#4729] opened 2020-05-04 12:42 UTC
I downloaded orange 3.25.0 and installed it without problems. I checed the addons and updated those that needed update. I restarted Orange without problems. No i cant see the addon list anymore. instead i get this error message.
![Orange](https://user-images.githubusercontent.com/64785791/80966700-4b7a8700-8e15-11ea-9b1b-75b002cadcc8.PNG)
This error message have the following details:
Traceback (most recent call last):
File "C:\Users\Anders.SPINNAREN\AppData\Local\Orange\lib\concurrent\futures\thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "C:\Users\Anders.SPINNAREN\AppData\Local\Orange\lib\site-packages\orangecanvas\application\addons.py", line 679, in <lambda>
lambda config=config: (config, list_available_versions(config)),
File "C:\Users\Anders.SPINNAREN\AppData\Local\Orange\lib\site-packages\orangecanvas\application\addons.py", line 1227, in list_available_versions
response = session.get(PYPI_API_JSON.format(name=p))
File "C:\Users\Anders.SPINNAREN\AppData\Local\Orange\lib\site-packages\requests\sessions.py", line 546, in get
return self.request('GET', url, **kwargs)
File "C:\Users\Anders.SPINNAREN\AppData\Local\Orange\lib\site-packages\requests\sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "C:\Users\Anders.SPINNAREN\AppData\Local\Orange\lib\site-packages\requests\sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "C:\Users\Anders.SPINNAREN\AppData\Local\Orange\lib\site-packages\cachecontrol\adapter.py", line 44, in send
cached_response = self.controller.cached_request(request)
File "C:\Users\Anders.SPINNAREN\AppData\Local\Orange\lib\site-packages\cachecontrol\controller.py", line 145, in cached_request
resp = self.serializer.loads(request, cache_data)
File "C:\Users\Anders.SPINNAREN\AppData\Local\Orange\lib\site-packages\cachecontrol\serialize.py", line 97, in loads
return getattr(self, "_loads_v{}".format(ver))(request, data)
File "C:\Users\Anders.SPINNAREN\AppData\Local\Orange\lib\site-packages\cachecontrol\serialize.py", line 182, in _loads_v4
cached = msgpack.loads(data, encoding="utf-8")
File "msgpack/_unpacker.pyx", line 144, in msgpack._cmsgpack.unpackb
TypeError: unpackb() got an unexpected keyword argument 'encoding'

**Comment by ajdapretnar** [comment] 2020-05-04 12:44
Duplicate of #4720.

**Closed by ajdapretnar** 2020-05-04 12:44 UTC
Labels: bug report
