### ISSUE TITLE
Widgets should work normally with 700 pixels of vertical space

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3058] opened 2018-06-08 06:57 UTC
Widgets should work normally with 700 pixels of vertical space. This is important for presentations on x768 projectors and for display on small laptop screens.

Some Windows laptops are quite small, have 1920x1080 resolution, and due to the save, have often scaling set to 150%. Which means their effective resolution is x720, which can make at least Scatter plot and MDS widgets unusable.

**Comment by ajdapretnar** [comment] 2018-06-29 10:06
Any ideas how to approach this?

**Comment by markotoplak** [comment] 2018-06-29 10:10
1. Make tests that fail if any widget is too big.
2. Redesign the interface. Widget specific. Perhaps hide some options into a pane that only appears when user clicks a button?

**Comment by ajdapretnar** [comment] 2018-06-29 10:14
Hm... 🤔 You mean like _Advanced_ button in the bottom row? Where we would have, say, Jittering, Shape & Size, Symbol size, Opacity and Plot Properties?
How about a 🔽 button that extends the widget? Is that too kitsch?

**Comment by markotoplak** [comment] 2018-06-29 10:15
We cannot extend the widget as there is no space. :) We could try make the setting area scrollable though.

**Comment by ajdapretnar** [comment] 2018-06-29 10:16
I think large widgets could benefit from some simplification, where we would move less used features to the background. Retain them, of course, since they are useful sometimes, but have just really core features in the front.

> We cannot extend the widget as there is no space. :) We could try make the setting area scrollable though.

Yes, yes, something like that.

**Comment by janezd** [comment] 2018-06-29 10:18
The priority should be to make widgets simpler. We had tabbed control areas, and we had collapsable boxes, but decided they are too invisible and complicated. I would use them as the last resort.

**Comment by ajdapretnar** [comment] 2018-06-29 10:19
> The priority should be to make widgets simpler.
Absolutely. But all too often the users ask us for a functionality they need/would like to have. Removing too many things makes Orange useless for some real analysis. I think some advanced settings are desirable, they just don't have to be at the forefront of the widget. No?

**Comment by janezd** [comment] 2018-06-29 11:21
Case-by-case. I'm warning against collapsable boxes, tabs, and (I forgot) scrolling, because they make it too easy for us to just add whatever feature somebody wants. No changing of backgrounds and label fonts. But, of course, without sacrificing anything actually useful.

Having just 700 pixels is uncommon. Widgets shouldn't become more complicated (by hiding stuff) or less useful (by us removing stuff) to cover just a few users/use cases. What about some responsive design?

**Comment by markotoplak** [comment] 2018-06-29 11:35
> Having just 700 pixels is uncommon. 

Not that uncommon. 13 inch windows laptops are frequently 1366x768. 

Even small monitors that are natively 1920x1080 are often 150% scaled, which makes it x720. And then OS takes some space. On the last workshop we had to disable scaling in system properties for 5/20 students (then everything was tiny, but at least it appeared).

**Comment by kernc** [comment] 2018-06-29 20:35
One of the hallmark assumptions of responsive design, in established terms, is that one dimension is readily available, i.e. infinite vertical scrolling space.

Even if we add expandable [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details),<details>personally, :+1:,</details> the unskilled user with a small screen resolution would still have no way to fiddle with controls that overflow.

A normal solution (in shit like configuration and installation dialogs) would be to use scroll areas. http://doc.qt.io/qt-5/qscrollarea.html

**Comment by markotoplak** [comment] 2018-07-20 08:27
So is anyone willing to write tests for that? A test that would go through all the widgets and would fail if a widget is too big? And then perhaps we can fix the hopefully (few) offenders.

**Comment by janezd** [comment] 2019-01-24 22:08
Duplicate of something I just closed. @markotoplak, if you're willing to do it, write the tests. You can also reopen the issue. :)

But don't be too strict: I'd prefer just a warning, and in such a way that it can be silenced by widgets that can't help but be large.

**Closed** 2019-04-01 08:24 UTC
Labels: friday
