### ISSUE TITLE
Mosaic plot produces KeyError

### ISSUE THREAD

**Issue by kernc** [biolab/orange3#854] opened 2015-11-17 13:15 UTC
@ypanagis in the [original issue report](https://github.com/biolab/orange/issues/38) says:
> I am trying to load the titanic dataset from the example datasets given with Orange and build a mosaic plot with it. After I select all the data from the DataTable the Output window pops-up and I get the error below. I am using version `3.2.dev0+ee85297` in Windows7 x64. Orange was installed with Python 3.4 32bits that was pre-existing in my machine

> ```python
unable to set <Orange.widgets.gui.OrangeComboBox object at 0x04E6E6C0> to value 'Feature 9'. Possible values are status, age, sex, survived.
--------------------------------------------------------------------------------
KeyError                                      Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 690, in process_signals_for_widget
    widget.handleNewSignals()
  File "C:\Python34\lib\site-packages\Orange\widgets\visualize\owmosaic.py", line 396, in handleNewSignals
    self.updateGraphAndPermList()
  File "C:\Python34\lib\site-packages\Orange\widgets\visualize\owmosaic.py", line 447, in updateGraphAndPermList
    self.updateGraph(**args)
  File "C:\Python34\lib\site-packages\Orange\widgets\visualize\owmosaic.py", line 483, in updateGraph
    data = data[:, attrList + [data.domain.class_var]]
  File "C:\Python34\lib\site-packages\Orange\data\table.py", line 637, in __getitem__
    attributes, col_indices = self.domain._compute_col_indices(col_idx)
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 391, in _compute_col_indices
    attributes = [self[col] for col in col_idx]
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 391, in <listcomp>
    attributes = [self[col] for col in col_idx]
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 213, in __getitem__
    idx = self._indices[idx]
KeyError: 'Feature 9'
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 690, in process_signals_for_widget
    widget.handleNewSignals()
  File "C:\Python34\lib\site-packages\Orange\widgets\visualize\owmosaic.py", line 396, in handleNewSignals
    self.updateGraphAndPermList()
  File "C:\Python34\lib\site-packages\Orange\widgets\visualize\owmosaic.py", line 447, in updateGraphAndPermList
    self.updateGraph(**args)
  File "C:\Python34\lib\site-packages\Orange\widgets\visualize\owmosaic.py", line 483, in updateGraph
    data = data[:, attrList + [data.domain.class_var]]
  File "C:\Python34\lib\site-packages\Orange\data\table.py", line 637, in __getitem__
    attributes, col_indices = self.domain._compute_col_indices(col_idx)
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 391, in _compute_col_indices
    attributes = [self[col] for col in col_idx]
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 391, in <listcomp>
    attributes = [self[col] for col in col_idx]
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 213, in __getitem__
    idx = self._indices[idx]
KeyError: 'Feature 9'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "C:\Python34\lib\logging\__init__.py", line 980, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\lib\site-packages\Orange\canvas\__main__.py", line 403, in <module>
    sys.exit(main())
  File "C:\Python34\lib\site-packages\Orange\canvas\__main__.py", line 386, in main
    status = app.exec_()
  File "C:\Python34\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 714, in event
    return SignalManager.event(self, event)
  File "C:\Python34\lib\site-packages\Orange\canvas\scheme\signalmanager.py", line 452, in event
    self.process_queued(max_nodes=1)
  File "C:\Python34\lib\site-packages\Orange\canvas\scheme\signalmanager.py", line 316, in process_queued
    self.process_node(node)
  File "C:\Python34\lib\site-packages\Orange\canvas\scheme\signalmanager.py", line 335, in process_node
    self.send_to_node(node, signals_in)
  File "C:\Python34\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 632, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "C:\Python34\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 694, in process_signals_for_widget
    node.title)
Message: "Error calling 'handleNewSignals()' of '%s'"
Arguments: ('Mosaic Display',)
--------------------------------------------------------------------------------
KeyError                                      Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\Orange\widgets\visualize\owmosaic.py", line 321, in resizeEvent
    self.updateGraph()
  File "C:\Python34\lib\site-packages\Orange\widgets\visualize\owmosaic.py", line 483, in updateGraph
    data = data[:, attrList + [data.domain.class_var]]
  File "C:\Python34\lib\site-packages\Orange\data\table.py", line 637, in __getitem__
    attributes, col_indices = self.domain._compute_col_indices(col_idx)
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 391, in _compute_col_indices
    attributes = [self[col] for col in col_idx]
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 391, in <listcomp>
    attributes = [self[col] for col in col_idx]
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 213, in __getitem__
    idx = self._indices[idx]
KeyError: 'Feature 9'
--------------------------------------------------------------------------------
KeyError                                      Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\Orange\widgets\visualize\owmosaic.py", line 325, in showEvent
    self.updateGraph()
  File "C:\Python34\lib\site-packages\Orange\widgets\visualize\owmosaic.py", line 483, in updateGraph
    data = data[:, attrList + [data.domain.class_var]]
  File "C:\Python34\lib\site-packages\Orange\data\table.py", line 637, in __getitem__
    attributes, col_indices = self.domain._compute_col_indices(col_idx)
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 391, in _compute_col_indices
    attributes = [self[col] for col in col_idx]
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 391, in <listcomp>
    attributes = [self[col] for col in col_idx]
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 213, in __getitem__
    idx = self._indices[idx]
KeyError: 'Feature 9'
--------------------------------------------------------------------------------
KeyError                                      Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\Orange\widgets\gui.py", line 2550, in __call__
    self.f(**kwds)
  File "C:\Python34\lib\site-packages\Orange\widgets\visualize\owmosaic.py", line 447, in updateGraphAndPermList
    self.updateGraph(**args)
  File "C:\Python34\lib\site-packages\Orange\widgets\visualize\owmosaic.py", line 483, in updateGraph
    data = data[:, attrList + [data.domain.class_var]]
  File "C:\Python34\lib\site-packages\Orange\data\table.py", line 637, in __getitem__
    attributes, col_indices = self.domain._compute_col_indices(col_idx)
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 391, in _compute_col_indices
    attributes = [self[col] for col in col_idx]
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 391, in <listcomp>
    attributes = [self[col] for col in col_idx]
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 213, in __getitem__
    idx = self._indices[idx]
KeyError: 'Feature 9'
```

He follows up with:

> Right it seems to me that it was a remainder of one of my earlier attempts to draw a mosaic plot, but I would expect the variables to be wiped out. Thus, I was trying to reproduce yesterday's problem but at the point I was trying to connect a Data Table to the File widget, Orange was freezing. I am gladly sharing with you another `.tab` file I have and the respective OWS workflow, that exhibit the same issue. I have renamed both to `.txt` because I couldn't upload otherwise
[edutemp2.tab.txt](https://github.com/biolab/orange/files/36523/edutemp2.tab.txt)
[untitled.ows.txt](https://github.com/biolab/orange/files/36525/untitled.ows.txt)

**Comment by kernc** [comment] 2015-11-17 13:18
Thanks, I was able to reproduce by clicking Apply in Select columns widget.

The problem seems to be that [`openContext()` call](https://github.com/biolab/orange3/blob/84dfffb0fed9f1ee3b6f5bdbca63a98bd3125a24/Orange/widgets/visualize/owmosaic.py#L371) restores `self.variable1` to `'Feature 9'`. @astaric, any ideas?

**Comment by kernc** [comment] 2015-11-17 14:49
> Thus, I was trying to reproduce yesterday's problem but at the point I was trying to connect a Data Table to the File widget, Orange was freezing.

Can you also please open a new issue for this behavior, if you can reproduce it, and possibly attach the relevant files? Freezing for more than a moment should not happen, obviously. :smiley:

**Comment by kernc** [comment] 2015-11-17 14:49
> Thus, I was trying to reproduce yesterday's problem but at the point I was trying to connect a Data Table to the File widget, Orange was freezing.

@ypanagis Can you also please open a new issue for this behavior, if you can reproduce it, and possibly attach the relevant files? Freezing for more than a moment should not happen, obviously. :smiley:

**Comment by ypanagis** [comment] 2015-11-17 15:38
This isn't happening in Orange 2.7 though! :) Thanks for following up on the issue

**Comment by ajdapretnar** [comment] 2016-04-25 07:18
@kernc @astaric @janezd A stale issue that still needs fixing. I'm getting the error even with the updated master.

**Comment by janezd** [comment] 2016-06-23 20:33
I can reproduce this bug if I load the schema attached to the report. If I instead construct this exact same schema myself, I get no error.

Also, if I load the schema and the re-select the same attributes in Mosaic, the Mosaic shows without an error. If I then save schema and load it again, it gives no errors.

I assume the schema contains corrupt context settings. I see no way of reproducing the events that led to this schema. Settings have been refactored a lot, so let us hope the bug disappeared. I suggest closing this issue. @kernc, @ajdapretnar, @astaric?

**Comment by ajdapretnar** [comment] 2016-06-24 08:28
@janezd Agree. I get no issue as well with that exact data set. Since we can't reproduce (and a lot of fixes have already been done since), I'm closing the issue.
If the problem remains, @ypanagis you can open another issue.

**Closed by ajdapretnar** 2016-06-24 08:28 UTC
