### ISSUE TITLE
PyQt4.QtCore persistently called

### ISSUE THREAD

**Issue by striatum** [biolab/orange3#2475] opened 2017-07-14 16:12 UTC
##### Orange version

orange3                   3.4.1

Current conda install:

               platform : osx-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Library/Frameworks/Python.framework/Versions/anaconda  (writable)
    default environment : /Library/Frameworks/Python.framework/Versions/anaconda
       envs directories : /Library/Frameworks/Python.framework/Versions/anaconda/envs
                          /Users/petar/.conda/envs
          package cache : /Library/Frameworks/Python.framework/Versions/anaconda/pkgs
                          /Users/petar/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/petar/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/3.6.1 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 501:20

##### Actual behavior

orange3 issues en error message repeatedly:

     SystemError: unable to find to find module: PyQt4.QtCore

despite the fact that I've followed instruction:

     export QT_API=pyqt5

Previously, I've also installed:

     qt-opensource-mac-x64-5.9.1.dmg
     pip install SIP
     pip install pyqt5

##### Steps to reproduce the behavior

This happens every time when application is launched.

**Comment by striatum** [comment] 2017-08-18 19:08
Still not fix???

**Comment by ajdapretnar** [comment] 2018-10-05 08:20
@astaric @lanzagar Is this not already solved?

**Comment by lanzagar** [comment] 2018-10-05 09:05
It should be. Is anyone still able to actually reproduce this error or did the issue just remain open by accident (I can't reproduce)?

**Comment by ajdapretnar** [comment] 2018-10-05 10:14
I think it is probably open by accident. I will close it. If the issue remains, please reopen.

**Closed by ajdapretnar** 2018-10-05 10:14 UTC
