### ISSUE TITLE
Distributions: illegible x-axis labels

### ISSUE THREAD

**Issue by iva-c** [biolab/orange3#3793] opened 2019-05-10 11:47 UTC
Labels on x-axis overlap or are blurred.
![chrX_distribution](https://user-images.githubusercontent.com/48483052/57524649-b8edf780-7328-11e9-9e16-a08b9c06069f.png)

**Comment by janezd** [comment] 2019-05-10 13:32
Duplicate of #3736.

**Closed by janezd** 2019-05-10 13:32 UTC
