### ISSUE TITLE
Metrics calculation in Prediction widget is possibly wrong.

### ISSUE THREAD

**Issue by mkosovic1981** [biolab/orange3#4704] opened 2020-04-25 22:07 UTC
Hi!

It seems that the calculation of the metrics (Precision, Recall ...) obtained by Prediction widget is wrong. 
I am sending you .ows file where I used iris data set and KNN model.

Regards,
Marin

[KNN-iris_bug.zip](https://github.com/biolab/orange3/files/4534178/KNN-iris_bug.zip)

![CM](https://user-images.githubusercontent.com/60138769/80291839-4486b100-8751-11ea-8e58-172908dcb2f2.JPG)
![metrics](https://user-images.githubusercontent.com/60138769/80291840-45b7de00-8751-11ea-8952-ca412484e9dd.JPG)

**Comment by janezd** [comment] 2020-04-25 22:09
Which Orange version is this?

**Comment by mkosovic1981** [comment] 2020-04-25 22:37
Sorry, I forgot to place the version.
It is 3.23.1

**Comment by janezd** [comment] 2020-04-26 07:46
Thanks. Unless I'm mistaken, this is a duplicate of #4029, which has been fixed in 3.24. Please update and report back.

**Comment by mkosovic1981** [comment] 2020-04-26 09:46
It works perfectly with the  latest version 3.25.0

The thing is that Anaconda by default does not update Orange3 to the latest version, but the maximum version that can be obtained is 3.23.1 Why is that?

**Comment by janezd** [comment] 2020-04-29 21:06
The latest version of Orange is available only on channel conda-forge. See https://orange.biolab.si/blog/2020/2020-02-24-anaconda-navigator/.

**Closed by janezd** 2020-04-29 21:06 UTC
Labels: bug report
