### ISSUE TITLE
3d visualizations in Orange3

### ISSUE THREAD

**Issue by mjolly** [biolab/orange3#5552] opened 2021-08-16 21:36 UTC
Hi:
Does orange3 have 3d visualizations such as ScatterPlot3D, LinProj3D and Sphereviz3D, as mentioned in this [link] ?(https://orangedatamining.com/blog/2011/09/07/3d-visualizations-in-orange/). 
The technical project page for above visualizations under Orange3 leads to a dead [link.](https://matejd.github.com/)

I am aware of FreeViz(multivariate projection) tool, however that has a limit on the amount of data input to it. I tried inputting approximately 20000 data points and the tool gave an error related synonymous to - too much data.

Thanks.

**Comment by ajdapretnar** [comment] 2021-08-17 07:05
I am sorry, but there's literally an issue about 3D visualizations opened just 3 places below yours.

The link that you posted in someone's Github page, which he likely removed. This was a student contribution in 2011 and from what I know, it applies to Orange2, not Orange3.

In short, no there aren't 3D visualizations in Orange. With 20,000 data points you will have issues anyway, because Orange is designed for interactivity (selection, coloring, grouping data points) and that doesn't work well for large data sets. You can always try Data Sampler and sample the data.

Closing as a (partial) duplicate of https://github.com/biolab/orange3/issues/5546.

**Closed by ajdapretnar** 2021-08-17 07:05 UTC

**Comment by janezd** [comment] 2021-08-17 07:35
20000 points may work in other visualizations, but Freeviz computes pairwise distances between all points at each step and I suppose this would be too much for it.

**Comment by borondics** [comment] 2021-08-17 07:43
Would automatic downsampling of large datasets be an option? Maybe one
can't distinguish between 2000 and 20000 data points anyway. We do
something similar in Spectroscopy widgets - if there are too many spectra,
we simply show a random set of 1000. I am adding this because I also think
that 3D visualizations could be very useful sometimes.

**Comment by ajdapretnar** [comment] 2021-08-17 07:44
I agree 3D visualizations would be useful, but there's already a nice thread about it in #5546.
