### ISSUE TITLE
GEO Data Sets: no data

### ISSUE THREAD

**Issue by wfdoran** [biolab/orange3#4943] opened 2020-08-13 23:15 UTC
Orange version 3.26.0
Windows 10

When I open the GEO Data Sets widget, there are no datasets listed.  The Info box in the upper left says 4167 datasets, 0 datasets cached, 0 after filtering.  But there is no filter listed.  I also tried filters which should work and didn't get any hits.
![GEODataSets](https://user-images.githubusercontent.com/21267484/90196226-24224700-dd80-11ea-9859-35fb6e119285.png)

**Comment by ajdapretnar** [comment] 2020-08-14 07:30
Fixed in https://github.com/biolab/orange3-bioinformatics/pull/241. Duplicate of https://github.com/biolab/orange3-bioinformatics/issues/239.

Bioinformatics needs to be released.

**Closed by ajdapretnar** 2020-08-14 07:30 UTC
Labels: bug report
