### ISSUE TITLE
geo widget is not installing on windows 7

### ISSUE THREAD

**Issue by vishal18021987** [biolab/orange3#2746] opened 2017-11-06 12:23 UTC
Collecting Orange3-Geo
  Using cached Orange3-Geo-0.2.0.tar.gz
Requirement already satisfied: Orange3 in c:\program files\orange\lib\site-packages (from Orange3-Geo)
Requirement already satisfied: scikit-learn in c:\program files\orange\lib\site-packages (from Orange3-Geo)
Collecting pandas (from Orange3-Geo)
  Using cached pandas-0.21.0.tar.gz
Collecting scipy>=0.17 (from Orange3-Geo)
  Using cached scipy-1.0.0-cp34-none-win32.whl
Collecting shapely (from Orange3-Geo)
  Using cached Shapely-1.6.2.post1.tar.gz
   Complete output from command python setup.py egg_info:
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\vishal\AppData\Local\Temp\pip-build-cn9hjiso\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\vishal\AppData\Local\Temp\pip-build-cn9hjiso\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Python34\lib\ctypes\__init__.py", line 351, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\vishal\AppData\Local\Temp\pip-build-cn9hjiso\shapely\

**Comment by kernc** [comment] 2017-11-06 12:43
Duplicate of https://github.com/biolab/orange3-geo/issues/12.

**Closed by kernc** 2017-11-06 12:43 UTC
