### ISSUE TITLE
cannot build windows application!!

### ISSUE THREAD

**Issue by anilkodepaka** [biolab/orange3#1721] opened 2016-11-04 13:26 UTC
I'm trying to publish Orange on windows platform.

Windows + Conda (Anaconda installation)

Application installation worked without issues:

PS C:\Users\Desktop\ORANGE\orange3> pip install -e .
Obtaining file:///C:/Users/Desktop/ORANGE/orange3
Requirement already satisfied: AnyQt>=0.0.6 in c:\program files (x86)\anaconda3\lib\site-packages (from Orange3==3.3.9.dev0+unknown)
Requirement already satisfied: bottleneck>=1.0.0 in c:\program files (x86)\anaconda3\lib\site-packages (from Orange3==3.3.9.dev0+unknown)
Requirement already satisfied: chardet>=2.3.0 in c:\program files (x86)\anaconda3\lib\site-packages (from Orange3==3.3.9.dev0+unknown)
Requirement already satisfied: docutils in c:\program files (x86)\anaconda3\lib\site-packages (from Orange3==3.3.9.dev0+unknown)
Requirement already satisfied: joblib>=0.9.4 in c:\program files (x86)\anaconda3\lib\site-packages (from Orange3==3.3.9.dev0+unknown)
Requirement already satisfied: keyring in c:\program files (x86)\anaconda3\lib\site-packages (from Orange3==3.3.9.dev0+unknown)
Requirement already satisfied: keyrings.alt in c:\program files (x86)\anaconda3\lib\site-packages (from Orange3==3.3.9.dev0+unknown)
Requirement already satisfied: numpy>=1.9.0 in c:\program files (x86)\anaconda3\lib\site-packages (from Orange3==3.3.9.dev0+unknown)
Requirement already satisfied: pyqtgraph>=0.9.10 in c:\program files (x86)\anaconda3\lib\site-packages (from Orange3==3.3.9.dev0+unknown)
Requirement already satisfied: scikit-learn>=0.18 in c:\program files (x86)\anaconda3\lib\site-packages (from Orange3==3.3.9.dev0+unknown)
Requirement already satisfied: scipy>=0.11.0 in c:\program files (x86)\anaconda3\lib\site-packages (from Orange3==3.3.9.dev0+unknown)
Requirement already satisfied: xlrd>=0.9.2 in c:\program files (x86)\anaconda3\lib\site-packages (from Orange3==3.3.9.dev0+unknown)
Requirement already satisfied: pywin32-ctypes; sys_platform == "win32" in c:\program files (x86)\anaconda3\lib\site-packages (from keyring->Orange3==3.3.9.dev0+unknown)
Installing collected packages: Orange3
  Found existing installation: Orange3 3.3.8
    Uninstalling Orange3-3.3.8:
      Successfully uninstalled Orange3-3.3.8
  Running setup.py develop for Orange3
Successfully installed Orange3
PS C:\Users\Desktop\ORANGE\orange3>

However for the windows dev setup, i'm stuck with this numpy errors again:

PS C:\Users\Desktop\ORANGE\orange3> python setup.py build_ext --inplace --compile=mingw32
C:\Program Files (x86)\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\setuptools\dist.py:331: UserWarning: Normalizing '3.3.9.dev0+Unknown' to '3.3.9.dev0+unknown'
running build_ext
running build_src
build_src
building extension "Orange.classification._simple_tree" sources
building extension "Orange.classification._tree_scorers" sources
building extension "Orange.data._valuecount" sources
building extension "Orange.data._contingency" sources
building extension "Orange.data._io" sources
building extension "Orange.data._variable" sources
building extension "Orange.preprocess._discretize" sources
building extension "Orange.preprocess._relieff" sources
building extension "Orange.widgets.utils._grid_density" sources
build_src: building npy-pkg config files
Traceback (most recent call last):
  File "setup.py", line 277, in <module>
    setup_package()
  File "setup.py", line 273, in setup_package
    **extra_args
  File "C:\Program Files (x86)\Anaconda3\lib\site-packages\numpy\distutils\core.py", line 169, in setup
    return old_setup(**new_attr)
  File "C:\Program Files (x86)\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files (x86)\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Program Files (x86)\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Program Files (x86)\Anaconda3\lib\site-packages\numpy\distutils\command\build_ext.py", line 117, in run
    force=self.force)
  File "C:\Program Files (x86)\Anaconda3\lib\site-packages\numpy\distutils\ccompiler.py", line 597, in new_compiler
    compiler = klass(None, dry_run, force)
  File "C:\Program Files (x86)\Anaconda3\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 58, in __init__
    dry_run, force)
  File "C:\Program Files (x86)\Anaconda3\lib\distutils\cygwinccompiler.py", line 126, in __init__
    if self.ld_version >= "2.10.90":
TypeError: unorderable types: NoneType() >= str()

Does it look familiar to anyone? Thank you.

**Comment by ajdapretnar** [comment] 2016-11-08 09:05
Duplicate of #1732.

**Closed by ajdapretnar** 2016-11-08 09:05 UTC
