### ISSUE TITLE
Reload should leave roles as is

### ISSUE THREAD

**Issue by simon1tan** [biolab/orange3#3286] opened 2018-10-05 02:09 UTC
In the File widget, clicking on the Reload button causes the Role column to reset or be re-evaluated.  It takes time to make those changes and to have it all reset is no fun. Perhaps mark which ones have been changed by user and only evaluate any new columns.

##### Orange version
3.16.0

##### Expected behavior
Data is reloaded., roles remain unchanged because the user already made their selections

##### Actual behavior
All roles are reset

##### Steps to reproduce the behavior
Create File widget, select a file, modify the role. Then modify file, click reload.

**Comment by rokgomiscek** [comment] 2019-01-11 13:32
Can't reproduce. Probably fixed in #3231 .

**Closed by rokgomiscek** 2019-01-11 13:32 UTC
