### ISSUE TITLE
Problem with miniconda installer

### ISSUE THREAD

**Issue by andersonh-uta** [biolab/orange3#2862] opened 2018-01-11 17:02 UTC
##### Orange version
Orange 3.8.0 Miniconda 64-bit, Windows 10 and Windows 7 Enterprise Edition.

##### Expected behavior
Program should install normally, giving me a Start menu shortcut and so on.

##### Actual behavior
Installer fails partway through, and Orange does not install.

Installer gets through the "Installing Packages" phase, then always fails with the error: 
```
"conda" command exited with 1.  Cannot continue.
```
No further details are given in the installer.  When I scroll back through the messages in the installer window, I also see the following message: 
```
Executing cmd.exe /c install.bat "C:\Orange" "C:\miniconda3\Scripts\conda.exe"
The system cannot find the path specified.
Creating a conda env in "C:\Orange"
```

(note that the above message occurs even when using default install locations, or custom locations other than directly in C:\)  The installer then fails and does not continue, with Orange not successfully installing.

##### Steps to reproduce the behavior
Attempt to install Orange with the 64-bit Miniconda installer on my Windows 10 desktop or Windows 7 laptop.  The above errors occur every time.

_Addendum:_ The machines I am installing on are managed by my company's IT department, with fairly aggressive security settings enabled; I do not have the ability to disable these.  I run into similar issues installing just plain-old Miniconda and full-blown Anaconda (i.e. silently failing installs).  I suspect these security settings may be the root cause.

##### Additional info (worksheets, data, screenshots, ...)
Some places around the internet seem to say that Anaconda will frequently conflict with antivirus software and silently fail parts of the installation.  Given that the machine I'm working from has a company-managed antivirus that I cannot disable, even temporarily, this would make Anaconda and Orange (via miniconda) seemingly uninstallable with no recourse.  I'm having difficulty confirming that this is indeed what's happening, though.

Installing through `pip` with `pip install orange3 pyqt5` lets me run the `orange-canvas` command and launch it as normal, with all functionality as expected.  However, this does not get me a start menu launcher, which I have to create manually.  This is not much of a hassle for me, but I am trying to show Orange to colleagues and students who are less technically savvy and likely have no real experience in command line environments, and for whom these fidgety (by comparison to a simple point-and-click installer) steps might be a barrier if this issue occurs for them.

**Comment by astaric** [comment] 2018-01-24 13:35
I was not able to reproduce the error, but I have a (potential) workaround for you.

You can try "the old installer" and see if that works. We decided to stop promoting it as many add-ons depend on libraries that do not have windows binaries available and are therefore impossible to install (conda installer works as we can contribute conda recipes for those packages).

https://orange.biolab.si/download/files/Orange3-3.8.0-Python36-win_amd64.exe

You can see all built installers by navigating to https://orange.biolab.si/download/files/.

**Comment by andersonh-uta** [comment] 2018-01-24 15:02
Thanks for that link!  I suspect the original issue is due some of the security settings enforced by my IT department, but I don't have the ability to change those.  Per some of the Googling I did about Anaconda/Miniconda, it seems like aggressive firewall/antivirus settings can sometimes cause installs to silently fail (I had such an issue with regularly installing Anaconda/Miniconda--I edited my original post to reflect this).  Since posting that I was able to get the miniconda installer to work on other (personal) machines without issue, so the problem is almost certainly on my end.

The non-miniconda installer seems to have worked without issue on the original machines.  I'll put it through its paces a bit and see if/where I run into problems doing a clean install.

**Comment by astaric** [comment] 2018-03-04 20:08
If the Miniconda/Anaconda installation fails when combined with string antivirus/security policies, there is not much we can do (beside not using them). Classic and standalone installers are still built automatically for each release and we might consider putting a link back to the download page if there will be many reports like this one. For now, you can get any of the installers at the link in my first comment.

I am closing the issue, but if there is new information (such as a future version of miniconda installer reliably working on your work machine), let us know and we will see what we can do.

**Closed by astaric** 2018-03-04 20:08 UTC

**Comment by wfrsilva** [comment] 2019-09-07 13:40
Executing: cmd.exe /c install.bat "C:\Users\Avell\AppData\Local\Orange" "C:\Users\Avell\Anaconda3\Scripts\conda.exe"
"conda" command exited with 1. Cannot continue.
