### ISSUE TITLE
Windows installation: Can't overwrite Orange

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4133] opened 2019-10-23 10:23 UTC
**Describe the bug**
Windows installer cannot overwrite existing Orange installation.

**To Reproduce**
1. Have an older version of Orange installed on Win machine. Say 3.22.
2. Try to install version 3.23.1 over it.

**Expected behavior**
Orange used to overwrite existing installation. Now it doesn't.

**Operating system:**
Windows.

**Additional context**
Error:
"C:\Users\user\AppData\Local\Orange" contains a pre-existing environment that is not binary compatible with this installer. Please choose another destination folder.

**Comment by ajdapretnar** [comment] 2019-10-23 10:25
Same as in: https://github.com/Quasars/quasar/issues/2
and https://www.gitmemory.com/issue/biolab/orange3/3619/482569382

Apparently, the new installation comes with Python 3.7 which cannot overwrite a Python 3.6 environment. So annoying.

**Comment by markotoplak** [comment] 2019-10-23 13:35
Duplicate of #3830

**Closed by markotoplak** 2019-10-23 13:35 UTC
Labels: bug
