### ISSUE TITLE
run ows from command line without gui

### ISSUE THREAD

**Issue by huangkai31** [biolab/orange3#3874] opened 2019-06-12 09:17 UTC
##### Orange version
3.21.0

##### Expected behavior
after using orange-canvas save the workflow to a file like analysis.ows , can run it without opening the GUI
something like this:

orange-canvas --no-gui analysis.ows 

##### Actual behavior
It will always open GUI

**Comment by ajdapretnar** [comment] 2019-06-12 09:31
Essentially a duplicate of https://github.com/biolab/orange3/issues/2525 (includes explanation of why this is a wontfix).

Running workflows without GUI is not expected behavior. Orange is designed as an interactive exploration tool. For running scheduled workflows please use Python scripts.

**Closed by ajdapretnar** 2019-06-12 09:31 UTC
