### ISSUE TITLE
OWSave: 3.16 crashes on None input

### ISSUE THREAD

**Issue by stuart-cls** [biolab/orange3#3302] opened 2018-10-09 16:56 UTC
##### Orange version
3.16.0 (git revision: 4cfa80c)

##### Expected behavior
OWSave handles None table on input.

##### Actual behavior
OWSave crashes when receiving None input. This didn't happen on previous versions.

```

Exception:
AttributeError: 'NoneType' object has no attribute 'is_sparse'
Module:
Orange.widgets.data.owsave:136
Widget Name:
Save Data
Widget Module:
Orange.widgets.data.owsave:136
Version:
3.16.0
Environment:
Python 3.6.4 on Windows 10 10.0.16299 AMD64
Installed Packages:
AnyQt==0.0.8, Bottleneck==1.2.1, CommonMark==0.7.4, Orange-Spectroscopy-Prototypes==0.1.0, Orange-Spectroscopy==0.3.7, Orange3==3.16.0, PySocks==1.6.8, asn1crypto==0.24.0, astroid==1.6.4, certifi==2018.1.18, cffi==1.11.5, chardet==3.0.4, colorama==0.3.9, colorcet==0.9.1, cryptography==2.1.4, cycler==0.10.0, decorator==4.3.0, dill==0.2.7.1, docutils==0.14, future==0.16.0, h5py==2.7.1, idna==2.6, isort==4.3.4, joblib==0.11, keyring==9.0, keyrings.alt==1.2, kiwisolver==1.0.1, lazy-object-proxy==1.3.1, matplotlib==2.2.2, mccabe==0.6.1, networkx==2.1, numpy==1.14.2, opusFC==1.1.1, pip==9.0.1, pyOpenSSL==17.5.0, pycparser==2.18, pylint==1.9.1, pyparsing==2.2.2, pyqtgraph==0.10.0, pyreadline==2.1, python-dateutil==2.7.3, python-louvain==0.11, pytz==2018.5, pywin32==221, requests==2.18.4, scikit-learn==0.19.1, scipy==1.0.0, serverfiles==0.2.1, setuptools==38.5.1, six==1.11.0, spectral==0.19, tornado==5.1.1, urllib3==1.22, wheel==0.30.0, win-inet-pton==1.0.1, wincertstore==0.2, wrapt==1.10.11, xlrd==1.1.0
Machine ID:
109952947833691
Stack Trace:
Traceback (most recent call last):
  File "C:\Users\reads\AppData\Local\Continuum\miniconda3\envs\orange-spec-proto\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 1066, in process_signals_for_widget
    handler(*args)
  File "C:\Users\reads\AppData\Local\Continuum\miniconda3\envs\orange-spec-proto\lib\site-packages\Orange\widgets\data\owsave.py", line 136, in dataset
    if self.data.is_sparse():
AttributeError: 'NoneType' object has no attribute 'is_sparse'

Local Variables:
OrderedDict([('data', None),
             ('self',
              <Orange.widgets.data.owsave.OWSave object at 0x0000011BCDCF1A68>)])
```

##### Steps to reproduce the behavior
Put the following code in a Python Script widget, run and connect to Save Data.

```
out_data = None
```

**Comment by markotoplak** [comment] 2018-10-12 08:33
Duplicate of gh-3256

**Closed by markotoplak** 2018-10-12 08:33 UTC
