### ISSUE TITLE
Crash: Application crashes when selecting tutorials

### ISSUE THREAD

**Issue by arunshaji95** [biolab/orange3#3019] opened 2018-04-25 12:31 UTC
##### Orange version
Version: 3.14.0.dev0+5ab31e9
Os: Ubuntu 16.04 LTS
Python: Python 3.5.2 (inside venv)
##### Expected behavior

Application should run the examples.

##### Actual behavior
Application suddenly exits when I click on the I open an Example

##### Steps to reproduce the behavior
1. Open orange by running

> python -m Orange.canvas

2. In the welcome screen, click Examples.
3. Select FILE AND DATATABLE
4. Click open
5. Window exists suddenly

##### Additional info (worksheets, data, screenshots, ...)
Stacktrace
```
Could not find QtWebEngineProcess
[21047:21047:0425/175610.545121:FATAL:zygote_host_impl_linux.cc(182)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid). 
#0 0x7f4752ae20a5 <unknown>
#1 0x7f4752af7eca <unknown>
#2 0x7f475213afc3 <unknown>
#3 0x7f4752139c3b <unknown>
#4 0x7f475213a219 <unknown>
#5 0x7f4751d7d93a <unknown>
#6 0x7f4751d82e76 <unknown>
#7 0x7f47518a0600 <unknown>
#8 0x7f47518a1b25 <unknown>
#9 0x7f4751890ee9 <unknown>
#10 0x7f47518910be QtWebEngineCore::WebContentsAdapter::WebContentsAdapter()
#11 0x7f47577e2441 <unknown>
#12 0x7f47577e2f24 QWebEnginePage::QWebEnginePage()
#13 0x7f47577f0ebb QWebEngineView::page()
#14 0x7f4757a173f9 meth_QWebEngineView_page
#15 0x0000004e9b7f PyCFunction_Call
#16 0x0000005372f4 PyEval_EvalFrameEx
#17 0x0000005406df <unknown>
#18 0x00000053bd92 PyEval_EvalFrameEx
#19 0x0000005416ea PyEval_EvalCodeEx
#20 0x0000004ebe37 <unknown>
#21 0x0000005c1797 PyObject_Call
#22 0x00000053920b PyEval_EvalFrameEx
#23 0x0000005416ea PyEval_EvalCodeEx
#24 0x0000004ebe37 <unknown>
#25 0x0000005c1797 PyObject_Call
#26 0x0000004fb9ce <unknown>
#27 0x0000005c1797 PyObject_Call
#28 0x000000574999 <unknown>
#29 0x00000057f03c <unknown>
#30 0x0000005c1797 PyObject_Call
#31 0x00000053bba6 PyEval_EvalFrameEx
#32 0x0000005406df <unknown>
#33 0x00000053c1d0 PyEval_EvalFrameEx
#34 0x0000005416ea PyEval_EvalCodeEx
#35 0x0000004ebd23 <unknown>
#36 0x0000005c1797 PyObject_Call
#37 0x0000004fb9ce <unknown>
#38 0x0000005c1797 PyObject_Call
#39 0x000000574999 <unknown>
#40 0x00000057f03c <unknown>
#41 0x0000005c1797 PyObject_Call
#42 0x00000053bba6 PyEval_EvalFrameEx
#43 0x00000053b7e4 PyEval_EvalFrameEx
#44 0x00000053b7e4 PyEval_EvalFrameEx
#45 0x00000053b7e4 PyEval_EvalFrameEx
#46 0x000000540199 <unknown>
#47 0x00000053c1d0 PyEval_EvalFrameEx
#48 0x0000005416ea PyEval_EvalCodeEx
#49 0x0000004ebd23 <unknown>
#50 0x0000005c1797 PyObject_Call
#51 0x000000534d90 PyEval_CallObjectWithKeywords
#52 0x7f47609a4e15 PyQtSlot::call()
#53 0x7f47609a5320 PyQtSlot::invoke()
#54 0x7f47609a559b PyQtSlotProxy::unislot()
#55 0x7f47609a6377 PyQtSlotProxy::qt_metacall()
#56 0x7f4760323394 QMetaObject::activate()
#57 0x7f47592cf582 QAction::triggered()
#58 0x7f47592d1a80 QAction::activate()
#59 0x7f4759c8ab98 sipQToolButton::nextCheckState()
#60 0x7f47593c7e10 <unknown>
#61 0x7f47593c7f25 QAbstractButton::mouseReleaseEvent()

Received signal 6
#0 0x7f4752ae20a5 <unknown>
#1 0x7f4751823141 <unknown>
#2 0x7f4752ae243d <unknown>
#3 0x7f47725da390 <unknown>
#4 0x7f4772234428 gsignal
#5 0x7f477223602a abort
#6 0x7f4752ae1dc5 <unknown>
#7 0x7f4752af81ed <unknown>
#8 0x7f475213afc3 <unknown>
#9 0x7f4752139c3b <unknown>
#10 0x7f475213a219 <unknown>
#11 0x7f4751d7d93a <unknown>
#12 0x7f4751d82e76 <unknown>
#13 0x7f47518a0600 <unknown>
#14 0x7f47518a1b25 <unknown>
#15 0x7f4751890ee9 <unknown>
#16 0x7f47518910be QtWebEngineCore::WebContentsAdapter::WebContentsAdapter()
#17 0x7f47577e2441 <unknown>
#18 0x7f47577e2f24 QWebEnginePage::QWebEnginePage()
#19 0x7f47577f0ebb QWebEngineView::page()
#20 0x7f4757a173f9 meth_QWebEngineView_page
#21 0x0000004e9b7f PyCFunction_Call
#22 0x0000005372f4 PyEval_EvalFrameEx
#23 0x0000005406df <unknown>
#24 0x00000053bd92 PyEval_EvalFrameEx
#25 0x0000005416ea PyEval_EvalCodeEx
#26 0x0000004ebe37 <unknown>
#27 0x0000005c1797 PyObject_Call
#28 0x00000053920b PyEval_EvalFrameEx
#29 0x0000005416ea PyEval_EvalCodeEx
#30 0x0000004ebe37 <unknown>
#31 0x0000005c1797 PyObject_Call
#32 0x0000004fb9ce <unknown>
#33 0x0000005c1797 PyObject_Call
#34 0x000000574999 <unknown>
#35 0x00000057f03c <unknown>
#36 0x0000005c1797 PyObject_Call
#37 0x00000053bba6 PyEval_EvalFrameEx
#38 0x0000005406df <unknown>
#39 0x00000053c1d0 PyEval_EvalFrameEx
#40 0x0000005416ea PyEval_EvalCodeEx
#41 0x0000004ebd23 <unknown>
#42 0x0000005c1797 PyObject_Call
#43 0x0000004fb9ce <unknown>
#44 0x0000005c1797 PyObject_Call
#45 0x000000574999 <unknown>
#46 0x00000057f03c <unknown>
#47 0x0000005c1797 PyObject_Call
#48 0x00000053bba6 PyEval_EvalFrameEx
#49 0x00000053b7e4 PyEval_EvalFrameEx
#50 0x00000053b7e4 PyEval_EvalFrameEx
#51 0x00000053b7e4 PyEval_EvalFrameEx
#52 0x000000540199 <unknown>
#53 0x00000053c1d0 PyEval_EvalFrameEx
#54 0x0000005416ea PyEval_EvalCodeEx
#55 0x0000004ebd23 <unknown>
#56 0x0000005c1797 PyObject_Call
#57 0x000000534d90 PyEval_CallObjectWithKeywords
#58 0x7f47609a4e15 PyQtSlot::call()
#59 0x7f47609a5320 PyQtSlot::invoke()
#60 0x7f47609a559b PyQtSlotProxy::unislot()
#61 0x7f47609a6377 PyQtSlotProxy::qt_metacall()
  r8: 00007ffe1c542980  r9: 00007f47729eb700 r10: 0000000000000008 r11: 0000000000000202
 r12: 00007ffe1c542750 r13: 00000000000000ac r14: 00007ffe1c542980 r15: 00007ffe1c5430f0
  di: 0000000000005237  si: 0000000000005237  bp: 00007f47631a9140  bx: 00007ffe1c542ed0
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007f4772234428  sp: 00007ffe1c5425e8
  ip: 00007f4772234428 efl: 0000000000000202 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Comment by ajdapretnar** [comment] 2018-06-29 11:17
Duplicate of #3015.

**Closed by ajdapretnar** 2018-06-29 11:17 UTC
