### ISSUE TITLE
'Mismatching target' error

### ISSUE THREAD

**Issue by andy193** [biolab/orange3#2179] opened 2017-03-31 12:54 UTC
##### Orange version
3.4

##### Expected behavior
Classifies test data

##### Actual behavior
'Mismatching target (classification)' error pops up.

##### Additional info (worksheets, data, screenshots, ...)
![image](https://cloud.githubusercontent.com/assets/12152579/24551092/c8d09a12-1629-11e7-8d7d-ea061acf0c3a.png).
As you can see in the picture attached above, the left 'Select columns' is the dataset, the right one is the test data. The classification column in the dataset has 3 values 'low' 'high' and 'medium', but I don't know what to add into the classification column in the test data, since I basically want the program to predict what type it is, how come am I supposed to add values into the classification in the test data? And it's a target variable, therefore the 'Mismatching target' pops up.

**Comment by ajdapretnar** [comment] 2017-03-31 12:56
@andy193 Thank for reporting this! It is a bug in the latest release and we're fixing it as we speak.

Also a duplicate of #2148, so closing this and modifying the title of the first issue.

**Closed by ajdapretnar** 2017-03-31 12:56 UTC
