### ISSUE TITLE
orange-3 network is also not installing on windows-7 the error is

### ISSUE THREAD

**Issue by vishal18021987** [biolab/orange3#2747] opened 2017-11-06 12:37 UTC
Collecting Orange3-Network
  Using cached Orange3-Network-1.2.0.tar.gz
Requirement already satisfied: networkx>=1.10 in c:\program files\orange\lib\site-packages (from Orange3-Network)
Requirement already satisfied: pyqtgraph>=0.9.10 in c:\program files\orange\lib\site-packages (from Orange3-Network)
Requirement already satisfied: decorator>=4.1.0 in c:\program files\orange\lib\site-packages (from networkx>=1.10->Orange3-Network)
Requirement already satisfied: numpy in c:\program files\orange\lib\site-packages (from pyqtgraph>=0.9.10->Orange3-Network)
Installing collected packages: Orange3-Network
  Running setup.py install for Orange3-Network: started
    Running setup.py install for Orange3-Network: finished with status 'error'
    Complete output from command "C:\Program Files\Orange\Scripts\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\vishal\\AppData\\Local\\Temp\\pip-build-pp5iprid\\Orange3-Network\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\vishal\AppData\Local\Temp\pip-lvtklwek-record\install-record.txt --single-version-externally-managed --compile --install-headers "C:\Program Files\Orange\include\site\python3.4\Orange3-Network":
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building extension "orangecontrib.network._fr_layout" sources
    build_src: building npy-pkg config files
    running build_py
    creating build
    creating build\lib.win32-3.4
    creating build\lib.win32-3.4\orangecontrib
    copying orangecontrib\__init__.py -> build\lib.win32-3.4\orangecontrib
    creating build\lib.win32-3.4\orangecontrib\network
    copying orangecontrib\network\community.py -> build\lib.win32-3.4\orangecontrib\network
    copying orangecontrib\network\network.py -> build\lib.win32-3.4\orangecontrib\network
    copying orangecontrib\network\readwrite.py -> build\lib.win32-3.4\orangecontrib\network
    copying orangecontrib\network\setup.py -> build\lib.win32-3.4\orangecontrib\network
    copying orangecontrib\network\__init__.py -> build\lib.win32-3.4\orangecontrib\network
    creating build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\graphview.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\OWNxAnalysis.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\OWNxClustering.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\OWNxExplorer.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\OWNxFile.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\OWNxFromDistances.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\OWNxGenerator.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    copying orangecontrib\network\widgets\__init__.py -> build\lib.win32-3.4\orangecontrib\network\widgets
    creating build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\airtraffic.net -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\airtraffic_items.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\dicty_publication.net -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\dicty_publication_edges.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\dicty_publication_items.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\lastfm.net -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\lastfm.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\lastfm_all.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\lastfm_tags.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\leu_by_genesets.net -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\leu_by_genesets_items.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\leu_by_pmid.net -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\leu_by_pmid_items.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\leu_huttenhower_a.net -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\leu_huttenhower_a_items.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\makeNetworkList.py -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\mips_c2_cp_leu.net -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\mips_c2_cp_leu_items.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    copying orangecontrib\network\networks\network_info.tab -> build\lib.win32-3.4\orangecontrib\network\networks
    creating build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\button_autoscale.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\button_rect.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\Category-Network.svg -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\Dlg_clear.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\Dlg_HideSelection.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\Dlg_Mark2Sel.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\Dlg_Sel2Mark.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\Dlg_SelisMark.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\Dlg_UnselectedNodes.png -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\NetworkAnalysis.svg -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\NetworkClustering.svg -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\NetworkExplorer.svg -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\NetworkFile.svg -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\NetworkFromDistances.svg -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    copying orangecontrib\network\widgets\icons\NetworkGenerator.svg -> build\lib.win32-3.4\orangecontrib\network\widgets\icons
    running build_ext
    customize MSVCCompiler
    customize MSVCCompiler using build_ext
    customize MSVCCompiler
    Missing compiler_cxx fix for MSVCCompiler
    customize MSVCCompiler using build_ext
    building 'orangecontrib.network._fr_layout' extension
    compiling C sources
    error: Microsoft Visual C++ 10.0 is required. Get it with "Microsoft Windows SDK 7.1": www.microsoft.com/download/details.aspx?id=8279
    
    ----------------------------------------
Command ""C:\Program Files\Orange\Scripts\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\vishal\\AppData\\Local\\Temp\\pip-build-pp5iprid\\Orange3-Network\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\vishal\AppData\Local\Temp\pip-lvtklwek-record\install-record.txt --single-version-externally-managed --compile --install-headers "C:\Program Files\Orange\include\site\python3.4\Orange3-Network"" failed with error code 1 in C:\Users\vishal\AppData\Local\Temp\pip-build-pp5iprid\Orange3-Network\

**Comment by kernc** [comment] 2017-11-06 12:44
Duplicate of https://github.com/biolab/orange3-network/issues/36.

**Closed by kernc** 2017-11-06 12:44 UTC
