### ISSUE TITLE
Add-on installer reports "no internet connection" when opened first time

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#5734] opened 2021-12-10 16:31 UTC
**What's wrong?**
When selecting Options > Add-ons the first time after opening Orange, it reports "There's ant issue with the internet connection"
When clicking the OK button and electing Options > Add-ons again, it works as expected

**How can we reproduce the problem?** 
Perform the actions described above.

**What's your environment?**
- Operating system: Mac OS 11.6.1 (20G224) on Intel
- Orange version: 3.30.2
- How you installed Orange: from the DMG download.
![screenshot](https://user-images.githubusercontent.com/55989717/145608135-ad31e7cc-6b6c-4923-8723-45dc1381fc02.jpg)

**Comment by markotoplak** [comment] 2021-12-10 16:40
Duplicate of #5695. Interesting that this error is only reported on Macs.

**Closed by markotoplak** 2021-12-10 16:40 UTC
Labels: bug report
