### ISSUE TITLE
Widgets don't retain settings after worksheet reload

### ISSUE THREAD

**Issue by gcatalfamo** [biolab/orange3#1036] opened 2016-02-29 22:33 UTC
Whenever I reopen a workflow I have to to reconfigure every widget (not recreate, just reconfigure) because they get messed up after reload.
It doesn't happen after every single reload but I can't track down what makes it happen.

**Comment by kernc** [comment] 2016-03-01 00:09
What widgets are those?

**Comment by gcatalfamo** [comment] 2016-03-01 08:52
I use mainly data and visualization widgets. The one I am certain the problem is happening are:
- DATA, select rows
- DATA, feature constructor

The widgets seems to reset:
- feature constructor is empty
- select rows offers just one condition (regardless of how many there were before) with the first available option selected

I have used Orange3.2 on mac with several snapshots of the last 2 weeks.

**Comment by kernc** [comment] 2016-03-01 19:20
I can't seem to reproduce. If you open [this worksheet](https://dl.dropboxusercontent.com/u/8775166/untitled.ows), the preferences are cleared?

**Comment by gcatalfamo** [comment] 2016-03-02 10:31
The preference seems to be fine.

I found a way to reproduce it: if you reload a second dataset (that has the same features), widget will reset.

**Comment by ajdapretnar** [comment] 2016-04-13 10:43
@gcatalfamo Could you please let us know if the issue persists with the latest build?

**Comment by kernc** [comment] 2016-04-19 15:47
I made a subset of iris with Select Rows and saved it to iris2.tab. I add another variable in feature constructor and save _that_ as iris3.

When setting File to load iris2, it works. With iris3, it doesn't. Simple replacing of `PerfectDomainContextHandler` with `DomainContextHandler` didn't work, obviously. The domain is just not the same (even if it includes all the relevant variables). @astaric What can we do?

**Comment by astaric** [comment] 2016-04-20 10:50
We can fix it :)

I'll prepare a PR.

**Comment by astaric** [comment] 2016-04-20 15:34
A fix and imperfect matching of domains for FeatureConstructor widget is implemented in #1196. Please see if the second part of the workflow above now works with changing datasets.

I haven't managed to check the Select Rows widget yet.

**Comment by astaric** [comment] 2016-04-21 08:01
After playing around with the Select Rows widget, I could not find any problems. The fact that it does not restore filters for similar datasets is by design, as using it on adult and adult-sample keeps the filters just fine.

If one were to use many different datasets, which share only few of the variables, trying to apply filters from one to the other might not be a wisest choice, as they will be meaningful. If I was observing a group of male germans on one dataset, why would I want to have this as a default filter on a different datasets which contains variables gender and nationality?

If someone can provide a valid use case, I can prepare a PR that replaces PerfectDomainContextHandler with an ordinary DomainContextHandler.

**Comment by ajdapretnar** [comment] 2016-04-21 08:01
@astaric I've tested it and encountered an error. When I loaded iris, then Select Rows (sepal length > 5), Feature Constructor, FC crashed (unexpected EOF). Now for the love of me I cannot replicate it.
Also I saved a subset as iris2.tab with a new variable constructed (call it 'dummy'). When I loaded it in the (original) File widget, Feature Constructor (which was still connected to the File widget) replicated the variable, so now I have two variables called 'dummy'. I personally think that's fine, but I'm just reporting it as a side note.
Feature Constructor now retains settings, Select Rows not (yet).
I'll keep testing it a bit more.

**Comment by gcatalfamo** [comment] 2016-04-21 13:38
The problem with resetting filters is that for a similar/improved/cleaner
dataset I have to rebuild the whole workflow that might consist of several
transformations.
For my specific use case, perhaps too specific, having a workflow that
retains its filters and adapts to different datasets with compatible
features would be useful indeed. :-)

**Comment by janezd** [comment] 2016-04-21 14:10
There may be two reasons for sometimes using `PerfectDomainContextHandler`. Sometimes imperfect matches would not make sense, and sometimes, we're just lazy.

There are just four widgets that use `PerfectDomainContextHandler`. Select Rows, Color, Distance map and Sillhouete plot. The first two don't need perfect matching, but would require specialized handler. Distance Map and Silhouette plot store variable indices instead of names, and this is, afaik, the only reason why they require perfect match.

I think we should fix all four widgets.

**Comment by astaric** [comment] 2016-04-21 14:23
I am considering the idea of using a minimum required match for clone. When set to 0.9, a context would be cloned only when most of the settings in it apply to the new dataset. If a match is below given threshold, a new context would be generated.

This way, we could "clone" setting between similar datasets while still starting with a fresh copy for the datasets that are significantly different than anything seen before.

**Comment by janezd** [comment] 2016-04-21 14:34
I like your simplifications of context handlers. Don't make them great again. :)

I don't think thresholds will work well; 0.9 won't have a general meaning across domains. If we go in this direction, then the widget/handler must decide (`True` or `False`) whether to clone or not.

**Comment by astaric** [comment] 2016-04-21 15:43
Ok, no threshold then :)

I have updated PR with support for clone_context in SelectRows widget. Comments are welcome.

Please do not merge the PR yet, as it requires some refactoring. FeatureConstructor and SelectRows context handlers are almost the same so I will probably probably move shared methods to DomainContextHandler.

**Comment by astaric** [comment] 2016-04-25 08:55
I have refactored the code and updated the PR. I suggest you test it to see if it works the way you expected and report any problems directly on the PR.

**Comment by ajdapretnar** [comment] 2016-05-10 08:13
@gcatalfamo Could you please check if #1196 works and close the issue, if it does? Thanks!

**Closed** 2016-05-10 10:35 UTC
