### ISSUE TITLE
Orange 3: Failed to create D3D Shaders

### ISSUE THREAD

**Issue by Aditya222002** [biolab/orange3#4714] opened 2020-04-30 10:06 UTC
##### Orange version

3.23.1

##### Expected behavior

It should show UI

##### Actual behavior

It shows black screen 

##### Steps to reproduce the behavior

Just Open the software

##### Additional info (worksheets, data, screenshots, ...)

In anaconda command prompt it shows:-
[
![image](https://user-images.githubusercontent.com/64554000/80698595-54f3ae80-8af8-11ea-905e-6e561e67b87f.png)
](url)

And in Ancaconda Navigator it shows:-
Traceback (most recent call last):
File "C:\Users\Lenovo\anaconda3\Scripts\orange-canvas-script.py", line 10, in 
sys.exit(main())
File "C:\Users\Lenovo\anaconda3\lib\site-packages\Orange\canvas\__main__.py", line 572, in main
canvas_window = MainWindow()
File "C:\Users\Lenovo\anaconda3\lib\site-packages\Orange\canvas\mainwindow.py", line 88, in __init__
super().__init__(*args, **kwargs)
File "C:\Users\Lenovo\anaconda3\lib\site-packages\orangewidget\workflow\mainwindow.py", line 54, in __init__
super().__init__(*args, **kwargs)
File "C:\Users\Lenovo\anaconda3\lib\site-packages\orangecanvas\application\canvasmain.py", line 178, in __init__
self.setup_actions()
File "C:\Users\Lenovo\anaconda3\lib\site-packages\orangecanvas\application\canvasmain.py", line 510, in setup_actions
triggered=self._on_recent_scheme_action
TypeError: 'exclusive' is an unknown keyword argument

**Comment by ales-erjavec** [comment] 2020-05-04 12:45
> ... 
> TypeError: 'exclusive' is an unknown keyword argument

You need to either upgrade orange-canvas-core>=0.1.11 or downgrade pyqt5<5.14

**Comment by ajdapretnar** [comment] 2020-05-05 07:33
I think this is a duplicate of #4710?

**Comment by ales-erjavec** [comment] 2020-05-08 09:12
Regarding the 'Failed to create D3D Shaders'; it is probably a directx and/or graphics driver issue: https://stackoverflow.com/questions/48523078/spyder-in-anaconda-failed-to-create-d3d-shaders/52923196

**Closed** 2020-05-08 09:14 UTC
