### ISSUE TITLE
Orange Save and load model widget

### ISSUE THREAD

**Issue by yogesh030893** [biolab/orange3#3949] opened 2019-07-29 22:08 UTC
##### Orange version
Orange version - 3.22.0

##### Expected behavior
I am using orange, to save the model trained on orange canvas to a pickle file using the save model widget. The model gives the correct predictions when loading the test and train data during the model development. But when I save the model using the save model widget in pickle file and use it on a new canvas using load model widget, it gives the wrong output. Basically it only gives out one class for all the test data passed for prediction when using load model.

**Comment by ajdapretnar** [comment] 2019-07-30 07:14
Could you please provide a minimum example?

**Comment by ales-erjavec** [comment] 2019-07-30 08:06
Possibly a duplicate of gh-3521

**Comment by yogesh030893** [comment] 2019-07-30 13:54
Yes the issue posted in gh-3521 is similar with what I am facing. But I didn't get anything where it shows the issue is resolved. Can anyone direct me to the right post or link.

**Comment by ajdapretnar** [comment] 2019-07-31 07:38
It is not resolved yet, unfortunately. 😞 We will discuss this at Friday's meeting.

**Comment by yogesh030893** [comment] 2019-08-09 21:16
I am writing a python script so that the pickle file generated by the orange save data widget is used in the python script. 
So can anyone tell me how to convert a pandas data frame into orange data table so that it can be consumed in the pickle file in the same format as  it does in orange?

**Comment by janezd** [comment] 2019-08-30 18:07
You need to construct an ordinary numpy array and a corresponding [Domain](https://docs.biolab.si//3/data-mining-library/reference/data.domain.html), and pass them to [Orange.data.Table.from_numpy](https://docs.biolab.si//3/data-mining-library/reference/data.table.html#Orange.data.Table.from_numpy).

**Closed by janezd** 2019-08-30 18:07 UTC
Labels: friday
