### ISSUE TITLE
In OWWidget button clicked event gets triggered on enter key pressed.

### ISSUE THREAD

**Issue by zidarsk8** [biolab/orange3#1156] opened 2016-04-04 13:59 UTC
##### Orange version

3.3.2.dev0+e62ff25

##### Expected bahavior

When creating a widget with Orange.widgets.widget.OWWidget, I would expect my events to work the same as with QtGui.QWidget, but it seems there are a few differences with keypress events.
##### Actual behavior

Return Key press triggers click event on the first button that has autoDefault=True.
The weird part is that this behaviour is different if we are runnig the tests.
##### Steps to reproduce the behavior

save the follwing gist as test.py https://gist.github.com/zidarsk8/37c083275efea339b77c69d79915fda5

``` sh
# run tests and check the output
python -m unittest test.TestMVP

# run the app and do the same steps:
# - focus on text field and press enter
# - focus on okay and press enter
# - focus on other and press enter
# - focus on not Okay ond press enter
python test.py
# see that results differ from the tests
```

Issue That I have are: 
- I can't rely on my tests.
- The workaround is to make sure all button in my widget have `autoDefault=False` but then they can't be triggered with the keyboard.
##### Additional info (worksheets, data, screenshots, ...)

If we replace OWWidget with QtGui.QWidget, everything works as expected.

**Comment by kernc** [comment] 2016-04-04 16:28
The problem is likely in `OWWidget.keyPressEvent()`. @janezd / @astaric, Perhaps lead the way to eventual purging of it and `OWWidget.defaultKeyActions` in favor of something short, like:
```py
closed = QShortcut(QKeySequence(QKeySequence.Close), widget)
closed.activated.connect(widget.window().close)
```

**Comment by ales-erjavec** [comment] 2016-04-04 16:33
This behavior is inherited from [QDialog](http://doc.qt.io/qt-4.8/qdialog.html#default-button).

**Comment by zidarsk8** [comment] 2016-04-04 18:24
@ales-erjavec So that is expected behaviour, but does ti make sense? or is there a nice way for me to disable the default button on return key pressed?

**Comment by kernc** [comment] 2016-04-04 18:56
Working with generic widgets here, couldn't we extend QWindow instead? What good does QDialog give us besides Esc key closing it?

**Comment by ales-erjavec** [comment] 2016-04-05 07:07
> What good does QDialog give us besides Esc key closing it?

I think it also provides a size grip, but that's about it.

**Comment by kernc** [comment] 2016-04-12 14:51
We can't extend QMainWindow as that requires a `centralWidget` which makes widget's `self` no longer the widget the author can play with but the sole window instance.

Since [QDialog only handles Enter/Return keys](https://github.com/qtproject/qtbase/blob/3f41e8a2f51698d690a6b1f6a1f4acfe13ff50af/src/widgets/dialogs/qdialog.cpp#L635) somewhat as it documents, we can safely prevent calling `super().keyPressEvent()` for these keys, relying on appropriate signals being connected to explicitly?

**Comment by zidarsk8** [comment] 2016-05-20 13:50
@kernc Preventing `keyPressEvent()` works great for me. But I'm not sure if you guys want this in the `OWWidget` or not. If you want this I can make a PR with the code below, or you guys can add that. Or if you don't think this is needed, feel free to close this issue.

```python                                 
    def keyPressEvent(self, event):                                             
        """Capture and ignore all key press events.                                   
                                                                                
        This is used so that return key event does not trigger the exit button  
        from the dialog. We need to allow the return key to be used in filters  
        in the widget."""                                                       
        pass
```

**Comment by ajdapretnar** [comment] 2016-07-28 10:35
@kernc @zidarsk8 @ales-erjavec  Fix or close?

**Comment by ajdapretnar** [comment] 2016-07-28 18:53
I apologize, sir, for reminding you of the existence of an issue raised in **April** and not touched since **May**. Shall not happen again........

**Comment by astaric** [comment] 2016-12-12 08:52
If I add widget.show() to the attached test.py, the test behaves the same as when I do the modification on the widget manually.

If this problem reoccurs, we can solve it by adding widget.show() to the create_widget method in WidgetTest baseclass.

**Closed by astaric** 2016-12-12 08:52 UTC

**Comment by kernc** [comment] 2016-12-13 00:15
IIUC, your workaround only pertains to this part of the issue report?

> The weird part is that this behaviour is different if we are running the tests.

The real issue, as I understand it, is that when the input field is focused (in the demo) and Enter is pressed, _Okay_ and _Not Okay_ buttons both fire.

**Comment by astaric** [comment] 2016-12-13 09:46
As stated before, this behaviour is inherited from QDialog, which is by design. If the mentioned behaviour is not desired, a specific widget can implement the workaround mentioned above (doing nothing in the keypress event).

As none of the widgets in the core Orange ignores key events (this has not been a problem before, nor since), I suggest that the default behaviour remains as-is, and this issues stays closed as wont-fix.
