### ISSUE TITLE
Installing Orange3 3.22 on a 32 bit windows 7 system

### ISSUE THREAD

**Issue by Norsusan** [biolab/orange3#3984] opened 2019-08-23 15:25 UTC
Orange3 3.22.0 installation work around for Windows 7 32 bit
Install Orange 3 3.21 using Orange3-3.21.0-Python36-win32.whl
1.	Install Python & Orange3 3.21 “Just For Me”, Check “Install launcher for all users”, “Install Now”
2.	Installation of Python36-32 will be successful. If there is an error installing Orange, remove Orange folder only from C:\Users\name\AppData\Local
3.	Go to Start, right click  Computer,  Properties,  Advanced System Settings, Environment Variables, User Variables enter Path= C:\Users \ name\AppData\Local\Programs\Python\Python36-32; C:\Users \ name\AppData\Local\Programs\Python\Python36-32\Scripts
If there was an error installing Orange, retry install Orange3 using Orange3-3.21.0-Python36-win32.whl.

At Command Prompt:
Pip install pyqt5 pyqtwebengine
Pip install –U setuptools
Python –m pip install --upgrade pip
python -m pip install --upgrade Orange3
pip list orange3

Note: Visual Studio required:
https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16
C++Build Tools
MSVC V140  - VS2015 C++ Build Tools (V14.00)

**Comment by Norsusan** [comment] 2019-08-23 20:53
Run Orange3 3.22 at C:\Users\name\AppData\Local\Programs\Python\Python36-32\Scripts\Orange-canvas.exe

**Comment by thocevar** [comment] 2019-09-27 11:38
I've just tried to install the latest Orange 3.23 on a clean install of 32-bit Windows 7 with Python 3.7.4. Installing Visual Studio Built Tools and then installing Orange with pip from the Development Command Prompt worked flawlessly. I don't see where is the problem.

**Comment by thocevar** [comment] 2019-09-27 11:47
I've managed to repeat the same with Python 3.6 and Orange 3.22.

**Comment by Norsusan** [comment] 2019-09-27 15:44
Hello Tomaz,

 

I am running Windows 7 32 bit on a desktop and my laptop.

 

When I try to install  Orange3-3.22.0-Miniconda-x86_64.exe or Orange3-3.23.0-Miniconda-x86_64.exe, the installation software says I have a 32 bit system and need to use a 32 bit version of the installation software. The part of the installation software for 32 bit Python is greyed out and not changeable. I had to use my workaround to update to the latest version of Orange3.

 

Norm

**Comment by thocevar** [comment] 2019-09-30 10:21
Yes, we provide only 64-bit Windows binaries, which fits most users. Everyone else needs to build their own. The easiest way is to obtain Python and C/C++ compiler and install with pip as indicated on the github readme. You took a detour by first installing Orange 3.21, while an installation of Python would suffice.

I'm closing this as it works as intended.

**Closed by thocevar** 2019-09-30 10:21 UTC
