### ISSUE TITLE
Orange Failure to Launch Mac OS

### ISSUE THREAD

**Issue by dsponder** [biolab/orange3#6708] opened 2024-01-18 01:13 UTC
**What's wrong?**
 I've downloaded the recommended Orange file from the website and downloaded it onto my local computer. Whenever I try to open the application, the icon bounces a few times but ultimately doesn't open.
 No error message

**How can we reproduce the problem?** 

 Unsure on how to reproduce. Unfortunately, this isn't a strong suit for me.

**What's your environment?**

- Operating system: Mac OS 11.5.2 Apple M1 chip
- Orange version: Orange3-3.36.2-Python3.9.12-arm64.dmg
- How you installed Orange: Directly from the website, followed the install step (drag it to the application folder)

**Comment by markotoplak** [comment] 2024-01-18 07:44
Thanks for the report, other reports also confirm it.

Please download the older version that is now (again) available on the web page.

Closing as duplicate of #6709.

**Comment by markotoplak** [comment] 2024-01-18 07:45
Actually, reopening. Other users had problems adding widgets, you have a problem even earlier. Strange.

Please try with the 3.36.1 version that is now available on https://orangedatamining.com/download/ and report if it works for you.

**Comment by markotoplak** [comment] 2024-01-19 12:28
We just published new 3.36.2 packages that should fix these problem at https://orangedatamining.com/download/ 

Therefore, I am closing this issue. Please reopen if the issue persists.

**Closed by markotoplak** 2024-01-19 12:28 UTC
Labels: bug report
