### ISSUE TITLE
add RangeSlider gui component

### ISSUE THREAD

**Issue by kodymoodley** [biolab/orange3#6323] opened 2023-01-31 11:01 UTC
**What's your use case?**

Orange3 does not currently support RangeSlider gui components [see here](https://doc.qt.io/qt-6/qml-qtquick-controls2-rangeslider.html)

Not a problem. More a frustration.

I am building an Orange addon for text analysis that calculates scores for words based on certain metrics. I want to be able to filter words which have scores within a certain range. I am aware that there are other ways to specify numerical ranges using two [QSpinBox](https://www.tutorialspoint.com/pyqt/pyqt_qspinbox_widget.htm) components for example for the min and max values. However, I think it is more user-friendly and intuitive to use a range slider because then the user can more quickly and easily slide through different ranges to dynamically update the filtered results. Rather than manually typing arbitrary numbers for the min and max values for the QSpinBox components.

**What's your proposed solution?**

Port Range Slider widget to PyQt like in [this thread](https://stackoverflow.com/questions/47342158/porting-range-slider-widget-to-pyqt5).

**Are there any alternative solutions?**

I don't know.

**Comment by janezd** [comment] 2023-02-01 20:05
Thanks for this suggestion and for the link! It seems to work nicely (after the fix below), and properly paints the slider to have native look. Some small fixes are necessary, e.g. ticks are hard-coded, which also changes handle shapes from circular to triangular.

If we introduce this, I'd apply the same criteria as for regular sliders. We use them in cases when the actual number being set is opaque and meaningless to user (e.g. setting transparency in visualization, or regularization in regression), but not when the user might care about the number (e.g. minimal number of instances in tree leaves), in which case we prefer spin boxes or even pure line edits.

I personally dislike such double sliders for setting price intervals when buying bicycle parts. (Or whatever I'm buying on the web. That is, bicycle parts.)

**Note:** the linked code core dumps when `sizeHint` calls `QStyle.sizeFromContents`, which in tuen calls `QAbstractSlider.orientation`, which crashes. This can be fixed by

- deriving from `QSlider` - probably bad, because it adds other redundant methods
- removing the last argument, `self` from `sizeFromContents(QStyle.CT_Slider, self.opt, QSize(w, h), self)`. This does not seem to affect the sizing.

We must also see whether this class should be derived from `QAbstractSlider` instead of from `QWidget`. On the first glance, both work.

**Comment by janezd** [comment] 2023-02-03 09:05
At today's core group meeting we decided to add this control to the library. @markotoplak) also expressed concern about its potential overuse, and @BlazZupan confirmed its potential use in text mining widgets.

**Comment by kodymoodley** [comment] 2023-02-03 11:47
Thank you very much @janezd , @markotoplak  and @BlazZupan! I agree there is a potential to overuse it. But there are use cases where workarounds for no RangeSlider become unnecessarily complicated and unintuitive for qualitative researchers to use. Right now I need it for the Text mining use case above but I also know colleagues of mine building Orange addons who also need range sliders for Network Analysis. For example when filtering nodes in the network based on node centrality scores in a certain range. The usage of a single slider to filter scores above and below a certain threshold is useful but limited in its analytical power.

**Closed** 2023-02-17 07:51 UTC
