### ISSUE TITLE
SVM's not working... a bug with the polynomial degree 

### ISSUE THREAD

**Issue by PerryGogas** [biolab/orange3#6868] opened 2024-08-08 15:49 UTC
**What's wrong?**

After running a classification pipeline **after the 3.37 install** I get for the linear SVM:

> Fitting failed.
> The 'degree' parameter of SVC must be an int in the range [0, inf). Got 3.0 instead.

The funny thing is that **there is no degree parameter in the linear SVM** as it is... linear...
The relevant parameter is in the **polynomial SVM where by default it is set at 3.0**.
Probably this is the problem.
The system expects an integer and the default value and the parameter window reports the number as "3.0" that is **perceived as non-intege**r.

Now, even if I install any older version the bug still exists...

**How can we reproduce the problem?** 

- Data file:
[Credit Card Forecasting 400.xlsx](https://github.com/user-attachments/files/16550429/Credit.Card.Forecasting.400.xlsx)

- Orange file:
https://1drv.ms/u/s!ApNDH7n89OuPgdIT6GBAi3OGG3fhig?e=cDdIIx

**What's your environment?**

- Operating system: Windows 10
- Orange version: 3.37.0
- How you installed Orange: From the downloads on the Orange site.

**Comment by janezd** [comment] 2024-08-23 16:06
@markotoplak this is a duplicate of #6853 and was fixed in #6866, right?

**Comment by markotoplak** [comment] 2024-08-28 09:02
Duplicate of https://github.com/biolab/orange3/issues/6853

**Closed by markotoplak** 2024-08-28 09:02 UTC
Labels: bug report
