### ISSUE TITLE
Text addon causes crash on MacOS High Sierra

### ISSUE THREAD

**Issue by bogdanlalu** [biolab/orange3#3794] opened 2019-05-10 12:13 UTC
##### Orange version

3.20.1 

##### Actual behavior
The program crashes upon resizing a window

##### Steps to reproduce the behavior
1. Install Text addon (currently 0.6.0) and restart Orange
2. Add a widget
3. Double click on the widget to open it
4. Click on the edge of the window to resize it

##### Additional info (worksheets, data, screenshots, ...)

Crashes with the following message outputted in the terminal:  "Segmentation fault: 11"

Edit: Here's a more detailed output:
/anaconda3/envs/tf_p36/bin/pythonw: line 3:  3697 Segmentation fault: 11  /anaconda3/envs/tf_p36/python.app/Contents/MacOS/python "$@"

**_Uninstalling the addon fixes the issue_**

**Comment by ales-erjavec** [comment] 2019-05-10 12:52
Duplicate of https://github.com/biolab/orange3-text/issues/407

**Closed by ales-erjavec** 2019-05-10 12:52 UTC
