### ISSUE TITLE
Orange3 widgets move around

### ISSUE THREAD

**Issue by Vasco10** [biolab/orange3#3294] opened 2018-10-05 21:13 UTC
##### Expected behavior
When double-clicking on the widget it opens as expected. 
When doing it via contextual menu it opens as expected and remains as expected on its place.

##### Actual behavior
The widget moves to another place when double-clicked. With a few widget someone can manage well, but with complex systems it is quite chaotic.

##### Steps to reproduce the behavior
Just add some widgets and double-click on them.

##### Additional info (worksheets, data, screenshots, ...)
![widgtes_not_ok](https://user-images.githubusercontent.com/29803730/46560483-3dd8e480-c8f4-11e8-949c-ed16a1bdd66e.jpg)
![widgtes_ok](https://user-images.githubusercontent.com/29803730/46560484-3e717b00-c8f4-11e8-9d68-166ffdf2d36e.jpg)

**Comment by enjoysmath** [comment] 2018-10-09 22:35
Dude, I have the exact same version and have no problem like this.

**Comment by Vasco10** [comment] 2018-10-09 23:18
Apparently the problem is only on Windows version 10. Tried on another machine, it does exactly the same.
Tried it on a Windows 7 machine, it works.
Tried it on a Linux Debian system, it works.

**Comment by ajdapretnar** [comment] 2019-02-01 12:42
I tried on a fresh Windows 10 VM and cannot reproduce it either.

Closing until someone finds a way to reproduce it.

**Comment by markotoplak** [comment] 2019-02-01 13:00
I have these a similar problem on Linux with dwm in tiling mode and can reproduce it at will. 

If I double click, a new windows appears. And in tiling mode, this means that windows are rearranged/resized. The canvas therefore thinks that the widget was dragged because the position of the mouse cursor relative to canvas changed and the widget is moved.

**Comment by Vasco10** [comment] 2019-02-02 20:41
@ajdapretnar
@enjoysmath

Update on Orange 3 - widgets moving around:
---------------------------------------------------

I uninstalled everything and did a new installation (first Miniconda then Orange3).
This time I installed Orange3.20.

1. No errors were reported - not so with the previous versions.
(except for the add-on with the openTSNE, which I installed separately)
2. The widgets continue to "dance", but this time only one and curiously it sets itself behind the window - see picture.
(tried a few ones - always the same)

I intend to keep this so-called "beta" version.

![pr-2019-02-02](https://user-images.githubusercontent.com/29803730/52169088-1b849580-2733-11e9-945b-8ad18c7d7919.png)

**Comment by ajdapretnar** [comment] 2019-02-04 09:32
The behaviour where canvas is behind the widget window is expected/intentional. Go to View and uncheck _Display widgets on top_ to turn off this feature.

**Comment by Vasco10** [comment] 2019-02-04 19:33
@ajdapretnar 
Checked or unchecked the behavior is the same.

**Comment by markotoplak** [comment] 2019-03-27 10:21
In #3598 someone was kind enough to trace it (on Windows) to a feature called "Smart move".

**Comment by janezd** [comment] 2019-03-28 21:11
@thocevar, this looks like a job for somebody with Windows. (= You. :)) See #3598 for the explanation of why this happens.

**Closed** 2019-04-01 14:10 UTC
