### ISSUE TITLE
Table.from_numpy function doesn't work for numpy string array

### ISSUE THREAD

**Issue by nofarsa** [biolab/orange3#2074] opened 2017-03-06 09:53 UTC
##### Orange version

Orange 3.3.12

##### Expected behavior

the function _check_arrays gets a default parameter dtype='float64' and it fails for string array
if the meth

##### Steps to reproduce the behavior
the test function:
    def test_pandas_to_orange(self):
        dataset_orange = Orange.data.Table("iris")
        dataset_pandas = pd.DataFrame(datasets.load_iris().data, columns=['sepal length', 'sepal width',
                                                                                       'petal length',
                                                                                       'petal width']).round(decimals=2)

        dataset_pandas['iris'] = pd.DataFrame(datasets.load_iris().target, dtype='object')
        dataset_pandas.loc[dataset_pandas['iris'] == 0, 'iris'] = 'Iris-setosa'
        dataset_pandas.loc[dataset_pandas['iris'] == 1, 'iris'] = 'Iris-versicolor'
        dataset_pandas.loc[dataset_pandas['iris'] == 2, 'iris'] = 'Iris-virginica'

        data_transformation = DataUtil.DataFormatTransform()
        orange_from_pandas = data_transformation.pandas_to_orange(dataset_pandas)

def pandas_to_orange(data):
    domain = DataFormatTransform.df2domain(data)
    data_numpy=data.values
   domain = Orange.data.Domain.from_numpy(data_numpy)
   orange_data=Orange.data.Table.from_numpy(domain, data_numpy)

*it fails in the last line

##### Additional info (worksheets, data, screenshots, ...)
optional solution:
change the code: X, Y, W = _check_arrays(X, Y, W, dtype='float64')
to: X, Y, W = _check_arrays(X, Y, W)

**Comment by lanzagar** [comment] 2018-07-24 14:11
I am not sure I understand this issue correctly, but it looks to me like it is working correctly / as expected.
In Orange, X, Y and W arrays must be of type float64, hence also the dtype argument in that function call.

Maybe you tried with string values in the Y array (iris names instead of indices) and it failed because of that?
I am closing this issue (it is also very old), if someone can understand and reproduce the problem, reopen and clarify please.

**Closed by lanzagar** 2018-07-24 14:11 UTC
