### ISSUE TITLE
Report for Linear Regression

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1079] opened 2016-03-09 10:56 UTC
Implement Report function in Linear Regression as in other widgets. Report on learner name, model parameters and data.

Note: Button is already implemented, but it returns nothing.

**Comment by shark-S** [comment] 2016-03-09 14:41
have to implement  code for linear regression in orange environment ??

**Comment by ajdapretnar** [comment] 2016-03-09 14:58
No, you have to add report function as is present in other widgets.

**Comment by kumargaurav2596** [comment] 2016-03-14 17:46
I am working on it.

**Comment by kumargaurav2596** [comment] 2016-03-15 12:19
This is what the report looks like, does it need any change or should I commit.
![linear_regression_report](https://cloud.githubusercontent.com/assets/10504619/13777422/23af999a-ead6-11e5-9e62-256c6bfdedf3.png)

**Comment by kumargaurav2596** [comment] 2016-03-15 20:22
I have submitted a pull request for this issue [FIX] Report for Linear Regression #1079 #1118

**Comment by kernc** [comment] 2016-03-16 13:01
Fixed in https://github.com/biolab/orange3/pull/1092.

**Closed** 2016-03-16 13:21 UTC
Labels: easy
