### ISSUE TITLE
Automatically create a launcher icon on GNU/Linux?

### ISSUE THREAD

**Issue by brylie** [biolab/orange3#1426] opened 2016-07-08 07:47 UTC
Recently, lauhcing Orange on GNU/Linux involved activating a python environment and running a shell command. When installing via Anaconda, the process is easier, but still involves typing a shell command. Even though people might be using GNU/Linux, they may still appreciate launching Orange by clicking an icon.
## Orange version

3.x
## Expected bahavior

A launcher icon for Orange 3 would exist in my applications menu.
## Actual behavior

I need to launch Orange from the terminal:

```
source /path/to/orange3env/bin/activate
python -m Orange.canvas
```
## Steps to reproduce the behavior

Install and launch Orange.

**Comment by kernc** [comment] 2016-07-08 09:46
We've had this in https://github.com/biolab/orange3/pull/1205, but it was reverted in https://github.com/biolab/orange3/pull/1218 because installing the launcher is responsibility of the distributed installable package (e.g. deb) and not the source distribution's.

Building packages for multiple distributions should probably include some subset of:
* [AppImage](http://appimage.org/) ̉– @acopar any update on this?
* [Snap or Snappy or snapd](https://en.wikipedia.org/wiki/Snappy_%28package_manager%29) – not really.
* [Suse](https://build.opensuse.org/)'s [OpenBuildService](http://openbuildservice.org/) which can take a debian source package (orig.tar.xz, debian.tar.xz, and dsc) and build packages (deb, rpm, pkg) for multiple distributions and architectures.

**Comment by astaric** [comment] 2016-12-12 10:37
When installed with conda (https://github.com/conda-forge/orange3-feedstock#installing-orange3), you can run orange-canvas and then right click the icon in the launch bar and select either Add to Dash or Lock to Launcher.

You should also be able to access Orange through Anaconda Navigator.

As for installing a launcher as part of the setup.py installation, this is a duplicate of #1190, which was marked as "wont fix".

**Closed by astaric** 2016-12-12 10:37 UTC
