### ISSUE TITLE
The parameter settings of the model are garbled

### ISSUE THREAD

**Issue by yanglixiaLisa** [biolab/orange3#5133] opened 2020-12-16 10:06 UTC
- [ ] **What's wrong?**

The parameter settings of the model are garbled on only my comptuer. If I click the up and down adjustment buttons, this garbled characters will change accordingly.
![image](https://user-images.githubusercontent.com/26914220/102331918-67a6ef00-3fc6-11eb-8e24-09f0c3cff01e.png)
![image](https://user-images.githubusercontent.com/26914220/102331957-71c8ed80-3fc6-11eb-93ed-6740e9d6bac1.png)
![image](https://user-images.githubusercontent.com/26914220/102332018-84432700-3fc6-11eb-829e-c6d15d8a0d1e.png)
![miss](https://user-images.githubusercontent.com/26914220/102333135-f6683b80-3fc7-11eb-9c40-5bad32ea01c4.gif)

- [ ] **How can we reproduce the problem?** 

Only my computer has this problem, and no one else has encountered it.. Every time I open the parameter setting panel of the model, there will be this garbled problem.  Any data, any model, it comes everey time. 
![image](https://user-images.githubusercontent.com/26914220/102332125-a9379a00-3fc6-11eb-85b8-c16258abf6b2.png)

- [ ] **What's your environment?**

- Operating system:   Windows 10 enterprise edition 17134.1902
- Orange version:    Orange3-3.27.1-Miniconda-x86_64    &     Orange3-3.24.2b-Python37-win_amd64
- How you installed Orange:   The Installation package was download on the https://orange.biolab.si/download/#windows, and  click this Orange3-3.27.1-Miniconda-x86_64.exe to install. I also try the Orange3-3.24.2b-Python37-win_amd64.exe ,this problem also appeare.

**Comment by janezd** [comment] 2020-12-18 16:32
Thanks for reporting. But there is unfortunately nothing we can do here to help. We have not seen anything like this before and have no idea how to reproduce it. It must be related to the configuration of your system and its interaction with the library we use for GUI (PyQt), so even if we could reproduce it, fixing it could be beyond our power. Please try to play with fonts and international settings.

I'm closing this issue because we can't do anything, but please tell us if you discover the fix.

**Closed by janezd** 2020-12-18 16:32 UTC
Labels: bug report
