### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by hoekp** [biolab/orange3#4805] opened 2020-05-21 22:58 UTC
After installing Orange3 on a corporate computer behind a firewall I get an error if I attempt to use certain widgets. For example, as soon as I drag a PCA widget on to the canvas I get and error IndexError: list index out of range. (Trace shown below). 

It is hard to reproduce, as it is this network/computer specific. It may be caused by group permissions/environment/etc.
Can someone help in identifying where I should look to rectify the issue.

Many other widgets work , e.g.  CSV file import, line plot, distributions, box plot, heat map, python script, geo-map,  word cloud, etc all work.

**Orange version:**
Orange3=3.25.0

Copy of the error trace is shown below.
Traceback (most recent call last):
  File "C:\Users\hoekp\.conda\envs\testenv5\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 242, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "C:\Users\hoekp\.conda\envs\testenv5\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 296, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "C:\Users\hoekp\.conda\envs\testenv5\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 409, in create_widget_instance
    widget.__init__()
  File "C:\Users\hoekp\.conda\envs\testenv5\lib\site-packages\Orange\widgets\unsupervised\owpca.py", line 66, in __init__
    self._init_projector()
  File "C:\Users\hoekp\.conda\envs\testenv5\lib\site-packages\Orange\widgets\unsupervised\owpca.py", line 256, in _init_projector
    self._pca_projector = PCA(n_components=MAX_COMPONENTS, random_state=0)
  File "C:\Users\hoekp\.conda\envs\testenv5\lib\site-packages\Orange\projection\pca.py", line 261, in __init__
    self.params = vars()
  File "C:\Users\hoekp\.conda\envs\testenv5\lib\site-packages\Orange\projection\base.py", line 194, in params
    self._params = self._get_sklparams(value)
  File "C:\Users\hoekp\.conda\envs\testenv5\lib\site-packages\Orange\projection\base.py", line 201, in _get_sklparams
    assert spec.args[0] == "self"
IndexError: list index out of range
**Operating system:**
Windows

**Comment by ajdapretnar** [comment] 2020-05-22 07:18
Duplicate of https://github.com/biolab/orange3/issues/4795.

**Closed by ajdapretnar** 2020-05-22 07:18 UTC
Labels: bug report

**Comment by ronaldgevern** [comment] 2022-09-26 05:24
The IndexError is raised when attempting to retrieve an index from a sequence (e.g. list, tuple), and the index isn’t found in the sequence. The Python documentation defines when this exception is raised:

`Raised when a sequence subscript is out of range.`

Here’s an [Python Split()](http://net-informations.com/python/file/split.htm) example that raises the IndexError:

```
data = "one%two%three%four%five"
numbers = data.split('%')
```

The list numbers has 5 elements, and the indexing starts with 0, so, the last element will have index 4. If you try to subscript with an index higher than 4, the Python Interpreter will raise an IndexError since there is no element at such index.
