### ISSUE TITLE
Commonmark 0.8.1 breaks Orange3

### ISSUE THREAD

**Issue by jasonhfuller** [biolab/orange3#3263] opened 2018-09-22 01:01 UTC
##### Orange version
ALL VERSIONS
Tested with:
orange3 3.15.0  &  orange3 3.14.0

##### Expected behavior
After completing a fresh install via `pip install orange3` running `python -m Orange.canvas` should launch Orange

##### Actual behavior
`$ python -m Orange.canvas 
Traceback (most recent call last):
  File "/home/hybrid/.pyenv/versions/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hybrid/.pyenv/versions/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hybrid/.pyenv/versions/3.6.3/lib/python3.6/site-packages/Orange/canvas/__main__.py", line 30, in <module>
    from Orange.canvas.application.canvasmain import CanvasMainWindow
  File "/home/hybrid/.pyenv/versions/3.6.3/lib/python3.6/site-packages/Orange/canvas/application/canvasmain.py", line 61, in <module>
    from .canvastooldock import CanvasToolDock, QuickCategoryToolbar, \
  File "/home/hybrid/.pyenv/versions/3.6.3/lib/python3.6/site-packages/Orange/canvas/application/canvastooldock.py", line 25, in <module>
    from ..document.quickmenu import MenuPage
  File "/home/hybrid/.pyenv/versions/3.6.3/lib/python3.6/site-packages/Orange/canvas/document/__init__.py", line 17, in <module>
    from .schemeedit import SchemeEditWidget
  File "/home/hybrid/.pyenv/versions/3.6.3/lib/python3.6/site-packages/Orange/canvas/document/schemeedit.py", line 37, in <module>
    from .suggestions import Suggestions
  File "/home/hybrid/.pyenv/versions/3.6.3/lib/python3.6/site-packages/Orange/canvas/document/suggestions.py", line 7, in <module>
    from .interactions import NewLinkAction
  File "/home/hybrid/.pyenv/versions/3.6.3/lib/python3.6/site-packages/Orange/canvas/document/interactions.py", line 28, in <module>
    from ..canvas import items
  File "/home/hybrid/.pyenv/versions/3.6.3/lib/python3.6/site-packages/Orange/canvas/canvas/items/__init__.py", line 9, in <module>
    from .annotationitem import TextAnnotation, ArrowAnnotation
  File "/home/hybrid/.pyenv/versions/3.6.3/lib/python3.6/site-packages/Orange/canvas/canvas/items/annotationitem.py", line 7, in <module>
    import CommonMark
ModuleNotFoundError: No module named 'CommonMark'
`

##### Steps to reproduce the behavior
`pip install commonmark 0.8.1`
run `python -m Orange.canvas` 

##### Additional info (worksheets, data, screenshots, ...)
Downgrading to commonmark 0.8.0 fixes this.

Solution:
Change orange3's dependencies from 
CommonMark>=0.5.5  to CommonMark>=0.5.5,<=0.8.0

**Comment by ajdapretnar** [comment] 2018-09-24 07:46
Duplicate of https://github.com/biolab/orange3/issues/3250. Fixed in https://github.com/biolab/orange3/pull/3234. The new 3.16 version should work.

**Closed by ajdapretnar** 2018-09-24 07:46 UTC

**Comment by jasonhfuller** [comment] 2018-10-01 19:11
Confirmed as fixed in 3.16.  Sorry, I thought my upgrade to 3.16 had
completed when it had not.

- J
