### ISSUE TITLE
Change multiple attribute types

### ISSUE THREAD

**Issue by leeherman99** [biolab/orange3#4630] opened 2020-04-07 13:52 UTC
**Is your feature request related to a problem? Please describe.**

**Here**, write a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
I have a data set with a large number of attributes that are being interpreted as categorical, but they should be numerical. Changing the types manually is extremely tiresome.

**Describe the solution you'd like**
I would like to be able to change the types of multiple attributes in one shot.
Add a clear and concise description of what you want to happen **here**.

**Describe alternatives you've considered**

**Additional context**

**Comment by ajdapretnar** [comment] 2020-04-07 13:56
My preferred way is to use CSV File Import, where I can shift and select several attributes, then use the right click to set the type for all of them.

**Comment by leeherman99** [comment] 2020-04-07 20:54
Thanks, that worked.

**Comment by janezd** [comment] 2020-04-30 21:34
I see no simple way to change the (current) File widget. The issue is stalled and can be circumvented using CSV File import. Another way is to modify the files. So let's close this.

**Closed by janezd** 2020-04-30 21:34 UTC
