### ISSUE TITLE
Topic Modelling Ad on not working

### ISSUE THREAD

**Issue by NAsic123** [biolab/orange3#6045] opened 2022-06-22 16:01 UTC
Hello,

I am using Orange for my research (I am using LDA method). I downloaded previous version of Orange. But now when I downloaded the new version of programme, I can not do Topic Modelling (program crushed when I want to apply Topic Modelling).

I want to install previous version of Orange.

Is this possible?

Thank you for answer.

Best regards
Nejc Ašič

_
Slovenian:

Spoštovani.

Uporabljam Orange za analizo podatkov za svojo raziskavo, uporabljam LDA metodo, torej add on Topic Modelling. Do danes sem imel naloženo staro verzijo Orange programa. Danes sem ga posodil in od danes naprej ne morem uporabljati Topic Modellinga. Vsakič, ko zaženem Topic Modelling, se program zruši in nega delovati. Kot da nova verzija Topic Modellinga ne zmore uporabljati.

Mi lahko, prosim, pomagate? Želel bi, da Topic Modelling dela. Če v novem programu (posodobljenem) ne dela, me zanima, kako se naloži pretekla verzija programa Orange. Hvala vam.

Lep pozdrav
Nejc Ašič

**Comment by NAsic123** [comment] 2022-07-05 09:00
Version of Orange: 3.32.0
Version of Text add-on: 1.9.0

![image](https://user-images.githubusercontent.com/108016235/177291212-6dc64c6c-e2ac-420a-8934-73b40c1b2793.png)
![image](https://user-images.githubusercontent.com/108016235/177291256-c9c2202e-14f4-4232-95ad-eb8d62035c46.png)




> Thank you for reporting this. Could you please also state the version of Orange and the version of Text add-on?

**Comment by ajdapretnar** [comment] 2022-07-05 10:16
I think this is a duplicate of #820.

**Closed by ajdapretnar** 2022-07-05 10:16 UTC
Labels: bug report
