### ISSUE TITLE
Provide the same filtering options in "Select Columns" widget as in "Select Rows" 

### ISSUE THREAD

**Issue by smihael** [biolab/orange3#1765] opened 2016-11-19 12:27 UTC
Since #1588  was closed, I am reopening this as a separate issue (as suggested by @kernc )

Select columns widget lacks filtering options that are otherwise present when selecting rows. It would be nice if one could filter some columns out by simply checking if certain values occur. Currently this can be done only using a separate python widget, but not everyone has experience with coding.

**Comment by kernc** [comment] 2016-11-21 19:12
If this works for rows with _Select Rows_, it might be possible (if cumbersome) to achieve what you want for columns by using the _Transpose_ widget (https://github.com/biolab/orange3/pull/1738)?

**Comment by janezd** [comment] 2019-04-10 21:54
This probably makes sense in situations in which columns are somehow related, e.g. they measure the same thing in different circumstances. For such tables, one can use the Transpose widget to switch columns and rows, then filter by rows, and transpose back.

- Double transposing is not elegant, but the suggested functionality is far from what Select columns does currently, and it's incompatible with the current GUI. On the other hand, it's exactly the same as what Select rows does - except that it's on rows.

- The proposed functionality would be unclear in cases when variables are of different types. The available operators would also differ for categorical, numeric and string columns (like in #2223, but there it doesn't complicate the interface from the user's perspective).

- The issue is stalled: nobody showed interest in implementing in, neither was there any internal or other discussion.

I'm therefore closing it. If anybody is willing to propose a GUI (one solution that comes to mind is amending Select Rows widget instead of changing Select Columns) and implement it, we can reopen it (or start a new one).

**Closed by janezd** 2019-04-10 21:54 UTC
Labels: enhancement
