### ISSUE TITLE
Multiple sheets in Excel Files

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#1045] opened 2016-03-03 13:20 UTC
Orange does not support multiple sheets in Excel files. Add this functionality to the file widget. Don't ruin the GUI layout.

**Comment by rahulroxx** [comment] 2016-03-03 14:48
I did a quick fix for selecting multiple xls in the file widget . Should i update the comboBox too ? 

`import os
from warnings import catch_warnings

from PyQt4 import QtGui, QtCore
from PyQt4.QtGui import QSizePolicy as Policy

from Orange.widgets import widget, gui
from Orange.widgets.settings import Setting
from Orange.widgets.utils.itemmodels import PyListModel
from Orange.data.table import Table, get_sample_datasets_dir
from Orange.data.io import FileFormat


def add_origin(examples, filename):
    """Adds attribute with file location to each variable"""
    vars = examples.domain.variables + examples.domain.metas
    strings = [var for var in vars if var.is_string]
    dir_name, basename = os.path.split(filename)
    for var in strings:
        if "type" in var.attributes and "origin" not in var.attributes:
            var.attributes["origin"] = dir_name


class RecentPath:
    abspath = ''
    prefix = None   #: Option[str]  # BASEDIR | SAMPLE-DATASETS | ...
    relpath = ''  #: Option[str]  # path relative to `prefix`
    title = ''    #: Option[str]  # title of filename (e.g. from URL)

    def __init__(self, abspath, prefix, relpath, title=''):
        if os.name == "nt":
            # always use a cross-platform pathname component separator
            abspath = abspath.replace(os.path.sep, "/")
            if relpath is not None:
                relpath = relpath.replace(os.path.sep, "/")
        self.abspath = abspath
        self.prefix = prefix
        self.relpath = relpath
        self.title = title

    def __eq__(self, other):
        return (self.abspath == other.abspath or
                (self.prefix is not None and self.relpath is not None and
                 self.prefix == other.prefix and
                 self.relpath == other.relpath))

    @staticmethod
    def create(path, searchpaths):
        """
        Create a RecentPath item inferring a suitable prefix name and relpath.
        Parameters
        ----------
        path : str
            File system path.
        searchpaths : List[Tuple[str, str]]
            A sequence of (NAME, prefix) pairs. The sequence is searched
            for a item such that prefix/relpath == abspath. The NAME is
            recorded in the `prefix` and relpath in `relpath`.
            (note: the first matching prefixed path is chosen).
        """
        def isprefixed(prefix, path):
            """
            Is `path` contained within the directory `prefix`.
            >>> isprefixed("/usr/local/", "/usr/local/shared")
            True
            """
            normalize = lambda path: os.path.normcase(os.path.normpath(path))
            prefix, path = normalize(prefix), normalize(path)
            if not prefix.endswith(os.path.sep):
                prefix = prefix + os.path.sep
            return os.path.commonprefix([prefix, path]) == prefix

        abspath = os.path.normpath(os.path.abspath(path))
        for prefix, base in searchpaths:
            if isprefixed(base, abspath):
                relpath = os.path.relpath(abspath, base)
                return RecentPath(abspath, prefix, relpath)

        return RecentPath(abspath, None, None)

    def search(self, searchpaths):
        """
        Return a file system path, substituting the variable paths if required
        If the self.abspath names an existing path it is returned. Else if
        the `self.prefix` and `self.relpath` are not `None` then the
        `searchpaths` sequence is searched for the matching prefix and
        if found and the {PATH}/self.relpath exists it is returned.
        If all fails return None.
        Parameters
        ----------
        searchpaths : List[Tuple[str, str]]
            A sequence of (NAME, prefixpath) pairs.
        """
        if os.path.exists(self.abspath):
            return os.path.normpath(self.abspath)

        for prefix, base in searchpaths:
            if self.prefix == prefix:
                path = os.path.join(base, self.relpath)
                if os.path.exists(path):
                    return os.path.normpath(path)
        else:
            return None

    def resolve(self, searchpaths):
        if self.prefix is None and os.path.exists(self.abspath):
            return self
        elif self.prefix is not None:
            for prefix, base in searchpaths:
                if self.prefix == prefix:
                    path = os.path.join(base, self.relpath)
                    if os.path.exists(path):
                        return RecentPath(
                            os.path.normpath(path), self.prefix, self.relpath)
        return None

    @property
    def value(self):
        return os.path.basename(self.abspath)

    @property
    def icon(self):
        provider = QtGui.QFileIconProvider()
        return provider.icon(QtGui.QFileIconProvider.Drive)

    @property
    def dirname(self):
        return os.path.dirname(self.abspath)

    def __repr__(self):
        return ("{0.__class__.__name__}(abspath={0.abspath!r}, "
                "prefix={0.prefix!r}, relpath={0.relpath!r}, "
                "title={0.title!r})").format(self)

    __str__ = __repr__


class NamedURLModel(PyListModel):
    def __init__(self, mapping):
        self.mapping = mapping
        super().__init__()

    def data(self, index, role):
        data = super().data(index, role)
        if role == QtCore.Qt.DisplayRole:
            return self.mapping.get(data, data)
        return data

    def add_name(self, url, name):
        self.mapping[url] = name
        self.modelReset.emit()


class OWFile(widget.OWWidget):
    name = "File"
    id = "orange.widgets.data.file"
    description = "Read a data from an input file or network" \
                  "and send the data table to the output."
    icon = "icons/File.svg"
    priority = 10
    category = "Data"
    keywords = ["data", "file", "load", "read"]
    outputs = [widget.OutputSignal(
        "Data", Table,
        doc="Attribute-valued data set read from the input file.")]

    want_main_area = False
    resizing_enabled = False

    LOCAL_FILE, URL = range(2)

    #: List[RecentPath]
    recent_paths = Setting([])
    recent_urls = Setting([])
    source = Setting(LOCAL_FILE)
    sheet_names = Setting({})
    url = Setting("")

    dlg_formats = (
        "All readable files ({});;".format(
            '*' + ' *'.join(FileFormat.readers.keys())) +
        ";;".join("{} (*{})".format(f.DESCRIPTION, ' *'.join(f.EXTENSIONS))
                  for f in sorted(set(FileFormat.readers.values()),
                                  key=list(FileFormat.readers.values()).index)))

    def __init__(self):
        super().__init__()
        self.domain = None
        self.data = None
        self.loaded_file = ""
        self._relocate_recent_files()

        layout = QtGui.QGridLayout()
        gui.widgetBox(self.controlArea, margin=0, orientation=layout)
        vbox = gui.radioButtons(None, self, "source", box=True, addSpace=True,
                                callback=self.load_data, addToLayout=False)

        rb_button = gui.appendRadioButton(vbox, "File", addToLayout=False)
        layout.addWidget(rb_button, 0, 0, QtCore.Qt.AlignVCenter)

        box = gui.hBox(None, addToLayout=False, margin=0)
        box.setSizePolicy(Policy.MinimumExpanding, Policy.Fixed)
        self.file_combo = file_combo = QtGui.QComboBox(box)
        file_combo.currentIndexChanged[str].connect(self.select_file)
        file_combo.setSizePolicy(Policy.MinimumExpanding, Policy.Fixed)
        file_combo.activated[int].connect(self.select_file)
        box.layout().addWidget(file_combo)
        button = gui.button(
            box, self, '...', callback=self.browse_file, autoDefault=False)
        button.setIcon(self.style().standardIcon(QtGui.QStyle.SP_DirOpenIcon))
        button.setSizePolicy(Policy.Maximum, Policy.Fixed)
        button = gui.button(
            box, self, "Reload", callback=self.reload, autoDefault=False)
        button.setIcon(self.style().standardIcon(QtGui.QStyle.SP_BrowserReload))
        button.setSizePolicy(Policy.Fixed, Policy.Fixed)
        layout.addWidget(box, 0, 1,  QtCore.Qt.AlignVCenter)

        rb_button = gui.appendRadioButton(vbox, "URL", addToLayout=False)
        layout.addWidget(rb_button, 1, 0, QtCore.Qt.AlignVCenter)

        box = gui.hBox(vbox, addToLayout=False)
        self.url_combo = url_combo = QtGui.QComboBox()
        url_model = NamedURLModel(self.sheet_names)
        url_model.wrap(self.recent_urls)
        url_combo.setModel(url_model)
        url_combo.setSizePolicy(Policy.MinimumExpanding, Policy.Fixed)
        url_combo.setEditable(True)
        url_combo.setInsertPolicy(url_combo.InsertAtTop)
        url_edit = url_combo.lineEdit()
        l, t, r, b = url_edit.getTextMargins()
        url_edit.setTextMargins(l + 5, t, r, b)
        box.layout().addWidget(url_combo)
        url_combo.activated.connect(self._url_set)
        layout.addWidget(box, 1, 1, QtCore.Qt.AlignVCenter)

        box = gui.vBox(self.controlArea, "Info")
        self.info = gui.widgetLabel(box, 'No data loaded.')
        self.warnings = gui.widgetLabel(box, '')

        box = gui.hBox(self.controlArea)
        gui.button(
            box, self, "Browse documentation data sets",
            callback=lambda: self.browse_file(True), autoDefault=False)
        gui.rubber(box)
        box.layout().addWidget(self.report_button)
        self.report_button.setFixedWidth(170)

        # Set word wrap, so long warnings won't expand the widget
        self.warnings.setWordWrap(True)
        self.warnings.setSizePolicy(Policy.Ignored, Policy.MinimumExpanding)

        self.set_file_list()
        # Must not call open_file from within __init__. open_file
        # explicitly re-enters the event loop (by a progress bar)
        QtCore.QTimer.singleShot(0, self.load_data)

    def _relocate_recent_files(self):
        paths = [("sample-datasets", get_sample_datasets_dir())]
        basedir = self.workflowEnv().get("basedir", None)
        if basedir is not None:
            paths.append(("basedir", basedir))

        rec = []
        for recent in self.recent_paths:
            resolved = recent.resolve(paths)
            if resolved is not None:
                rec.append(RecentPath.create(resolved.abspath, paths))
            elif recent.search(paths) is not None:
                rec.append(RecentPath.create(recent.search(paths), paths))
        self.recent_paths = rec

    def set_file_list(self):
        self.file_combo.clear()
        if not self.recent_paths:
            self.file_combo.addItem("(none)")
            self.file_combo.model().item(0).setEnabled(False)
        else:
            for i, recent in enumerate(self.recent_paths):
                self.file_combo.addItem(recent.value)
                self.file_combo.model().item(i).setToolTip(recent.abspath)

    def reload(self):
        if self.recent_paths:
            basename = self.file_combo.currentText()
            path = self.recent_paths[0]
            if basename in [path.relpath, path.value]:
                self.source = self.LOCAL_FILE
                return self.load_data()
        self.select_file(len(self.recent_paths) + 1)

    def select_file(self, n):
        if n < len(self.recent_paths):
            recent = self.recent_paths[n]
            del self.recent_paths[n]
            self.recent_paths.insert(0, recent)
        elif n:
            path = self.file_combo.currentText()
            if os.path.exists(path):
                self._add_path(path)
            else:
                self.info.setText('Data was not loaded:')
                self.warnings.setText("File {} does not exist".format(path))
                self.file_combo.removeItem(n)
                self.file_combo.lineEdit().setText(path)
                return

        if len(self.recent_paths) > 0:
            self.source = self.LOCAL_FILE
            self.load_data()
            self.set_file_list()

    def _url_set(self):
        self.source = self.URL
        self.load_data()

    def browse_file(self, in_demos=False):
        if in_demos:
            try:
                start_file = get_sample_datasets_dir()
            except AttributeError:
                start_file = ""
            if not start_file or not os.path.exists(start_file):
                widgets_dir = os.path.dirname(gui.__file__)
                orange_dir = os.path.dirname(widgets_dir)
                start_file = os.path.join(orange_dir, "doc", "datasets")
            if not start_file or not os.path.exists(start_file):
                d = os.getcwd()
                if os.path.basename(d) == "canvas":
                    d = os.path.dirname(d)
                start_file = os.path.join(os.path.dirname(d), "doc", "datasets")
            if not os.path.exists(start_file):
                QtGui.QMessageBox.information(
                    None, "File",
                    "Cannot find the directory with example data sets")
                return
        else:
            if self.recent_paths:
                start_file = self.recent_paths[0].abspath
            else:
                start_file = os.path.expanduser("~/")

        filename = QtGui.QFileDialog.getOpenFileNames(
            self, 'Open Orange Data File', start_file, self.dlg_formats)
        if not filename:
            return

        self._add_path(filename)
        self.set_file_list()
        self.source = self.LOCAL_FILE
        self.load_data()

    def _add_path(self, filename):
        searchpaths = [("sample-datasets", get_sample_datasets_dir())]
        basedir = self.workflowEnv().get("basedir", None)
        if basedir is not None:
            searchpaths.append(("basedir", basedir))
        recent = RecentPath.create(filename, searchpaths)
        if recent in self.recent_paths:
            self.recent_paths.remove(recent)
        self.recent_paths.insert(0, recent)

    # Open a file, create data from it and send it over the data channel
    def load_data(self):
        def load(method, fn):
            with catch_warnings(record=True) as warnings:
                data = method(fn)
                self.warning(
                        33, warnings[-1].message.args[0] if warnings else '')
            return data, fn

        def load_from_file():
            fn = fn_original = self.recent_paths[0].abspath
            if fn == "(none)":
                return None, ""
            if not os.path.exists(fn):
                dir_name, basename = os.path.split(fn)
                if os.path.exists(os.path.join(".", basename)):
                    fn = os.path.join(".", basename)
                    self.information("Loading '{}' from the current directory."
                                     .format(basename))
            try:
                return load(Table.from_file, fn)
            except Exception as exc:
                self.warnings.setText(str(exc))
                ind = self.file_combo.currentIndex()
                self.file_combo.removeItem(ind)
                if ind < len(self.recent_paths) and \
                        self.recent_paths[ind].abspath == fn_original:
                    del self.recent_paths[ind]
                raise

        def load_from_network():
            combo = self.url_combo
            model = combo.model()
            # combo.currentText does not work when the widget is initialized
            url = model.data(model.index(combo.currentIndex()),
                             QtCore.Qt.EditRole)
            if not url:
                return None, ""
            elif "://" not in url:
                url = "http://" + url
            try:
                data, url = load(Table.from_url, url)
            except:
                self.warnings.setText(
                        "URL '{}' does not contain valid data".format(url))
                # Don't remove from recent_urls:
                # resource may reappear, or the user mistyped it
                # and would like to retrieve it from history and fix it.
                raise
            combo.clearFocus()
            if "://docs.google.com/spreadsheets" in url:
                model.add_name(url, data.name)
                self.url = \
                    "{} from {}".format(data.name.replace("- Sheet1", ""), url)
                combo.lineEdit().setPlaceholderText(self.url)
                return data, data.name
            else:
                self.url = url
                return data, url

        self.warning()
        self.information()

        try:
            loader = [load_from_file, load_from_network][self.source]
            self.data, self.loaded_file = loader()
        except:
            self.info.setText("Data was not loaded:")
            self.data = None
            self.loaded_file = ""
            return
        else:
            self.warnings.setText("")

        data = self.data
        if data is None:
            self.send("Data", None)
            self.info.setText("No data loaded")
            return

        domain = data.domain
        text = "{} instance(s), {} feature(s), {} meta attribute(s)".format(
            len(data), len(domain.attributes), len(domain.metas))
        if domain.has_continuous_class:
            text += "\nRegression; numerical class."
        elif domain.has_discrete_class:
            text += "\nClassification; discrete class with {} values.".format(
                len(domain.class_var.values))
        elif data.domain.class_vars:
            text += "\nMulti-target; {} target variables.".format(
                len(data.domain.class_vars))
        else:
            text += "\nData has no target variable."
        if 'Timestamp' in data.domain:
            # Google Forms uses this header to timestamp responses
            text += '\n\nFirst entry: {}\nLast entry: {}'.format(
                data[0, 'Timestamp'], data[-1, 'Timestamp'])
        self.info.setText(text)

        add_origin(data, self.loaded_file)
        self.send("Data", data)

    def get_widget_name_extension(self):
        _, name = os.path.split(self.loaded_file)
        return os.path.splitext(name)[0]

    def send_report(self):
        def get_ext_name(filename):
            try:
                return FileFormat.names[os.path.splitext(filename)[1]]
            except KeyError:
                return "unknown"

        if self.data is None:
            self.report_paragraph("File", "No file.")
            return

        if self.source == self.LOCAL_FILE:
            home = os.path.expanduser("~")
            if self.loaded_file.startswith(home):
                # os.path.join does not like ~
                name = "~/" + \
                       self.loaded_file[len(home):].lstrip("/").lstrip("\\")
            else:
                name = self.loaded_file
            self.report_items("File", [("File name", name),
                                       ("Format", get_ext_name(name))])
        else:
            self.report_items("Data", [("Resource", self.url),
                                       ("Format", get_ext_name(self.url))])

        self.report_data("Data", self.data)

    def workflowEnvChanged(self, key, value, oldvalue):
        if key == "basedir":
            self._relocate_recent_files()
            self.set_file_list()


if __name__ == "__main__":
    import sys
    a = QtGui.QApplication(sys.argv)
    ow = OWFile()
    ow.show()
    a.exec_()
    ow.saveSettings()
`

**Comment by rahulroxx** [comment] 2016-03-03 14:50
@janezd  i did a quick fix to select multiple files as mentioned in the file widget 
Here is the code snippet 
`    def browse_file(self, in_demos=False):
        if in_demos:
            try:
                start_file = get_sample_datasets_dir()
            except AttributeError:
                start_file = ""
            if not start_file or not os.path.exists(start_file):
                widgets_dir = os.path.dirname(gui.__file__)
                orange_dir = os.path.dirname(widgets_dir)
                start_file = os.path.join(orange_dir, "doc", "datasets")
            if not start_file or not os.path.exists(start_file):
                d = os.getcwd()
                if os.path.basename(d) == "canvas":
                    d = os.path.dirname(d)
                start_file = os.path.join(os.path.dirname(d), "doc", "datasets")
            if not os.path.exists(start_file):
                QtGui.QMessageBox.information(
                    None, "File",
                    "Cannot find the directory with example data sets")
`

**Comment by rahulroxx** [comment] 2016-03-03 14:52
@janezd  i did a quick fix to select multiple sheets in Excel files in the FIle Widget 

```

    def browse_file(self, in_demos=False):
        if in_demos:
            try:
                start_file = get_sample_datasets_dir()
            except AttributeError:
                start_file = ""
            if not start_file or not os.path.exists(start_file):
                widgets_dir = os.path.dirname(gui.__file__)
                orange_dir = os.path.dirname(widgets_dir)
                start_file = os.path.join(orange_dir, "doc", "datasets")
            if not start_file or not os.path.exists(start_file):
                d = os.getcwd()
                if os.path.basename(d) == "canvas":
                    d = os.path.dirname(d)
                start_file = os.path.join(os.path.dirname(d), "doc", "datasets")
            if not os.path.exists(start_file):
                QtGui.QMessageBox.information(
                    None, "File",
                    "Cannot find the directory with example data sets")
                return
        else:
            if self.recent_paths:
                start_file = self.recent_paths[0].abspath
            else:
                start_file = os.path.expanduser("~/")

        filename = QtGui.QFileDialog.getOpenFileNames(
            self, 'Open Orange Data File', start_file, self.dlg_formats)
        if not filename:
            return

        self._add_path(filename)
        self.set_file_list()
        self.source = self.LOCAL_FILE
        self.load_data()

```

**Comment by ajdapretnar** [comment] 2016-03-03 15:07
Make a PR so we can test it. Thanks!

**Comment by ajdapretnar** [comment] 2016-03-03 15:09
Also be wary of quick fixes. In particular, make sure it works with Data Table (and its tabs functionality).

**Comment by rahulroxx** [comment] 2016-03-03 15:11
What Exactly should i do here . Should i make a gui for displaying the Multiple Excel files in Data Table ?

**Comment by ajdapretnar** [comment] 2016-03-03 15:35
GUI is already there. Data Table displays tabs when fed multiple data sets. Use this functionality to switch between Excel Sheets. Also implement an option to select which sheet to output in the File widget and Data Table widget. Think also about merging and concatenating data from different sheets.

**Comment by rahulroxx** [comment] 2016-03-03 15:39
@ajdapretnar 
Thanks !

**Comment by rahulroxx** [comment] 2016-03-03 15:56
@ajdapretnar  Please review this workflow . tell me if i am wrong !
1) select multiple excel files in file widget 
2) output of the file widget should be multiple excel files with switching tabs 

Basically We need to access multiple excel files  in Data Table with one instance of File widget and Data Table  right ?

**Comment by ajdapretnar** [comment] 2016-03-03 16:09
The initial idea was to simply switch between the sheets. So if you have Sheet 1 and Sheet 2, can you switch between them in the Data Table?
Of course, it needs to be discussed where the selection would take place. Link editor would be one option, but what if the user has many sheets?
@janezd Would the sheet selection take place in the File widget or in later widgets? This seems a bit more complicated than we though... Many details to discuss here.

**Comment by janezd** [comment] 2016-03-03 16:33
The idea is that you select the sheet in the File widget.

When the user opens an Excel file (a single file!) the File widget checks whether there are multiple (non-empty) sheets. If there is just one, it loads it just like now. If there are multiple, a new combo appears in the widget (well, the combo is always there, but hidden when it is not needed) that allows the user to select the sheet. The combo is populated with the sheet names and the first sheet is selected and loaded by default.

Furthermore, assume I select the third sheet. Then I close Orange and open it again: the third sheet must be selected. Also, if I load another file and select, say, the fifth sheet, but then load the first file again, the third sheet must again be selected. Therefore, the widget must remember the selected sheet for each file that was loaded in the past.

The latter is somewhat more difficult since it is accomplished by context settings. You can implement the rest first and then get some assistance with storing the settings.

**Comment by rahulroxx** [comment] 2016-03-03 16:45
I doing first half module first ! 
Thanks @janezd

**Comment by rahulroxx** [comment] 2016-03-04 08:59
@janezd i was able to select multiple files with file widget and further i was able to do save configuration of selected files before closing the program . But i am facing to create a new tab within the table widget > 
The problem is I am sending the output signals from filewidget to tablewidget that contains multiple paths but input of table widget is not handling that . Only todo here is to create a new instance because in table widget (test main()) a new tab is opened when new instance is called and it's working fine

Please guide me ! for the new Tab thing

**Comment by janezd** [comment] 2016-03-04 15:58
Please read my explanation above. We could, in principle, adapt the table widget to select a data set out of the list. But we would have to do the same for *all* other widgets, too. We'd like to do exactly the opposite - move the selection of a sheet (from a single file) to the file widget.

**Comment by rahulroxx** [comment] 2016-03-04 16:37
@janezd I am not able to get the whole thing as I am new to this project but I want to learn through this issue  . It Would be nice if you please elaborate more  Thanks  :+1: 

> We'd like to do exactly the opposite - move the selection of a sheet (from a single file) to the file widget.

**Comment by janezd** [comment] 2016-03-04 19:26
Sure.

As I wrote above, when the user opens an Excel file (a single file!) the File widget should check whether there are multiple (non-empty) sheets. If there is just one, it loads it just like now. If there are multiple, a new combo appears in the widget (well, the combo is always there, but hidden when it is not needed) that allows the user to select the sheet. The combo is populated with the sheet names and the first sheet is selected and loaded by default.

Furthermore, assume I select the third sheet. Then I close Orange and open it again: the third sheet must be selected. Also, if I load another file and select, say, the fifth sheet, but then load the first file again, the third sheet must again be selected. Therefore, the widget must remember the selected sheet for each file that was loaded in the past.

The latter is somewhat more difficult since it is accomplished by context settings. You can implement the rest first and then get some assistance with storing the settings.

**Comment by rahulroxx** [comment] 2016-03-05 16:20
@janezd For Mutiple sheets I need to embed xlrd module for fetching multiple sheets from a single file  . So that will change Orange.data.table function from_file in Table instance  which furthur depends on .io.py because Table take the path as args . [Event handling]  Later , further changes into combobox widgets will be reflected  according to sheet names in excel file (single file) 
Is it what we want ?

**Comment by janezd** [comment] 2016-03-05 20:42
Don't fetch multiple sheets, fetch just their names, so you can show them in the combo. Loading multiple sheets may take too much time since sheets can be huge, and they can be in incorrect format or empty.

So, always load just the currently selected sheet. Method `Orange.data.io.ExcelFormat.read_file` already accept sheet as an argument; you can append the sheet name to the filename, using `:` as a separator (see https://github.com/biolab/orange3/blob/master/Orange/data/io.py#L658).

**Comment by rahulroxx** [comment] 2016-03-05 20:48
@janezd Totally Agreed !

**Comment by rahulroxx** [comment] 2016-03-11 13:17
@janezd Please help me to start Settings for sheets  .

**Comment by janezd** [comment] 2016-03-11 13:19
I would have to see what the code looks like now.

**Comment by rahulroxx** [comment] 2016-03-11 13:22
@janezd #1074

**Comment by janezd** [comment] 2016-03-11 13:24
I'm sorry, I somehow overlooked it.

**Comment by rahulroxx** [comment] 2016-03-11 13:30
@janezd i didn't yet used `ExcelFormat.read(excelfile:sheetname)` , i have passed the filename which and `ExcelFormat.read(excelfile:sheetname)` takes sheet[0] for now ! 
i'll fix this with context settings

**Comment by rahulroxx** [comment] 2016-03-11 13:39
@janezd tell me what i am missing if any ?

**Closed** 2016-04-08 09:53 UTC
