### ISSUE TITLE
[Feature Request]: Custom axis length

### ISSUE THREAD

**Issue by Biolilla** [biolab/orange3#2414] opened 2017-06-20 12:31 UTC
##### Orange version
3.4.2

A suggestion for a new feature from a very naive Orange user!

It would be nice to introduce the possibility to autonomously define axis length in Orange plots. This would allow a better comparison of different plots.

Thanks!
Ilaria

**Comment by ajdapretnar** [comment] 2017-09-08 10:20
Duplicate of #2109. (sort of, added explanation)

**Closed by ajdapretnar** 2017-09-08 10:20 UTC
Labels: enhancement
