### ISSUE TITLE
Line Chart widget doesn't work in 3.27.1

### ISSUE THREAD

**Issue by ddonadel** [biolab/orange3#5291] opened 2021-02-19 16:27 UTC
See the attached workflow, log (level 4) and dataset. Thank you

Same issue as #5244.

**Comment by ddonadel** [comment] 2021-02-19 16:34
#5244

**Comment by ddonadel** [comment] 2021-02-19 16:35
[linechart_bug.zip](https://github.com/biolab/orange3/files/6011490/linechart_bug.zip)

**Comment by janezd** [comment] 2021-02-19 17:52
Thanks for the workflow and the data.

I'm closing this as a duplicate of #5244, but I wrote a note there that the data and the workflow can be found here.

Thanks!

**Closed by janezd** 2021-02-19 17:52 UTC
