### ISSUE TITLE
Linear Discriminant Analysis in Linear Projection widget

### ISSUE THREAD

**Issue by bmatyasb** [biolab/orange3#5598] opened 2021-09-20 13:33 UTC
![shot](https://user-images.githubusercontent.com/91070973/134011556-374ed327-ce7f-4f22-8c28-cf58d36e5d31.jpg)
Hi!
I want to use the Linear Discriminant Analysist, which is in the Linear Projection widget.
I have tried many datasets, but I get error messages.
For the iris dataset for example:
``` An error occurred while projecting data. y should be a 1d array, got an array of shape (150, 0) instead. ```

- Operating system: Win 10 Home
- Orange version: 3.29.9
- How you installed Orange: I used the standalone installer

**Comment by ajdapretnar** [comment] 2021-09-20 13:58
Duplicate of #5359.

**Closed by ajdapretnar** 2021-09-20 13:58 UTC
Labels: bug report
