### ISSUE TITLE
Rename Transform widget to something more explicit

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3551] opened 2019-01-25 08:14 UTC
Perhaps "Apply preprocessor" or something as descriptive could be clearer.

Originally idea from @borondics.

**Comment by janezd** [comment] 2019-01-25 09:18
I started renaming, but then I realized that "Apply preprocessor" is not a really good name since it implies that the input must be some kind of preprocessor (well, the widget already indicates so...) in a "narrow sense". This may be misleading; preprocessor would often come from widgets that compute, for instance, some projection, which many users won't associate with preprocessing.

I support the idea, but we should look for a better name.

**Comment by janezd** [comment] 2019-02-28 21:59
Unclear name caused by the ambiguity about what this widget actually does; see #3623.

**Comment by janezd** [comment] 2019-03-15 10:55
Fixed in #3673.

**Closed by janezd** 2019-03-15 10:55 UTC
