### ISSUE TITLE
[Request] Parallel Coordinates and Star Coordinates

### ISSUE THREAD

**Issue by jonwoodring** [biolab/orange3#1658] opened 2016-10-12 16:08 UTC
I'm new to Orange, so I may have missed it if any one of them already exists.

**Comment by kernc** [comment] 2016-10-14 19:44
Correct me if I'm wrong. Duplicate of https://github.com/biolab/orange3/issues/1329.

**Comment by jonwoodring** [comment] 2016-10-18 16:35
Partially.

Parallel coordinates and star coordinates are not just subplots of scatterplots, but specific high dimensional plot-types.

**Comment by jonwoodring** [comment] 2016-10-18 16:36
https://en.wikipedia.org/wiki/Parallel_coordinates

**Comment by jonwoodring** [comment] 2016-10-18 16:38
Star coordinates are like the linear plot, but gives you the ability to rotate and scale any of the axes to explore the relationships between dimensions.

**Comment by jonwoodring** [comment] 2016-10-18 16:39
http://people.cs.vt.edu/~north/infoviz/starcoords.pdf

**Comment by ajdapretnar** [comment] 2016-10-19 08:54
I agree. I'm taking out only Scatterplot Matrices, since this is indeed a duplicate, but the other two are not. Also +1 on Star Coordinates, these would be great with our Tweet Profiler widget!

**Comment by jonwoodring** [comment] 2016-10-19 14:06
Thanks!

**Comment by ajdapretnar** [comment] 2018-01-11 09:57
Parallel Coordinates now introduced in Prototypes.
Star Coordinates seems similar to Freeviz. And since we also introduced Radviz, both for vizualizing relations between dimensions, I suggest we close this. I believe we won't be introducing a third similar visualization. I hope you like the two vizualizations proposed.

**Closed by ajdapretnar** 2018-01-11 09:57 UTC
Labels: wishlist

**Comment by liar666** [comment] 2021-07-13 16:34
Hi,

Using Orange3 3.29.3, I cannot find "Parallel Coordinates" neither in "Prototypes" nor in any other category. Has it been removed or renamed?
