### ISSUE TITLE
Cannot Install on Windows 10 - See Error

### ISSUE THREAD

**Issue by asrichardson821** [biolab/orange3#4485] opened 2020-03-02 19:15 UTC
I am trying to re-install the current version of Orange on a Windows 10 machine. I keep getting the following install errors:

![image](https://user-images.githubusercontent.com/15249123/75709173-255b2e00-5c90-11ea-85ad-2fd2a545957b.png)

![image](https://user-images.githubusercontent.com/15249123/75709189-2e4bff80-5c90-11ea-8268-bbbf41c3a372.png)

here is the location of the failed script - LinkError: post-link script failed for package <unknown>::qt-5.12.5-h7ef1ec2_0
location of failed script: C:\Users\richardsona4\AppData\Local\Orange\Scripts.qt-post-link.bat

**Comment by fmallea666** [comment] 2020-03-03 18:25
I´m having the same problem.
Did you fix it?

**Comment by asrichardson821** [comment] 2020-03-03 20:16
No, not yet - I believe this is a build issue. as I have tried to install on two different windows 10 machines and I have the same problem. I hope they fix it soon.

**Comment by markotoplak** [comment] 2020-03-03 21:42
Thanks for your report. Did perhaps anyone reading this manage to install Orange on Windows 10?

@fmallea666, @asrichardson821, which languages / input settings are you using on your system? Could you please try something out to help us debug this? If you open a command prompt, what does running "chcp" there (typing chcp and pressing enter) give you?

**Comment by markotoplak** [comment] 2020-03-03 21:49
Also, what does `echo %PATH%` in windows command prompt show?

**Comment by fmallea666** [comment] 2020-03-04 11:55
Hi Marko
In the command prompt 
![image](https://user-images.githubusercontent.com/61754262/75877133-c4e60100-5df5-11ea-9dd1-27b9f0e99154.png)

with the second one 
![image](https://user-images.githubusercontent.com/61754262/75877185-e21acf80-5df5-11ea-9ef5-e9d02c579214.png)

**Comment by asrichardson821** [comment] 2020-03-04 14:18
Hi Marko, 

Please see below; chcp does not run for me.
![image](https://user-images.githubusercontent.com/15249123/75888157-f0b6b600-5df8-11ea-92f2-6ff5479f3961.png)

echo on %PATH%
![image](https://user-images.githubusercontent.com/15249123/75888240-0f1cb180-5df9-11ea-8f2f-766077e95293.png)

**Comment by ajdapretnar** [comment] 2020-03-04 14:47
I think you need to run `chcp` without quotation marks.

**Comment by asrichardson821** [comment] 2020-03-04 14:55
yes, I tried both ways; it does not run even w/o quotation marks.

![image](https://user-images.githubusercontent.com/15249123/75891752-3cb82980-5dfe-11ea-84c0-a5d5d5e0b367.png)

**Comment by markotoplak** [comment] 2020-03-04 15:24
@asrichardson821, your PATH variable seems that is broken. See for example [this stackoverflow question](https://stackoverflow.com/questions/8142058/chcp-is-not-recognized-as-an-internal-or-external-command-operable-program-or). This can happen because some previous installations (of other software) accidentally cleared it. See stackoverflow answer and set [correct path in your windows settings](https://www.java.com/en/download/help/path.xml).

@fmallea666, do you really get exact same error message? Your path seems to be fine.

**Comment by fmallea666** [comment] 2020-03-04 16:33
Hi
I run It again and it shows:

[image: image.png]
[image: image.png]







<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by asrichardson821** [comment] 2020-03-04 18:16
Thank you @markotoplak and @ajdapretnar . I have since fixed the variables, I believe I am using the US English language settings.

![image](https://user-images.githubusercontent.com/15249123/75909602-667f4980-5e1a-11ea-924b-9f1ce24db657.png)

**Comment by markotoplak** [comment] 2020-03-04 18:29
@fmallea666, we can not see the images you posted. It would be perhaps easiest if you just copied the last few lines of the log.

@asrichardson821, did installation work now? Or are you still seeing the same problem? Are you installing only for you or for all users on the machine?

**Comment by fmallea666** [comment] 2020-03-04 22:58
1. For CHCP:


C:\Users\Felipe Mallea>chcp
Página de códigos activa: 850

C:\Users\Felipe Mallea>


2. For "Echo %PATH%":

C:\Users\Felipe Mallea>echo %PATH%
C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS
Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program
Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
(x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
Files\Intel\Intel(R) Management Engine
Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Users\Felipe
Mallea\AppData\Local\Microsoft\WindowsApps;

C:\Users\Felipe Mallea>


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by asrichardson821** [comment] 2020-03-05 04:21
@markotoplak @ajdapretnar I tried to re-install, but I received two errors:

1) The install wizard could not install "Miniconda" Menus

2) This Python Error:

![image](https://user-images.githubusercontent.com/15249123/75947580-e7683080-5e6e-11ea-8b0a-228c72160316.png)

**Comment by janezd** [comment] 2020-03-06 11:08
These appear to be machine-specific problems that we can't reproduce. The problem seems to be in conda, not in Orange. If we knew what it was, we could try to circumvent it -- but as it stands now, we can't. Try removing everything related to Orange and conda and try again.

We're closing the issue for now, and wait for when/if we have more reports and more information about what is going on.

**Closed by janezd** 2020-03-06 11:08 UTC
Labels: bug report

**Comment by Novus01** [comment] 2020-04-10 14:41
I seem to have the same (similar) problem 

Dell latitude with recent upgrade to windows10: install latest orange3 version.

Error message identical to above (either via miniconda cmd line or with the windows exe).
I had python 3.7 already installed - relevant?

Any solution available yet?
If I need to check something, just let me know.

thx
PS installed on another PC as temp solution.
