### ISSUE TITLE
Edit Domain resets when reopening orange

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#6414] opened 2023-04-14 22:04 UTC
### Discussed in https://github.com/biolab/orange3/discussions/6412

<div type='discussions-op-text'>

<sup>Originally posted by **zikook** April 14, 2023</sup>
Hi,
When I close and reopen Orange, changes I've made in Edit Domain, for example naming a variable, sometimes disappear.
This happens when I use the widget 'Create Table' from the Educational tab to send it a table.
I can upload a workflow if it helps.
Anyone experienced this? Is there a workaround?
Thanks,
-Aaron</div>

**Comment by janezd** [comment] 2023-04-14 22:04
@zikook, thanks. You can upload the workflow (please do), but I'm pretty sure what I'll find there. And it's a bit complicated to explain.

Note to self (or anybody): this widget shouldn't have context settings but a rather permanent-ish storage of "variable hints".

"Permanent-ish": not storing more than 1000 variables or something, so they're not kept indefinitely. LRU.

**Comment by AOSTern** [comment] 2023-11-27 15:57
HI, I am working with version 3.36.1 on a windows enviroment and Edit Domain forgot my settings. I had already renamed over 100 values (complex names and categories). This was quite frustrating. It was even more frustrating to find out that it was supposed to have been fixed already. 

The work flow goes from import CSV to Edit Domain to Table.

I think the issue arrived when I disconnected the flow of data to the Edit Domain item and then reconnected it again. 

I tried to open a previous version of the Edit Domain in a file that i had saved as backup and foud that that Edit Domain had also forgotten the changes.

Thank you in advance for looking into this again.

**Comment by markotoplak** [comment] 2023-11-28 09:55
Something like this should not happen in 3.36 anymore. Are you absolutely sure that the reconnected file had all edited variables (with the same names and types)?

**Comment by AOSTern** [comment] 2023-11-28 14:03
For this particular project, I use just one master csv file that never gets any editing done on it and it just reconects with the flow upon opening the workflow. At one point all the data on the Edit Domain just went blank. I am trying to recall all previous steps to the earasure and there might have been a connection of a formula box that created a new (undesirable) variable (downstream) (undesirable because it had remained on the list from earlier use). I created the desired variable in the formula box and then tried to use an additional Edit Domain box (independently created) to change the domain of the newly created variable (I know it sounds overtly complicated but I am mostly just taking advantage of the high flexibility of conectors and stuff). Anyways at some point that did not work and I disconnected the formula boxes and the new Edit Domain boxes (which I had just created). At that point I reconnected everything back and noticed that I had lost all the original changes in the domain box I had not touched, the one that connects with the CSV directly. After that I reopened and earlier copy (backup) of the workflow only to find out that that Edit Domain had also lost its features.

I hope this helps you to diagnose the problem.

At the moment I have redone all the Edit Domain stuff but have not closed the file (as I don't want to lose all the info again). As soon as I finish gathering all the info from the project (the final analysis) and can close the file again I will try to reproduce the failure to better document it. Thank you again for your attention to this.

**Comment by markotoplak** [comment] 2023-11-29 13:24
I tried replicating your problems by renaming variables and changing types, and could not get anything like you observed.

Could you answer some questions that would help me debug, please? How many variables did you edit in the edit domain (approximately)? What is the type of variable you were working with? Numeric or categorical? If categorical, how many values do your variables have?

I suspect your problem has something to do with matching categorical features. Maybe values didn't match in different data versions, thus the settings seemed lost.

**Comment by markotoplak** [comment] 2023-11-30 14:01
@AOSTern, I found the likely problem. Closed in favor of #6660.

**Closed by markotoplak** 2023-11-30 14:01 UTC
