### ISSUE TITLE
Discretize gives me lots of erros

### ISSUE THREAD

**Issue by jamartinh** [biolab/orange3#991] opened 2016-01-26 08:53 UTC
```
data/anaconda3/envs/py35/lib/python3.5/site-packages/sklearn/metrics/classification.py:976: DeprecationWarning: From version 0.18, binary input will not be handled specially when using averaged precision/recall/F-score. Please use average='binary' to report only the positive class performance.
  'positive class performance.', DeprecationWarning)
--------------------------------------------------------------------------------
KeyError                                      Traceback (most recent call last):
  File "/home/jamh/sources/orange3/orange3/Orange/canvas/scheme/widgetsscheme.py", line 680, in process_signals_for_widget
    handler(*args)
  File "/home/jamh/sources/orange3/orange3/Orange/widgets/data/owdiscretize.py", line 241, in set_data
    self._update_points()
  File "/home/jamh/sources/orange3/orange3/Orange/widgets/data/owdiscretize.py", line 318, in _update_points
    points, dvar = induce_cuts(state.method, self.data, var)
  File "/home/jamh/sources/orange3/orange3/Orange/widgets/data/owdiscretize.py", line 304, in induce_cuts
    dvar = _dispatch[type(method)](method, data, var)
KeyError: <class 'collections.Default'>
--------------------------------------------------------------------------------
AssertionError                                Traceback (most recent call last):
  File "/home/jamh/sources/orange3/orange3/Orange/widgets/data/owdiscretize.py", line 85, in initStyleOption
    extra = self.cutsText(state)
  File "/home/jamh/sources/orange3/orange3/Orange/widgets/data/owdiscretize.py", line 118, in cutsText
    assert False
AssertionError
--------------------------------------------------------------------------------
AssertionError                                Traceback (most recent call last):
  File "/home/jamh/sources/orange3/orange3/Orange/widgets/data/owdiscretize.py", line 85, in initStyleOption
    extra = self.cutsText(state)
  File "/home/jamh/sources/orange3/orange3/Orange/widgets/data/owdiscretize.py", line 118, in cutsText
    assert False
AssertionError
--------------------------------------------------------------------------------
AssertionError                                Traceback (most recent call last):
  File "/home/jamh/sources/orange3/orange3/Orange/widgets/data/owdiscretize.py", line 85, in initStyleOption
    extra = self.cutsText(state)
  File "/home/jamh/sources/orange3/orange3/Orange/widgets/data/owdiscretize.py", line 118, in cutsText
    assert False
AssertionError
```

**Comment by ales-erjavec** [comment] 2016-01-26 12:06
I can't duplicate this.

The first error seems to be the suspect. The `<class 'collections.Default'>` is not something which should even exist. The owdiscretize module defines a `Default` namedtuple but the class's module should be correctly set to `Orange.widgets.data.owdiscretize`. Can you please run:

    python -c "from Orange.widgets.data import owdiscretize; print(owdiscretize.Default)"

Does it output `<class 'Orange.widgets.data.owdiscretize.Default'>`?

**Comment by jamartinh** [comment] 2016-01-26 13:06
<class 'Orange.widgets.data.owdiscretize.Default'>

**Comment by ajdapretnar** [comment] 2016-04-13 08:05
@jamartinh Have you solved the issue or does it still remain?

**Comment by jamartinh** [comment] 2016-05-03 08:21
Hi, the Discretize widget still gives tons of error. For example, assertion errors on cut_off

It also seems to have troubles with the Domain, it does not refresh the Domain correctly, and remember input variables that are not actually in the Table.

**Comment by ajdapretnar** [comment] 2016-05-03 08:47
@jamartinh Huh, I'm having a hard time reproducing this. I tested Discretize with iris.tab, wine.tab, housing.tab and three Google Sheets data sets with and without NaNs. Everything works fine for me.
Also I'm not experiencing any problems with the Domain when changing data sets.
Could you send an .ows to reproduce the error?

**Comment by ajdapretnar** [comment] 2016-06-24 08:30
@jamartinh Please send the workflow, since I can't reproduce any of this. Alternatively, I can close the issue.

**Comment by ajdapretnar** [comment] 2016-07-28 10:36
I am closing this since I can't reproduce and it is a very stale issue. If the problem persists, please open a new issue. Tnx!

**Closed by ajdapretnar** 2016-07-28 10:36 UTC
