### ISSUE TITLE
BUG: F1, Precision, Recall computation + NN AUC mismatch

### ISSUE THREAD

**Issue by dsanalytics** [biolab/orange3#5829] opened 2022-02-05 00:47 UTC
Posting more than one bug in one message as they may be related.
1) It seems that Orange is not computing F1, Precision, and Recall correctly [4]. I used my own calculations [3] plus consulted online CM sites [1][2] which matched mine. CA seems correct. I sincerely hope that I missed something.
2) It seems that UAC for NN differs between Test & Score and Prediction reports [4], although I used the same data (training data) and got the same Confusion Matrix. LR UACs match. NN does not have Replicable Training option checked, but that should not matter as both results are computed post training. All other measures for NN match between both reports (CA, F1, Precision, Recall).

Example data: http://faculty.cas.usf.edu/mbrannick/regression/Logistic.html
(selected Treatment of Anger as numeric as LR kept splitting it into 2 features while categorical)

[1] Confusion Matrix - Online Calculator
https://www.mdapp.co/confusion-matrix-calculator-406/ 
[2] Confusion Matrix Calculator
https://www.onlineconfusionmatrix.com/ 
[3] My own calculations
![image](https://user-images.githubusercontent.com/32625394/152620848-c5a2a92b-ca62-4d24-8a4f-0756029e70b8.png)

[4] Workflow screenshot:
![image](https://user-images.githubusercontent.com/32625394/152620346-1616bc20-c80d-407a-a658-e06f57a84fc1.png)

**Comment by janezd** [comment] 2022-02-07 10:31
Duplicate of #5743 and #5764.

**Closed by janezd** 2022-02-07 10:31 UTC
Labels: bug report

**Comment by dsanalytics** [comment] 2022-02-07 11:50
@ajdapretnar @markotoplak I checked #5743 and #5764 and it seems to me that in my case, "Target Class" was not the issue, as I both trained and ran predictions on the training data, hence did not use the test data. Thoughts?
