### ISSUE TITLE
Data Table widget not saving selection

### ISSUE THREAD

**Issue by iva-c** [biolab/orange3#4184] opened 2019-11-12 10:54 UTC
Data table does not save all selected data and always resets to no data selected upon the reopening of the workflow.

**Comment by PrimozGodec** [comment] 2019-11-13 13:54
@iva-c I cannot reproduce this issue. What version of Orange do you use? I remember it was an issue but it must be fixed now.

**Comment by iva-c** [comment] 2019-11-14 21:27
I haven't managed to reproduce it either, I guess I called it too early. So, I'm closing this issue.

**Comment by iva-c** [comment] 2019-11-15 13:19
Came acorss a workflow where this happens. 
[human_osteoarthritis.zip](https://github.com/biolab/orange3/files/3851621/human_osteoarthritis.zip)

Orange version: 3.22
OS: W10

**Comment by PrimozGodec** [comment] 2019-11-29 10:53
I was able to reproduce the issue on macOS too (Orange version 3.23.1, master).
What I found out is that when data comes from PCA (either components or transformed data) the selection is not saved. Here is the simplified workflow that shows the issue.

[human_osteoarthritis – kopija.ows.zip](https://github.com/biolab/orange3/files/3904846/human_osteoarthritis.kopija.ows.zip)

**Closed** 2019-12-20 07:13 UTC
Labels: bug, friday
