### ISSUE TITLE
Feature Constructor: data corruption

### ISSUE THREAD

**Issue by chourroutm** [biolab/orange3#5928] opened 2022-03-31 12:15 UTC
**What's wrong?**

Following on #5917 and #5918, I obtained a minimal reproducible example from the Iris dataset using the Feature Constructor widget:
```
----------------------------- KeyError Exception ------------------------------
Traceback (most recent call last):
  File "/home/chourroutm/.orange-env/lib/python3.8/site-packages/Orange/widgets/data/owgroupby.py", line 384, in __rows_selected
    active_aggregations = [self.aggregations[attr] for attr in selected_attrs]
  File "/home/chourroutm/.orange-env/lib/python3.8/site-packages/Orange/widgets/data/owgroupby.py", line 384, in <listcomp>
    active_aggregations = [self.aggregations[attr] for attr in selected_attrs]
KeyError: ContinuousVariable(name='petal_area', number_of_decimals=3, compute_value=FeatureFunc('petal_length*petal_width', [('petal_length', ContinuousVariable(name='petal length', number_of_decimals=1)), ('petal_width', ContinuousVariable(name='petal width', number_of_decimals=1))], {}, None))
-------------------------------------------------------------------------------
```

**How can we reproduce the problem?** 

The workflow is attached as [example_corruption_FeatureConstructor.zip](https://github.com/biolab/orange3/files/8389137/example_corruption_FeatureConstructor.zip).

To reproduce, re-enable the link between Feature Constructor and Group By, try to change the Group By behaviour for petal_area and an error will be raised.

**What's your environment?**

- Operating system: Ubuntu 20.04 LTS
- Orange version: 3.31.1
- How you installed Orange: via pip (in an environment)

**Comment by markotoplak** [comment] 2022-08-10 12:45
I have tried this out with 3.31.1 and I reproduces the same error. But with 3.32.0 it works for me. It also works on master.

Thanks for the report. Closing as this is fixed in later versions.

**Closed by markotoplak** 2022-08-10 12:45 UTC
Labels: bug
