### ISSUE TITLE
orange 3.3.3(win) has a bug when run orange-text (1.10) to create wordlcloud

### ISSUE THREAD

**Issue by swayblue** [biolab/orange3#1221] opened 2016-05-03 08:36 UTC
##### Orange version

orange 3.3.2 window  release
orange-text 0.1.10

##### Expected bahavior
when run orange-text to create wordcloud

##### Actual behavior
when run the has error ,"AttributeError: 'module' object has no attribute 'TableWidget"

##### Steps to reproduce the behavior
1.insert sample text 
2.choose icon wordcloud to creat cloud 
3.then the error come

##### Additional info (worksheets, data, screenshots, ...)
when i look the reason for this error ,find info like this:
1.you rewrite the //orange//widgets//gui.py,and has so many change to the 3.3.1 version
2.the most import thing is  u  delete the chass "TableWidget" and "WebviewWidget",but the the orange-text 0.1.10  always use it (owwordcloud.py),for this ,the error coming
![error](https://cloud.githubusercontent.com/assets/19164883/14978253/1a67f3ee-114d-11e6-894a-daa957eb2fc0.png)

**Comment by ajdapretnar** [comment] 2016-05-03 08:49
@swayblue Thank you for reporting this. I'm having an issue just with placing the Wordcould widget onto canvas.
Big thanks for additional info, will fix this asap!

**Comment by ajdapretnar** [comment] 2016-05-03 09:11
@swayblue Update: there's a PR waiting to be merged already, so you can expect the fix soon.

**Comment by kernc** [comment] 2016-05-03 11:19
Closed as duplicate of https://github.com/biolab/orange3/pull/1217.

@swayblue Thanks. If you need an urgent workaround, please try [version 3.3.1](https://github.com/biolab/orange3/tags).

**Closed by kernc** 2016-05-03 11:19 UTC

**Comment by ales-erjavec** [comment] 2016-05-03 12:57
Note that the Orange 3.3.1 installer can be downloaded from http://orange.biolab.si/download/files/Orange3-3.3.1.dev0%2b5d39ea2.win32-py3.4-install.exe
