### ISSUE TITLE
Installation problem on windows

### ISSUE THREAD

**Issue by kaonL0** [biolab/orange3#3408] opened 2018-11-22 00:26 UTC
##### Orange version
Orange3-3.18.0-Miniconda-x86_64.exe

##### Expected behavior
Launch Orange3 when i click on desktop icon

##### Actual behavior
Do nothing...
When I launch manually (python -m Orange.canvas), I got an error : Original error was: cannot import name 'multiarray'
Seem have no multiarray.py file in numpy/core directory only multiarray.cp36-win32.pyd
Tried to set PYTHONPATH

##### Steps to reproduce the behavior
install Orange3-3.18.0-Miniconda-x86_64.exe
on windows 10 Famille
Version 1803
Version : 17134.407
System 64bits, x64

##### Additional info (worksheets, data, screenshots, ...)
In AppData/Roaming/Python/Python3.6/
So I deleted numpy and numpy dist, then git clone https://github.com/numpy/numpy.git
Got new error with scipy : import scipy error: cannot import name '_ccallback_c'
So I deleted scipy and scipy dist, then git clone https://github.com/scipy/scipy.git
Then installed : python setup.py install --user
Got lots of error, Processing scipy\io\matlab\mio_utils.pyx
```
ModuleNotFoundError: No module named 'Cython'
Traceback (most recent call last):
  File "C:\Users\loicd\AppData\Roaming\Python\Python36\site-packages\scipy\tools\cythonize.py", line 93, in process_pyx
    r = subprocess.call(['cython'] + flags + ["-o", tofile, fromfile], cwd=cwd)
  File "C:\ProgramData\Miniconda3\lib\subprocess.py", line 267, in call
Processing scipy\io\matlab\streams.pyx
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Miniconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
Processing scipy\linalg\cython_blas.pyx
  File "C:\ProgramData\Miniconda3\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```
Then i tried again launching Orange with shortcut : it works ! But my scipy lib is not stable...
I don't know how to get out of that properly, thx.

**Comment by kaonL0** [comment] 2018-11-22 00:34
And when i launch, i don't have all widget (only 2 in visualisation)

**Comment by kaonL0** [comment] 2018-11-28 21:02
I am sure I installed with Orange3-3.18.0-Miniconda-x86_64.exe
I probably had another version of anaconda installed before
I redo installation right now with AppData/Roaming/Python/Python3.6/numpy and scipy deleted (i'll give you feedback)

C:\Users\loicd>C:\ProgramData\Miniconda3\Scripts\conda info
Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Miniconda3  (read only)
    default environment : C:\ProgramData\Miniconda3
       envs directories : C:\ProgramData\Miniconda3\envs
                          C:\Users\loicd\AppData\Local\conda\conda\envs
                          C:\Users\loicd\.conda\envs
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\loicd\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\loicd\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.17134

**Comment by kaonL0** [comment] 2018-11-28 22:19
So I deleted AppData/Roaming/Python/Python3.6/numpy and AppData/Roaming/Python/Python3.6/scipy
I reinstall  Orange3-3.18.0-Miniconda-x86_64.exe
C:\ProgramData\Miniconda3\Lib\site-packages\numpy and C:\ProgramData\Miniconda3\Lib\site-packages\scipy seems well installed it was proably a conflict with other versions

I can launch Orange3, but I still don't have all widgets 

![image](https://user-images.githubusercontent.com/2285622/49186140-0de21680-f364-11e8-9902-68f787237bba.png)

**Comment by janezd** [comment] 2019-01-24 20:34
I guess we can close this. We can't replicate and we hope it either went away or was caused by something peculiar.

**Closed by janezd** 2019-01-24 20:34 UTC
