### ISSUE TITLE
Select Rows selects all the rows, disregarding the filter?

### ISSUE THREAD

**Issue by enjoysmath** [biolab/orange3#4460] opened 2020-02-26 17:33 UTC
Input Data that clearly shows Past/Future column has both P and F values: (It is a "Meta attribute"):

![image](https://user-images.githubusercontent.com/1606391/75370076-6b238b00-5879-11ea-836a-47262abd7e9a.png)

Here's my Select Rows settings:
![image](https://user-images.githubusercontent.com/1606391/75370253-a9b94580-5879-11ea-89b8-ae5fb7a30817.png)

And here's a Data Table view on the output side of Select Rows (showing "Matching Data"):
![image](https://user-images.githubusercontent.com/1606391/75370347-cb1a3180-5879-11ea-98ed-d824acbc7cf1.png)

##### Orange version
Version: 3.24

##### Expected behavior
For SelectRows widget to only select the rows marked "F" in the Past/Future column and for the output Data Table to reflect this.

##### Actual behavior
No filtering is done, the entire input Data Table is displayed in the output Data Table.

##### Steps to reproduce the behavior
1. Download the attached files.
2. Open up the workflow in Orange.
3. In the very first input widget (.tab data) locate the accompanied BinaryData.tab file.
4. Click reload in Orange on the input widget.
5. Wait 1 minute for it to load.
6. Select "F" in the bottom "Select Future Data (for Testing)" Select Rows widget.  This is another bug, I am always having to select "P" / "F" in the two Select Rows widgets regardless of saving the .ows file.
7. View the input / output Data Tables that are on the workflow to verify that no rows get filtered out.

##### Additional info (worksheets, data, screenshots, ...)
[BinaryPredictions7.zip](https://github.com/biolab/orange3/files/4257250/BinaryPredictions7.zip)

Here is a much smaller data file that will load a lot more quickly and that exhibits the same bug:
[BinaryData (2).zip](https://github.com/biolab/orange3/files/4257308/BinaryData.2.zip)

**Comment by janezd** [comment] 2020-02-26 17:46
Thanks for a very exact description. Unfortunately --- it works for me.

<img width="753" alt="Screenshot 2020-02-26 at 18 39 47" src="https://user-images.githubusercontent.com/2387315/75371721-87e6af80-58c7-11ea-9e97-806d34f2058b.png">

As you can see in the screenshot, the widget outputs 19213 rows. I've noticed, though, that Neural network takes ages, and other widgets are not updated yet (see the red dots on your "Test and Score"). I also suspect that GUIs are not entirely updated because your screeenshot of Select Rows is missing the information on input data.

Is it possible that you just have to wait for a bit longer? I don't see how such a trivial but in Select Rows would go unnoticed.

The bug that you mention in step 6 is most probably a duplicate of #4415 and should be fixed by #4421.

**Comment by enjoysmath** [comment] 2020-02-26 18:15
@janezd 

Thank your for your prompt reply.  After deleting the NN node, I'm getting that one of them is working (the Past Selector) and that the other is not (Future). 

I will try that bugfix you mentioned.

I will also try earlier and earlier versions until it works properly.   I was not having the issue before at some point.

**Comment by janezd** [comment] 2020-02-26 19:19
I think that the fix won't have any effect on an existing workflow.

I'm closing this for now. If you can replicate this with a smaller data set and/or without time consuming widgets, please let us know.

**Closed by janezd** 2020-02-26 19:19 UTC
