### ISSUE TITLE
No widget in Orange3

### ISSUE THREAD

**Issue by kingaza** [biolab/orange3#1753] opened 2016-11-15 07:45 UTC
I install Orange3 3.3.8 on win7.
After open canvas, the main UI opens.
However, no widget lists are available.

**Comment by kernc** [comment] 2016-11-15 13:35
Does [running with `-l 4`](https://github.com/biolab/orange3/issues/1286#issuecomment-222331975) produce any helpful output?

**Comment by kingaza** [comment] 2016-11-17 04:32
here is my log

(D:\05_Software\Anaconda) C:\Users\hejiew>D:\05_Software\Anaconda\Scripts\orange
-canvas.exe -l 4
Starting 'Orange Canvas' application.
Starting CanvasApplicaiton with argv = ['D:\\05_Software\\Anaconda\\Scripts\\ora
nge-canvas-script.py'].
Adding search path 'orange' for prefix, 'canvas_icons'
Setting up Canvas main window.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Scheme node properties sync (changed: False)
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Setting scheme '<Orange.canvas.scheme.widgetsscheme.WidgetsScheme object at 0x00
0000000539DEE8>' on 'CanvasScene(objectName='', ...)'
Stack transition start ()
Stack transition finished ()
Dock transition finished (new width 116)
Dock transition started.
Loading widget registry cache ('C:\\Users\\hejiew\\AppData\\Roaming\\Orange\\3.3
.8\\Cache\\canvas\\registry-cache.pck').
Running widget discovery process.
Could not load 'Orange Widgets = Orange.widgets' (unsatisfied dependencies).
Traceback (most recent call last):
  File "D:\05_Software\Anaconda\lib\site-packages\Orange\canvas\registry\discove
ry.py", line 89, in run
    point = entry_point.load()
  File "D:\05_Software\Anaconda\lib\site-packages\setuptools-23.0.0-py3.5.egg\pk
g_resources\__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "D:\05_Software\Anaconda\lib\site-packages\setuptools-23.0.0-py3.5.egg\pk
g_resources\__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "D:\05_Software\Anaconda\lib\site-packages\setuptools-23.0.0-py3.5.egg\pk
g_resources\__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'keyrings.alt' distribution was not foun
d and is required by the application
Saving widget registry cache with 1 entries ('C:\\Users\\hejiew\\AppData\\Roamin
g\\Orange\\3.3.8\\Cache\\canvas\\registry-cache.pck').
'set_global_registry()' - setting registry.
Setting registry '<Orange.canvas.registry.qt.QtWidgetRegistry object at 0x000000
00063B8318> on 'CanvasScene(objectName='', ...)'.
Entering main event loop.

**Comment by astaric** [comment] 2016-11-17 07:49
Runing pip install keyrings.alt should fix the problem. We are aware of the issue, the problem is that the keyrings.alt does not (yet) exists as a conda package and cannot be installed automatically.

I have opened the issue at the corresponding conda-forge repository (https://github.com/conda-forge/orange3-feedstock/issues/12).

**Comment by astaric** [comment] 2016-11-29 22:14
The issue has been fixed in the feedstock. keyring and keyrings.alt package are now installed as dependencies when installing with conda.

**Closed by astaric** 2016-11-29 22:14 UTC

**Comment by kingaza** [comment] 2016-12-10 10:21
thx

**Comment by cosmin** [comment] 2017-03-14 22:38
I still got the same issue when installing with conda. `keyring` was installed, however `pywin32-ctypes` is required by `keyring` and this was not installed when installing through `conda`. The solution was to manually install `pywin32-ctypes` through `pip`.
