### ISSUE TITLE
Rank: crash on missing class values

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1089] opened 2016-03-09 13:54 UTC
Rank widget crashes on missing class values. Seems to be a ReliefF problem. When the problem is fixed, check ranking in both Rank and Scatter Plot widgets.

**Comment by wadhwasahil** [comment] 2016-03-09 14:36
What output do you want in case of missing class?

**Comment by wadhwasahil** [comment] 2016-03-09 14:54
Can you provide the data file where crash is happening?

**Comment by shark-S** [comment] 2016-03-10 15:25
@ajdapretnar if class is missing then it also effect on model we choose and plot graph also  so we have to remove that section which is incomplete? and also if only data table in rank is corrected then it can give wrong results. can you guide in this?

**Comment by ajdapretnar** [comment] 2016-03-10 15:46
There's already a PR in the making by one student. The idea was to purge the instances with missing class values for ReliefF.

**Comment by shark-S** [comment] 2016-03-10 16:22
Got it thanks for help.

**Comment by wadhwasahil** [comment] 2016-03-11 07:56
@ajdapretnar So should we leave this issue?

**Comment by ajdapretnar** [comment] 2016-03-11 07:59
For the time being, you can. I'll let you know if the PR is not submitted in due time. Thanks!

**Comment by wadhwasahil** [comment] 2016-03-11 08:01
:+1:

**Comment by kernc** [comment] 2016-03-11 09:22
Duplicate of https://github.com/biolab/orange3/issues/1046.

**Comment by wadhwasahil** [comment] 2016-03-11 09:27
I have a question.
How to check which amongst the radio buttons is selected in pyqt?

**Comment by ales-erjavec** [comment] 2016-03-11 14:07
> How to check which amongst the radio buttons is selected in pyqt?

A QRadioButton inherits a `checked` property from http://doc.qt.io/qt-4.8/qabstractbutton.html#checked-prop, you can access it with `rb.isChecked()`

**Closed** 2016-03-12 22:53 UTC
Labels: easy
