### ISSUE TITLE
MDS crashes when feed column distances

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#3328] opened 2018-10-23 19:58 UTC
##### Orange version
3.16

##### Expected behavior
Just like Hierarchical Clustering, MDS can handle inputs that stem from measuring distances between columns. The behavior of selection of points in MDS visualization should be similar to selection of branch in the dendrogram and should change the composition of the feature domain.

##### Actual behavior
When given column distances, MDS crashes.

Error encountered in widget MDS:

```Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/unsupervised/owmds.py", line 519, in __next_step
    self._update_plot()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/unsupervised/owmds.py", line 584, in _update_plot
    self._setup_plot(new=new)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/unsupervised/owmds.py", line 637, in _setup_plot
    attributes = data.domain.attributes + (self.variable_x, self.variable_y)
AttributeError: 'NoneType' object has no attribute 'domain'
```

##### Steps to reproduce the behavior
See the workflow below. The data set brown-selected was used.

<img width="333" alt="mds-bug" src="https://user-images.githubusercontent.com/726604/47387110-b4584d80-d70e-11e8-83cd-6242790644bf.png">

**Comment by VesnaT** [comment] 2018-10-24 12:57
I'm closing the issue, since I can't reproduce the bug (running code from master). It has probably been (unknowingly) fixed when reorganizing projections.

**Comment by janezd** [comment] 2018-10-24 13:13
I'll piggyback on this issue and reopen it. It doesn't crash, but doesn't work as intended either, and I guess it worked before.

In @BlazZupan's schema, MDS should allow choosing column name (variable name) as a label. If you take, say, Brown data, you should be able to label MDS points with gene names.

**Closed** 2019-02-16 08:36 UTC
Labels: bug
