### ISSUE TITLE
Hierarchial Clustering Missing Data Axis

### ISSUE THREAD

**Issue by stoic74** [biolab/orange3#3778] opened 2019-05-02 18:09 UTC
##### Orange version

3.20.1

##### Expected behavior
All printed dendrograms require display of the axis with values for many reasons. This is true in teaching, public talks, and publication.

##### Actual behavior
Neither a save to PDF or generation of a Report shows the axis.

##### Steps to reproduce the behavior
![Sample Cluster Label](https://user-images.githubusercontent.com/29643579/57096500-49459000-6cca-11e9-97d8-2bedcee2a132.png)

##### Additional info (worksheets, data, screenshots, ...)

A wishlist would be for cluster id to be printed to the right along with a bar matching termini of the cluster being labeled. Besides more easily seeing cluster members one can reference viewers or readers to each cluster ID. A sample drawing is attached.
![Sample Cluster Label](https://user-images.githubusercontent.com/29643579/57096666-ae00ea80-6cca-11e9-84df-7a1c50bc5f9e.png)

**Comment by ajdapretnar** [comment] 2019-05-06 14:03
Duplicate of #1088.

**Closed by ajdapretnar** 2019-05-06 14:03 UTC
